// Component glossary data, extracted from src/pages/ComponentGlossary.tsx.
// Trilingual strings copied verbatim from the source page; aliases, semanticRoles,
// and relatedStateIds are authored here (NET-NEW per the ComponentTerm contract).

import { t } from './localization';
import type { ComponentTerm, ComponentCategoryDef } from './types';

export const componentCategories: ComponentCategoryDef[] = [
  {
    id: 'states',
    title: t('Interaction states', '인터랙션 상태', 'インタラクション状態'),
    description: t(
      'Words for how a component reacts before, during, and after a user action.',
      '누르기 전, 누르는 중, 누른 뒤에 컴포넌트가 어떻게 반응하는지 설명하는 말입니다.',
      'ユーザー操作の前・最中・後でコンポーネントがどう反応するかを表す言葉です。',
    ),
  },
  {
    id: 'controls',
    title: t('Controls', '입력/선택 컨트롤', '入力/選択コントロール'),
    description: t(
      'Buttons, fields, menus, and switches that let people choose or submit something.',
      '버튼, 입력창, 메뉴, 스위치처럼 무언가를 고르거나 제출할 때 쓰는 요소입니다.',
      'ボタン、入力欄、メニュー、スイッチなど、選択や送信に使う要素です。',
    ),
  },
  {
    id: 'navigation',
    title: t('Navigation', '이동과 구조', '移動と構造'),
    description: t(
      'Patterns that help people know where they are and move to another view.',
      '지금 어디에 있는지 알려주고 다른 화면으로 옮겨가도록 돕는 패턴입니다.',
      '現在地の把握と別画面への移動を助けるパターンです。',
    ),
  },
  {
    id: 'feedback',
    title: t('Feedback & overlays', '피드백과 오버레이', 'フィードバックとオーバーレイ'),
    description: t(
      'Temporary messages or layers that explain what just happened or ask for attention.',
      '방금 일어난 일을 알려주거나 잠깐 주의를 끄는 임시 메시지나 레이어입니다.',
      '直前の結果を伝えたり注意を促したりする一時的な表示です。',
    ),
  },
  {
    id: 'layout',
    title: t('Content patterns', '콘텐츠 패턴', 'コンテンツパターン'),
    description: t(
      'Reusable blocks for grouping information, scanning lists, and showing waiting states.',
      '정보를 묶고 목록을 훑고 대기 상태를 보여줄 때 반복해서 쓰는 블록입니다.',
      '情報をまとめ、一覧を読みやすくし、待機状態を示すための再利用パターンです。',
    ),
  },
];

export const components: ComponentTerm[] = [
  {
    id: 'hover',
    category: 'states',
    name: t('Hover', '호버', 'ホバー'),
    aliases: ['hover state', 'mouseover', '마우스오버', '커서 반응', 'ホバー状態', 'マウスオーバー'],
    plain: t(
      'The visual change that appears when the cursor rests on an element.',
      '마우스 커서를 요소 위에 올렸을 때 나타나는 모습 변화입니다.',
      'カーソルを要素に重ねた時に出る見た目の変化です。',
    ),
    useWhen: t(
      'Desktop links, buttons, cards, menu rows, and chart points.',
      '데스크톱의 링크, 버튼, 카드, 메뉴 행, 차트 포인트에서 자주 씁니다.',
      'デスクトップのリンク、ボタン、カード、メニュー行、チャート点でよく使います。',
    ),
    avoidWhen: t(
      'Do not rely on hover alone because touch screens cannot hover.',
      '터치 화면에는 호버가 없으니 핵심 정보를 호버에만 숨기지 마세요.',
      'タッチ画面にはホバーがないため、重要情報をホバーだけに隠さないでください。',
    ),
    semanticRoles: ['interaction-feedback', 'pointer-affordance'],
    relatedStateIds: [],
    example: 'button:hover { background: #111; color: white; }',
  },
  {
    id: 'focus',
    category: 'states',
    name: t('Focus', '포커스', 'フォーカス'),
    aliases: ['focus ring', 'focus state', '포커스 링', '키보드 대상', 'フォーカスリング', 'フォーカス状態'],
    plain: t(
      'The active target for keyboard input, usually shown with an outline or ring.',
      '지금 키보드 입력을 받는 대상이며 보통 테두리나 링으로 표시합니다.',
      'キーボード入力の対象で、通常アウトラインやリングで表示されます。',
    ),
    useWhen: t(
      'Forms, search, menus, modal dialogs, and every keyboard-accessible control.',
      '폼, 검색창, 메뉴, 모달 등 키보드로 다루는 모든 컨트롤에 필요합니다.',
      'フォーム、検索、メニュー、モーダル、キーボード操作可能な全コントロールに必要です。',
    ),
    avoidWhen: t(
      'Removing the focus ring makes the interface hard to use without a mouse.',
      '포커스 표시를 지우면 마우스 없이 쓰기 어려운 화면이 됩니다.',
      'フォーカス表示を消すと、マウスなしで使いづらくなります。',
    ),
    semanticRoles: ['accessibility', 'keyboard-affordance'],
    relatedStateIds: [],
    example: 'input:focus-visible { outline: 3px solid #2563eb; }',
  },
  {
    id: 'active-pressed',
    category: 'states',
    name: t('Active / pressed', '액티브 / 눌림', 'アクティブ / 押下'),
    aliases: ['pressed state', 'selected state', '눌림 상태', '선택 상태', '押下状態', '選択状態'],
    plain: t(
      'The state while a control is being pressed or currently selected.',
      '컨트롤을 누르는 순간, 또는 지금 선택돼 있는 상태를 뜻합니다.',
      '押している瞬間、または現在選択中の状態です。',
    ),
    useWhen: t(
      'Segmented controls, nav tabs, filter chips, and pressed buttons.',
      '세그먼트 컨트롤, 네비게이션 탭, 필터 칩, 눌린 버튼에 씁니다.',
      'セグメント、ナビタブ、フィルタチップ、押下中ボタンで使います。',
    ),
    avoidWhen: t(
      'Do not make active look identical to hover; selected state must remain visible.',
      '액티브와 호버를 똑같이 만들면 무엇이 선택됐는지 보이지 않습니다.',
      'アクティブとホバーを同じ見た目にすると、何が選択されているか分かりません。',
    ),
    semanticRoles: ['interaction-feedback', 'selection-indicator'],
    relatedStateIds: [],
    example: '.tab.is-active { border-color: currentColor; }',
  },
  {
    id: 'disabled',
    category: 'states',
    name: t('Disabled', '비활성', '無効'),
    aliases: ['disabled state', 'inactive', 'grayed out', '비활성 상태', '사용 불가', '無効状態'],
    plain: t(
      'A control that exists on the screen but cannot be used right now.',
      '화면에는 있지만 지금은 사용할 수 없는 컨트롤 상태입니다.',
      '画面にはあるが現在は使えないコントロールの状態です。',
    ),
    useWhen: t(
      'Submit buttons before required fields are filled, unavailable plans, and pending actions.',
      '필수 입력 전 제출 버튼, 선택 불가 요금제, 처리 중인 액션에서 씁니다.',
      '必須入力前の送信ボタン、利用不可プラン、処理中アクションで使います。',
    ),
    avoidWhen: t(
      'If the reason is not obvious, place a short hint near the disabled control.',
      '왜 비활성인지 분명하지 않다면 바로 옆에 짧은 이유를 붙이세요.',
      '理由が明確でない場合は、近くに短い説明を置きます。',
    ),
    semanticRoles: ['availability-indicator', 'affordance'],
    relatedStateIds: ['pristine', 'read-only', 'permission-denied'],
    example: '<button disabled>Save</button>',
  },
  {
    id: 'dropdown-select',
    category: 'controls',
    name: t('Dropdown / select', '드롭다운 / 셀렉트', 'ドロップダウン / セレクト'),
    aliases: ['select menu', 'combobox', 'picker', '셀렉트 박스', '선택 메뉴', 'プルダウン', '選択メニュー'],
    plain: t(
      'A compact control that opens a list of choices.',
      '선택지를 접어 두었다가 클릭하면 목록을 펼치는 컨트롤입니다.',
      '選択肢を折りたたみ、クリックで一覧を開くコントロールです。',
    ),
    useWhen: t(
      'Language, sorting, country, timeframe, plan, and category selection.',
      '언어, 정렬, 국가, 시간대, 요금제, 카테고리 선택에 씁니다.',
      '言語、並び替え、国、時間軸、プラン、カテゴリ選択で使います。',
    ),
    avoidWhen: t(
      'For only two choices, use a toggle or segmented control instead.',
      '선택지가 둘뿐이면 토글이나 세그먼트 컨트롤이 더 빠릅니다.',
      '選択肢が2つだけなら、トグルやセグメントの方が速いです。',
    ),
    semanticRoles: ['single-select', 'form-input'],
    relatedStateIds: [],
    example: '<select><option>Newest</option></select>',
  },
  {
    id: 'checkbox',
    category: 'controls',
    name: t('Checkbox', '체크박스', 'チェックボックス'),
    aliases: ['check box', 'tick box', 'multi-select', '체크 상자', '복수 선택', 'チェック欄', '複数選択'],
    plain: t(
      'A yes/no box, often allowing multiple selections in the same group.',
      '예/아니오를 표시하는 상자로, 같은 그룹에서 여러 개를 고를 수 있습니다.',
      'はい/いいえを示す箱で、同じグループ内で複数選択できます。',
    ),
    useWhen: t(
      'Agreements, filters, optional features, and bulk item selection.',
      '동의 항목, 필터, 선택 기능, 여러 항목 선택에 씁니다.',
      '同意、フィルタ、任意機能、複数項目選択で使います。',
    ),
    avoidWhen: t(
      'Do not use checkboxes when exactly one option must be selected.',
      '반드시 하나만 골라야 한다면 체크박스 대신 라디오를 쓰세요.',
      '必ず1つだけ選ぶ場合はチェックボックスではなくラジオを使います。',
    ),
    semanticRoles: ['multi-select', 'form-input'],
    relatedStateIds: [],
    example: '<input type="checkbox" checked />',
  },
  {
    id: 'radio-button',
    category: 'controls',
    name: t('Radio button', '라디오 버튼', 'ラジオボタン'),
    aliases: ['radio group', 'option button', 'single choice', '라디오 그룹', '단일 선택', 'ラジオグループ', '単一選択'],
    plain: t(
      'A set of choices where only one option can be selected.',
      '여러 선택지 중 하나만 고르는 원형 선택 컨트롤입니다.',
      '複数の選択肢から1つだけ選ぶ丸いコントロールです。',
    ),
    useWhen: t(
      'Billing periods, delivery methods, visibility modes, and survey answers.',
      '결제 주기, 배송 방식, 공개 범위, 설문 답변에 씁니다.',
      '請求周期、配送方法、公開範囲、アンケート回答で使います。',
    ),
    avoidWhen: t(
      'Do not hide every option inside a dropdown when comparison matters.',
      '서로 비교해야 하는 선택지는 드롭다운 안에 숨기지 않는 편이 좋습니다.',
      '比較が重要な選択肢はドロップダウンに隠さない方が良いです。',
    ),
    semanticRoles: ['single-select', 'form-input'],
    relatedStateIds: [],
    example: '<input type="radio" name="billing" />',
  },
  {
    id: 'toggle-switch',
    category: 'controls',
    name: t('Toggle / switch', '토글 / 스위치', 'トグル / スイッチ'),
    aliases: ['on/off switch', 'toggle button', '온오프 스위치', '켜기 끄기', 'オンオフスイッチ', '切り替え'],
    plain: t(
      'An immediate on/off control, like a physical switch.',
      '물리 스위치처럼 즉시 켜고 끄는 컨트롤입니다.',
      '物理スイッチのように即時オン/オフするコントロールです。',
    ),
    useWhen: t(
      'Dark mode, notifications, reduced motion, and feature enablement.',
      '다크 모드, 알림, 움직임 줄이기, 기능 활성화에 씁니다.',
      'ダークモード、通知、動きを減らす、機能有効化で使います。',
    ),
    avoidWhen: t(
      'If the action needs review before saving, use a checkbox plus a save button.',
      '저장하기 전에 확인이 필요하면 토글보다 체크박스와 저장 버튼이 낫습니다.',
      '保存前に確認が必要なら、トグルよりチェックボックスと保存ボタンが適切です。',
    ),
    semanticRoles: ['binary-toggle', 'form-input'],
    relatedStateIds: [],
    example: '<button role="switch" aria-checked="true">On</button>',
  },
  {
    id: 'slider',
    category: 'controls',
    name: t('Slider', '슬라이더', 'スライダー'),
    aliases: ['range slider', 'range input', '범위 슬라이더', '범위 입력', 'レンジスライダー', '範囲入力'],
    plain: t(
      'A control for choosing a number along a continuous range.',
      '이어진 범위에서 숫자 값을 고르는 컨트롤입니다.',
      '連続した範囲から数値を選ぶコントロールです。',
    ),
    useWhen: t(
      'Volume, brightness, intensity, price range, and animation duration.',
      '볼륨, 밝기, 강도, 가격 범위, 애니메이션 지속 시간에 씁니다.',
      '音量、明るさ、強度、価格範囲、アニメーション時間で使います。',
    ),
    avoidWhen: t(
      'When exact values matter, pair it with a numeric input.',
      '정확한 숫자가 중요하면 숫자 입력창을 함께 두세요.',
      '正確な値が重要なら、数値入力と組み合わせます。',
    ),
    semanticRoles: ['range-input', 'form-input'],
    relatedStateIds: [],
    example: '<input type="range" min="0" max="100" />',
  },
  {
    id: 'tabs',
    category: 'navigation',
    name: t('Tabs', '탭', 'タブ'),
    aliases: ['tab bar', 'tabbed view', 'segmented tabs', '탭 바', '탭 메뉴', 'タブバー', 'タブメニュー'],
    plain: t(
      'A set of labels that switches between related panels in the same place.',
      '같은 자리에서 관련 패널을 바꿔 가며 보여주는 라벨 묶음입니다.',
      '同じ場所で関連パネルを切り替えるラベル群です。',
    ),
    useWhen: t(
      'Settings sections, dashboard views, account areas, and documentation examples.',
      '설정 섹션, 대시보드 보기, 계정 영역, 문서 예시에 씁니다.',
      '設定セクション、ダッシュボード表示、アカウント領域、ドキュメント例で使います。',
    ),
    avoidWhen: t(
      'Do not use tabs for unrelated pages that deserve separate navigation.',
      '서로 관련 없는 페이지를 탭에 억지로 넣으면 구조가 흐려집니다.',
      '関連の薄いページをタブに入れると構造が分かりづらくなります。',
    ),
    semanticRoles: ['view-switcher', 'navigation'],
    relatedStateIds: [],
    example: '<button role="tab" aria-selected="true">Overview</button>',
  },
  {
    id: 'breadcrumb',
    category: 'navigation',
    name: t('Breadcrumb', '브레드크럼', 'パンくずリスト'),
    aliases: ['breadcrumb trail', 'path navigation', '경로 표시', '이동 경로', 'パンくず', '階層ナビ'],
    plain: t(
      'A small path showing where the current page sits in the site hierarchy.',
      '현재 페이지가 사이트 구조상 어디에 있는지 보여주는 작은 경로입니다.',
      '現在ページがサイト階層のどこにあるかを示す小さな経路です。',
    ),
    useWhen: t(
      'Deep product pages, docs, admin consoles, and nested settings.',
      '깊은 상품 페이지, 문서, 관리자 콘솔, 중첩 설정 화면에 씁니다.',
      '深い商品ページ、ドキュメント、管理画面、階層設定で使います。',
    ),
    avoidWhen: t(
      'Do not replace the main navigation with breadcrumbs.',
      '브레드크럼은 보조 경로이지 메인 네비게이션 대체물이 아닙니다.',
      'パンくずは補助経路であり、メインナビの代替ではありません。',
    ),
    semanticRoles: ['location-indicator', 'navigation'],
    relatedStateIds: [],
    example: 'Home / Docs / Components / Button',
  },
  {
    id: 'pagination',
    category: 'navigation',
    name: t('Pagination', '페이지네이션', 'ページネーション'),
    aliases: ['pager', 'page navigation', 'page controls', '페이지 이동', '쪽 넘김', 'ページ送り', 'ページ移動'],
    plain: t(
      'Controls for moving through many results page by page.',
      '많은 결과를 페이지 단위로 넘겨 보는 이동 컨트롤입니다.',
      '多数の結果をページ単位で移動するコントロールです。',
    ),
    useWhen: t(
      'Search results, tables, article archives, and order history.',
      '검색 결과, 표, 글 목록, 주문 내역에 씁니다.',
      '検索結果、テーブル、記事アーカイブ、注文履歴で使います。',
    ),
    avoidWhen: t(
      'Infinite scroll is not always better when users need stable positions or URLs.',
      '위치나 URL이 그대로 유지돼야 한다면 무한 스크롤이 늘 낫지는 않습니다.',
      '位置やURLを保つ必要がある場合、無限スクロールが常に良いとは限りません。',
    ),
    semanticRoles: ['result-navigation', 'navigation'],
    relatedStateIds: ['loading-next-page', 'end-of-results'],
    example: '<nav aria-label="Pagination">1 2 3 Next</nav>',
  },
  {
    id: 'modal-dialog',
    category: 'feedback',
    name: t('Modal dialog', '모달', 'モーダル'),
    aliases: ['dialog', 'popup', 'overlay window', '대화 상자', '팝업 창', 'ダイアログ', 'ポップアップ'],
    plain: t(
      'A layer that appears above the page and temporarily blocks the underlying screen.',
      '페이지 위에 떠서 아래 화면을 잠시 가리는 레이어입니다.',
      'ページ上に重なり、背後の画面を一時的に覆って操作できなくするレイヤーです。',
    ),
    useWhen: t(
      'Confirmations, short forms, destructive actions, and focused editing.',
      '확인, 짧은 폼, 삭제 같은 위험 액션, 집중 편집에 씁니다.',
      '確認、短いフォーム、削除などの危険操作、集中編集で使います。',
    ),
    avoidWhen: t(
      'Do not put long workflows in a modal when a full page would be clearer.',
      '긴 절차를 모달 안에 넣으면 답답하므로 전체 페이지가 더 명확할 수 있습니다.',
      '長い手順をモーダルに入れるより、専用ページの方が明確な場合があります。',
    ),
    semanticRoles: ['overlay', 'focus-trap'],
    relatedStateIds: [],
    example: '<div role="dialog" aria-modal="true">Confirm delete?</div>',
  },
  {
    id: 'tooltip',
    category: 'feedback',
    name: t('Tooltip', '툴팁', 'ツールチップ'),
    aliases: ['hint', 'helper label', 'popover hint', '도움말', '말풍선', 'ヒント', '吹き出し'],
    plain: t(
      'A tiny helper label that appears near an icon or compact control.',
      '아이콘이나 작은 컨트롤 옆에 잠깐 뜨는 짧은 도움말입니다.',
      'アイコンや小さな操作部の近くに出る短い補足です。',
    ),
    useWhen: t(
      'Icon buttons, abbreviations, chart points, and dense toolbars.',
      '아이콘 버튼, 약어, 차트 포인트, 밀도 높은 툴바에 씁니다.',
      'アイコンボタン、略語、チャート点、密度の高いツールバーで使います。',
    ),
    avoidWhen: t(
      'Important instructions should be visible, not hidden inside a tooltip.',
      '중요한 안내는 툴팁에 숨기지 말고 화면에 그대로 보여 주세요.',
      '重要な案内はツールチップに隠さず、画面上に表示します。',
    ),
    semanticRoles: ['contextual-help', 'overlay'],
    relatedStateIds: [],
    example: '<button aria-label="Export">↧</button>',
  },
  {
    id: 'toast-snackbar',
    category: 'feedback',
    name: t('Toast / snackbar', '토스트 / 스낵바', 'トースト / スナックバー'),
    aliases: ['notification banner', 'flash message', 'transient alert', '알림 토스트', '잠깐 알림', '通知バー', '一時通知'],
    plain: t(
      'A short message that appears after an action, then disappears.',
      '어떤 동작을 한 뒤 잠깐 나타났다가 사라지는 짧은 메시지입니다.',
      '操作後に一時表示され、消える短いメッセージです。',
    ),
    useWhen: t(
      'Saved, copied, uploaded, failed, or queued status messages.',
      '저장됨, 복사됨, 업로드됨, 실패함, 대기열 추가 같은 상태 안내에 씁니다.',
      '保存、コピー、アップロード、失敗、キュー追加などの状態通知で使います。',
    ),
    avoidWhen: t(
      'Do not use only a disappearing toast for critical errors.',
      '중대한 오류를 사라지는 토스트 하나로만 알리면 놓치기 쉽습니다.',
      '重大エラーを消えるトーストだけで伝えると見逃されます。',
    ),
    semanticRoles: ['status-feedback', 'transient-notification'],
    relatedStateIds: ['form-success', 'fetch-failed', 'console-success'],
    example: 'Saved. Undo',
  },
  {
    id: 'skeleton-loading',
    category: 'feedback',
    name: t('Skeleton loading', '스켈레톤 로딩', 'スケルトンローディング'),
    aliases: ['skeleton screen', 'placeholder loader', 'shimmer', '스켈레톤 화면', '로딩 자리표시', 'スケルトン画面', 'プレースホルダー'],
    plain: t(
      'A temporary gray layout that shows the shape of content while data is loading.',
      '데이터를 기다리는 동안 콘텐츠 형태를 회색 블록으로 먼저 보여주는 로딩 상태입니다.',
      'データ読込中にコンテンツ形状を灰色ブロックで先に示す状態です。',
    ),
    useWhen: t(
      'Feeds, tables, cards, dashboards, and detail pages with network data.',
      '피드, 표, 카드, 대시보드, 네트워크 데이터를 기다리는 상세 페이지에 씁니다.',
      'フィード、表、カード、ダッシュボード、通信待ちの詳細ページで使います。',
    ),
    avoidWhen: t(
      'If loading is almost instant, a skeleton may add unnecessary visual noise.',
      '로딩이 거의 즉시 끝난다면 스켈레톤이 오히려 시각적 소음을 만들 수 있습니다.',
      '読込がほぼ即時なら、スケルトンは余計な視覚ノイズになる場合があります。',
    ),
    semanticRoles: ['loading-indicator', 'placeholder'],
    relatedStateIds: ['initial-loading', 'loading-next-page'],
    example: '.skeleton { background: #e5e7eb; }',
  },
  {
    id: 'card',
    category: 'layout',
    name: t('Card', '카드', 'カード'),
    aliases: ['content card', 'tile', 'panel', '콘텐츠 카드', '타일', 'タイル', 'コンテンツカード'],
    plain: t(
      'A contained block that groups one item, topic, product, or summary.',
      '항목 하나, 주제, 상품, 요약을 한데 묶는 독립 블록입니다.',
      '1つの項目、話題、商品、要約をまとめる独立ブロックです。',
    ),
    useWhen: t(
      'Style tiles, product summaries, pricing options, articles, and dashboard widgets.',
      '스타일 타일, 상품 요약, 요금제, 글 목록, 대시보드 위젯에 씁니다.',
      'スタイルタイル、商品要約、料金、記事、ダッシュボードウィジェットで使います。',
    ),
    avoidWhen: t(
      'Do not place every page section inside a card; reserve cards for repeated items.',
      '모든 페이지 섹션을 카드로 감싸기보다 반복 항목에 주로 써야 합니다.',
      'ページ区画を全部カードにせず、反復項目に主に使います。',
    ),
    semanticRoles: ['content-grouping', 'container'],
    relatedStateIds: [],
    example: '<article className="card">...</article>',
  },
  {
    id: 'badge-chip',
    category: 'layout',
    name: t('Badge / chip', '배지 / 칩', 'バッジ / チップ'),
    aliases: ['tag', 'pill', 'label', 'status badge', '태그', '상태 배지', 'タグ', 'ラベル'],
    plain: t(
      'A small label that marks status, category, count, or a selected filter.',
      '상태, 카테고리, 개수, 선택한 필터를 작게 표시하는 라벨입니다.',
      '状態、カテゴリ、件数、選択済みフィルタを小さく示すラベルです。',
    ),
    useWhen: t(
      'New, beta, sale, active filters, tags, and unread counts.',
      'New, beta, sale, 활성 필터, 태그, 읽지 않은 개수에 씁니다.',
      'New、beta、sale、有効フィルタ、タグ、未読数で使います。',
    ),
    avoidWhen: t(
      'Too many badges reduce scanability; keep them short and meaningful.',
      '배지가 너무 많으면 훑어보기 어려우니 짧고 의미 있게 두세요.',
      'バッジが多すぎると読みにくいため、短く意味あるものに絞ります。',
    ),
    semanticRoles: ['status-indicator', 'metadata-label'],
    relatedStateIds: [],
    example: '<span className="badge">Beta</span>',
  },
  {
    id: 'accordion',
    category: 'layout',
    name: t('Accordion', '아코디언', 'アコーディオン'),
    aliases: ['expander', 'collapsible', 'disclosure', '접이식 패널', '펼침 목록', '折りたたみ', '開閉パネル'],
    plain: t(
      'A stack of expandable rows that show one chunk of hidden content at a time.',
      '접힌 행을 한 번에 하나씩 펼쳐 숨은 내용을 보여주는 세로형 패턴입니다.',
      '折りたたんだ行を一度に一つずつ開き、隠れた内容を見せる縦型パターンです。',
    ),
    useWhen: t(
      'FAQs, settings groups, mobile filters, and dense documentation.',
      'FAQ, 설정 그룹, 모바일 필터, 밀도 높은 문서에 씁니다.',
      'FAQ、設定グループ、モバイルフィルタ、密度の高い文書で使います。',
    ),
    avoidWhen: t(
      'Do not hide content people must compare side by side.',
      '서로 비교해야 하는 내용은 아코디언에 숨기지 않는 편이 좋습니다.',
      '並べて比較すべき内容はアコーディオンに隠さない方が良いです。',
    ),
    semanticRoles: ['progressive-disclosure', 'content-grouping'],
    relatedStateIds: [],
    example: '<details><summary>Question</summary>Answer</details>',
  },
  {
    id: 'empty-state',
    category: 'layout',
    name: t('Empty state', '빈 상태', '空状態'),
    aliases: ['blank state', 'zero state', 'no results', '빈 화면', '결과 없음', '空の画面', 'ゼロ状態'],
    plain: t(
      'The screen shown when there is no data, no result, or nothing selected yet.',
      '데이터나 검색 결과가 없거나 아직 아무것도 고르지 않았을 때 보이는 화면입니다.',
      'データなし、検索結果なし、未選択時に表示する画面です。',
    ),
    useWhen: t(
      'Dashboards before setup, empty tables, failed searches, and first-time product use.',
      '초기 대시보드, 빈 표, 검색 실패, 첫 사용 화면에 씁니다.',
      '初期ダッシュボード、空テーブル、検索失敗、初回利用画面で使います。',
    ),
    avoidWhen: t(
      'A good empty state explains the next useful action, not just "nothing here".',
      '좋은 빈 상태는 “없음”만 말하지 않고 다음 행동을 알려줍니다.',
      '良い空状態は「何もない」だけでなく次の行動を示します。',
    ),
    semanticRoles: ['empty-content-guidance', 'onboarding-affordance'],
    relatedStateIds: ['initial-empty', 'filtered-empty'],
    example: 'No results. Try removing one filter.',
  },
];
