import { t } from './localization';
import type {
  DesignConcern,
  DesignPrinciple,
  DesignPrincipleCategory,
  DesignPrincipleCategoryDef,
  DesignPrincipleReference,
  UxPhase,
  UxSurface,
} from './types';

export const designPrincipleCategories: DesignPrincipleCategoryDef[] = [
  {
    id: 'intent-iteration',
    label: t('Intent & iteration', '의도와 반복', '意図と反復'),
    description: t(
      'Start from a real task, expose assumptions early, and raise fidelity only as decisions become stable.',
      '실제 과업에서 시작해 가정을 일찍 드러내고, 결정이 안정될수록 완성도를 높입니다.',
      '実際のタスクから始め、前提を早く表面化し、判断が固まるほど精度を上げます。',
    ),
  },
  {
    id: 'hierarchy-semantics',
    label: t('Hierarchy & semantics', '위계와 의미 구조', '階層と意味構造'),
    description: t(
      'Align visual emphasis, labels, relationships, and layers with the meaning users and assistive technology receive.',
      '시각적 강조·라벨·관계·레이어를 사용자와 보조 기술이 받는 의미 구조에 맞춥니다.',
      '視覚的強調、ラベル、関係、レイヤーを、利用者と支援技術が受け取る意味構造に揃えます。',
    ),
  },
  {
    id: 'adaptation-density',
    label: t('Adaptation & density', '적응형 배치와 밀도', '適応と密度'),
    description: t(
      'Make relationships survive container changes, zoom, content expansion, input modes, and different task frequencies.',
      '컨테이너 변화·확대·콘텐츠 확장·입력 방식·사용 빈도가 달라도 관계가 유지되게 합니다.',
      'コンテナ変化、拡大、内容伸長、入力方式、利用頻度が変わっても関係を保ちます。',
    ),
  },
  {
    id: 'typography-localization',
    label: t('Typography & localization', '타이포그래피와 현지화', '文字設計とローカライズ'),
    description: t(
      'Coordinate type, measure, line breaking, script direction, fallback, and locale formats as one reading system.',
      '글자·행 길이·줄바꿈·문자 방향·대체 글꼴·지역 형식을 하나의 읽기 체계로 조율합니다.',
      '文字、行長、改行、書字方向、代替書体、地域形式を一つの読書体系として調整します。',
    ),
  },
  {
    id: 'tokens-color-themes',
    label: t('Tokens, color & themes', '토큰·색·테마', 'トークン・色・テーマ'),
    description: t(
      'Express design decisions through semantic tokens that preserve role and contrast across modes and platforms.',
      '의미 토큰으로 설계 결정을 표현하고 모드와 플랫폼이 바뀌어도 역할과 대비를 지킵니다.',
      '意味トークンで設計判断を表し、モードやプラットフォームが変わっても役割と対比を保ちます。',
    ),
  },
  {
    id: 'interaction-accessibility',
    label: t('Interaction & accessibility', '상호작용과 접근성', '操作とアクセシビリティ'),
    description: t(
      'Keep controls operable and state legible across keyboard, touch, pointer, speech, and assistive technology.',
      '키보드·터치·포인터·음성·보조 기술에서도 컨트롤을 조작하고 상태를 이해할 수 있게 합니다.',
      'キーボード、タッチ、ポインター、音声、支援技術でも操作と状態理解を保ちます。',
    ),
  },
  {
    id: 'states-feedback-recovery',
    label: t('States, feedback & recovery', '상태·피드백·복구', '状態・フィードバック・回復'),
    description: t(
      'Design the full state matrix, communicate change truthfully, and give users a safe route back.',
      '전체 상태 행렬을 설계하고 변화를 정확히 알리며 사용자가 안전하게 돌아갈 길을 제공합니다.',
      '状態全体を設計し、変化を正確に伝え、安全に戻れる経路を用意します。',
    ),
  },
];

const sourceReferences = {
  vibeCodedAudit: {
    title: 'Does your AI-built app look vibe-coded?',
    publisher: 'The Crit',
    url: 'https://thecrit.co/resources/does-your-ai-built-app-look-vibe-coded',
  },
  primerNavigation: {
    title: 'Navigation UI patterns',
    publisher: 'Primer',
    url: 'https://primer.style/product/ui-patterns/navigation/',
  },
  linearRefresh: {
    title: 'Behind the latest design refresh',
    publisher: 'Linear',
    url: 'https://linear.app/now/behind-the-latest-design-refresh',
  },
} satisfies Record<string, DesignPrincipleReference>;

function principle(
  id: string,
  name: ReturnType<typeof t>,
  aliases: string[],
  category: DesignPrincipleCategory,
  summary: ReturnType<typeof t>,
  designQuestion: ReturnType<typeof t>,
  placement: ReturnType<typeof t>,
  apply: ReturnType<typeof t>,
  verify: ReturnType<typeof t>,
  caution: ReturnType<typeof t>,
  concernTags: DesignConcern[],
  surfaceTags: UxSurface[],
  phaseTags: UxPhase[],
  relatedDesignPrincipleIds: string[],
  relatedUxPrincipleIds: string[],
  references: DesignPrincipleReference[] = [],
): DesignPrinciple {
  return {
    id,
    name,
    aliases,
    category,
    summary,
    designQuestion,
    placement: [placement],
    apply: [apply],
    verify: [verify],
    caution,
    concernTags,
    surfaceTags,
    phaseTags,
    relatedDesignPrincipleIds,
    relatedUxPrincipleIds,
    references,
  };
}

export const designPrinciples: DesignPrinciple[] = [
  principle(
    'core-task-first',
    t('Let the task shape the shell', '핵심 과업이 틀을 정하게 하기', '中心タスクから枠組みを決める'),
    ['task-first composition', 'feature-first design'],
    'intent-iteration',
    t(
      'Start from the smallest complete user task; let navigation and page regions emerge around it.',
      '사용자가 끝낼 수 있는 가장 작은 핵심 과업에서 시작하고, 그 주변에 내비게이션과 화면 영역을 만듭니다.',
      '完了できる最小の中心タスクから始め、その周囲にナビゲーションと画面領域を組みます。',
    ),
    t('What must work if every decorative or secondary region disappears?', '장식과 보조 영역을 모두 지워도 반드시 작동해야 하는 것은 무엇인가요?', '装飾や補助領域をすべて消しても、必ず機能すべきものは何ですか。'),
    t('Place the primary input, object, and outcome in one uninterrupted path before adding global chrome.', '전역 장식을 더하기 전에 핵심 입력·대상·결과를 끊김 없는 한 경로에 배치하세요.', '全体の装飾を足す前に、主要な入力・対象・結果を途切れない一つの経路に置きます。'),
    t('Prototype that path with real content, then add only the navigation needed to enter, leave, or switch context.', '실제 콘텐츠로 그 경로를 먼저 만들고, 진입·이탈·맥락 전환에 필요한 내비게이션만 추가하세요.', '実データでその経路を先に作り、開始・離脱・文脈切替に必要なナビゲーションだけを加えます。'),
    t('A first-time user can complete the primary task without scanning unrelated regions.', '처음 온 사용자가 무관한 영역을 훑지 않고 핵심 과업을 완료할 수 있는지 확인하세요.', '初回利用者が無関係な領域を探さず中心タスクを完了できるか確認します。'),
    t('Do not hide safety, price, status, or consequences in the name of a cleaner task path.', '과업 경로를 깔끔하게 만든다는 이유로 안전·가격·상태·결과를 숨기지 마세요.', '経路を簡潔にするために、安全、価格、状態、結果を隠してはいけません。'),
    ['focus', 'restraint', 'resilience'],
    ['global', 'landing-page'],
    ['discover', 'structure'],
    ['task-sized-composition', 'attention-budget'],
    ['cognitive-load', 'teslers-law'],
  ),
  principle(
    'opening-earns-its-frame',
    t('Make the opening specific to this product', '오프닝을 이 제품만의 것으로 만들기', 'オープニングをこの製品固有のものにする'),
    ['furniture check', 'centerpiece composition', 'anti-template opening'],
    'intent-iteration',
    t(
      'Build the first screen around the product’s single most important object, action, or feeling, and make every region that owns real space demonstrate it.',
      '첫 화면을 이 제품에서 가장 중요한 대상·행동·감정 하나를 중심으로 구성하고, 넓은 자리를 차지하는 영역마다 그것을 보여주게 만듭니다.',
      '最初の画面を、この製品で最も重要な対象・行動・感情ひとつを中心に構成し、広い面積を占める領域それぞれにそれを示させます。',
    ),
    t('Could this opening be pasted onto a competitor by swapping the logo and one noun?', '로고와 명사 하나만 바꿔서 경쟁 제품에 그대로 옮길 수 있는 오프닝인가요?', 'ロゴと名詞ひとつを替えるだけで競合製品に貼れるオープニングになっていませんか。'),
    t('Give the frame to what the product actually does; keep copy and controls subordinate to it rather than standing beside it as an equal column.', '제품이 실제로 하는 일에 화면을 내주고, 카피와 컨트롤은 그 옆에 대등한 컬럼으로 세우지 말고 아래에 두세요.', '製品が実際に行うことに画面を与え、コピーや操作は対等な列として横に並べず従属させます。'),
    t('Name the centerpiece, then write down three structurally different openings — organizing device, what owns more than half the frame, where the eye lands first — with at least one carrying no running-text column, and compose the one the content justifies.', '중심을 먼저 정한 뒤 구조가 다른 오프닝 세 가지를 적으세요. 각각 구성 장치, 화면 절반 이상을 차지하는 요소, 시선이 처음 닿는 지점을 쓰고, 그중 하나는 본문 컬럼 없이 구성합니다. 그다음 콘텐츠가 뒷받침하는 안을 만드세요.', '中心を決めたうえで、構造の異なるオープニングを三つ書き出します。それぞれ構成の軸、画面の半分以上を占める要素、視線が最初に落ちる場所を記し、うち一つは本文の列を持たない形にします。そのうえで内容が支持できる案を作ります。'),
    t('Moving the opening onto a different product makes it nonsensical: the visual shows this product’s real input and output with realistic domain content, and the opening carries at most a headline, one short line, and one action.', '오프닝을 다른 제품으로 옮기면 말이 되지 않는지 확인하세요. 비주얼이 이 제품의 실제 입력과 결과를 현실적인 도메인 데이터로 보여주고, 오프닝 카피는 헤드라인 하나, 짧은 한 줄, 액션 하나를 넘지 않아야 합니다.', 'オープニングを別の製品に移すと意味をなさないか確認します。ビジュアルがこの製品の実際の入力と結果を現実的なデータで示し、コピーは見出し一つ、短い一行、アクション一つを超えないことを確かめます。'),
    t('Distinctiveness never outranks legibility, accessible contrast, or truthful claims; an original composition still owes the visitor an obvious first action.', '독창성이 가독성·접근 가능한 대비·사실에 맞는 주장보다 앞설 수는 없습니다. 새로운 구성이어도 방문자에게 첫 행동은 분명히 보여야 합니다.', '独自性が可読性、アクセシブルな対比、正確な主張に優先することはありません。新しい構成でも、訪問者に最初の行動は明確に示す必要があります。'),
    ['focus', 'balance', 'restraint'],
    ['landing-page', 'onboarding', 'content'],
    ['discover', 'structure', 'validation'],
    ['core-task-first', 'attention-budget', 'resilient-imagery'],
    ['aesthetic-usability-effect', 'selective-attention', 'von-restorff-effect'],
    [sourceReferences.vibeCodedAudit],
  ),
  principle(
    'evidence-near-claim',
    t('Put evidence beside the claim', '주장 곁에 근거 두기', '主張のそばに根拠を置く'),
    ['proof near promise', 'claim evidence', 'credible product proof'],
    'intent-iteration',
    t(
      'Pair important promises with nearby, inspectable evidence so visual polish does not have to carry credibility by itself.',
      '중요한 약속 곁에 직접 확인할 수 있는 근거를 두어 시각적 완성도가 혼자 신뢰를 떠맡지 않게 합니다.',
      '重要な約束の近くに確認できる根拠を置き、見た目の完成度だけに信頼を担わせないようにします。',
    ),
    t('What can a person inspect here to decide whether this promise is true for their situation?', '이 약속이 자신의 상황에도 사실인지 판단하려면 여기서 무엇을 직접 확인할 수 있나요?', 'この約束が自分の状況でも正しいか判断するために、ここで何を確認できますか。'),
    t('Place the strongest relevant artifact, example, method, source, or constraint in the same scan group as the claim it supports.', '가장 관련 있는 결과물·예시·방법·출처·제약을 그것이 뒷받침하는 주장과 같은 훑기 영역에 배치하세요.', '最も関連する成果物、例、方法、出典、制約を、それが支える主張と同じ走査範囲に置きます。'),
    t('Inventory promises, metrics, comparisons, and superlatives; connect each to real evidence, qualify its boundary, or remove it when no support exists.', '약속·수치·비교·최상급 표현을 목록화하고, 각각을 실제 근거와 연결해 한계를 밝히거나 뒷받침할 수 없으면 제거하세요.', '約束、数値、比較、最上級表現を棚卸しし、それぞれを実際の根拠に結び、範囲を示すか、支えられなければ削除します。'),
    t('Every material claim has adjacent evidence or an explicit qualification; links resolve, examples are real, limits stay visible, and no metric, customer quote, or outcome was invented.', '중요한 주장마다 가까운 근거 또는 명시적인 한계 설명이 있고, 링크와 예시가 실제로 열리며, 제약이 보이고, 수치·고객 인용·성과를 만들어내지 않았는지 확인하세요.', '重要な主張ごとに近接する根拠または明示的な限定があり、リンクと例が実在し、制約が見え、数値、顧客の声、成果を捏造していないか確認します。'),
    t('Evidence should answer the claim, not merely add logos, decorative dashboards, or unrelated numbers that imitate authority.', '근거는 주장을 실제로 설명해야 합니다. 권위 있어 보이기 위한 로고·장식용 대시보드·무관한 수치를 덧붙이지 마세요.', '根拠は主張に答える必要があります。権威を装うロゴ、装飾用ダッシュボード、無関係な数値を足してはいけません。'),
    ['focus', 'scanability', 'resilience'],
    ['landing-page', 'onboarding', 'content'],
    ['content', 'validation'],
    ['opening-earns-its-frame', 'explicit-labels-and-semantics', 'complete-state-model'],
    ['aesthetic-usability-effect', 'mental-model'],
    [sourceReferences.vibeCodedAudit],
  ),
  principle(
    'fidelity-follows-certainty',
    t('Increase fidelity with certainty', '확신에 맞춰 완성도 높이기', '確信に合わせて精度を上げる'),
    ['progressive fidelity', 'detail follows certainty'],
    'intent-iteration',
    t(
      'Resolve flow and hierarchy cheaply before polishing type, color, depth, and illustration.',
      '타이포·색·깊이·삽화를 다듬기 전에 흐름과 위계를 저비용으로 확정합니다.',
      '文字、色、奥行き、図版を磨く前に、フローと階層を低コストで固めます。',
    ),
    t('Which visual decisions are hiding an unresolved content or flow decision?', '어떤 시각적 결정이 아직 풀지 못한 콘텐츠나 흐름 문제를 가리고 있나요?', 'どの視覚的判断が、未解決の内容やフローの問題を隠していますか。'),
    t('Keep uncertain regions schematic and put finished detail only where the task and content are stable.', '불확실한 영역은 개략적으로 두고, 과업과 콘텐츠가 안정된 곳에만 완성된 디테일을 배치하세요.', '不確かな領域は概略のままにし、タスクと内容が安定した場所だけを仕上げます。'),
    t('Review in passes—structure, hierarchy, spacing, type, color, depth, then finish—and keep a reversible before/after comparison while decisions are still moving.', '구조→위계→간격→글자→색→깊이→마감 순서로 나누어 검토하고, 결정이 바뀌는 동안에는 이전·이후 화면을 되돌려 비교할 수 있게 유지하세요.', '構造、階層、余白、文字、色、奥行き、仕上げの順に確認し、判断が動く間は前後を戻して比較できる状態を保ちます。'),
    t('Side-by-side views still show the intended order without decoration, and stress views—long text, dense data, empty and error states, narrow widths—do not reverse the decision.', '이전·이후 화면을 나란히 놓고 장식을 제거해도 읽는 순서가 분명하며, 긴 문구·고밀도 데이터·빈 상태·오류·좁은 화면에서도 그 결정이 무너지지 않는지 확인하세요.', '前後を並べ、装飾を外しても読順が明確で、長文、高密度データ、空、エラー、狭幅でも判断が崩れないか確認します。'),
    t('Low fidelity is not permission to omit error, empty, loading, or responsive behavior.', '낮은 완성도는 오류·빈 상태·로딩·반응형 동작을 생략해도 된다는 뜻이 아닙니다.', '低精度だからといって、エラー、空、読込、レスポンシブ挙動を省略してよいわけではありません。'),
    ['focus', 'consistency', 'restraint'],
    ['global'],
    ['discover', 'structure', 'validation'],
    ['core-task-first', 'bounded-choice-system'],
    ['cognitive-load', 'mental-model'],
    [sourceReferences.linearRefresh],
  ),
  principle(
    'bounded-choice-system',
    t('Use semantic tokens and modes', '의미 토큰과 모드 사용하기', '意味トークンとモードを使う'),
    ['semantic tokens', 'design token aliases', 'theme modes'],
    'tokens-color-themes',
    t(
      'Connect base values to semantic roles and component states so themes and platforms preserve the same decisions.',
      '기초 값을 의미 역할과 컴포넌트 상태에 연결해 테마와 플랫폼이 달라도 같은 결정을 유지합니다.',
      '基礎値を意味役割とコンポーネント状態につなぎ、テーマや基盤が変わっても同じ判断を保ちます。',
    ),
    t('Which decision belongs to a base token, a semantic alias, a component state, or a documented exception?', '어떤 결정이 기초 토큰·의미 별칭·컴포넌트 상태·문서화된 예외에 속하나요?', 'どの判断が基礎トークン、意味別名、状態、文書化した例外に属しますか。'),
    t('Keep semantic tokens beside the roles they control and make theme, density, and accessibility modes explicit.', '의미 토큰을 제어 대상 역할 가까이에 두고 테마·밀도·접근성 모드를 명시하세요.', '意味トークンを対象役割の近くに置き、テーマ、密度、アクセシビリティモードを明示します。'),
    t('Map base → semantic → component aliases; cover default, hover, focus, active, disabled, error, and high-contrast modes before adding exceptions.', '기초→의미→컴포넌트 별칭을 연결하고 예외를 늘리기 전에 기본·호버·포커스·활성·비활성·오류·고대비 모드를 채우세요.', '基礎→意味→コンポーネント別名を結び、例外追加前に既定、hover、focus、active、disabled、error、高対比を揃えます。'),
    t('Design and code resolve the same token graph across light, dark, density, contrast, and brand modes without unresolved aliases.', '디자인과 코드가 밝음·어두움·밀도·대비·브랜드 모드에서 같은 토큰 그래프를 해석하고 미해결 별칭이 없는지 확인하세요.', 'デザインとコードが明暗、密度、対比、ブランドモードで同じトークングラフを解決し、未解決別名がないか確認します。'),
    t('Tokens centralize intent; they must not hide unclear roles, inaccessible pairings, or unexplained one-off values.', '토큰은 의도를 모으는 도구이며 불명확한 역할·접근 불가능한 조합·이유 없는 예외 값을 숨겨서는 안 됩니다.', 'トークンは意図を集約するもので、曖昧な役割、非アクセシブルな組合せ、理由のない例外を隠してはいけません。'),
    ['consistency', 'resilience', 'accessibility'],
    ['global'],
    ['structure', 'validation'],
    ['fidelity-follows-certainty', 'relational-spacing', 'deliberate-type-scale'],
    ['choice-overload', 'law-of-similarity'],
  ),
  principle(
    'attention-budget',
    t('Budget attention by importance', '중요도에 따라 주의 배분하기', '重要度に応じて注意を配る'),
    ['visual hierarchy', 'attention hierarchy'],
    'hierarchy-semantics',
    t(
      'Treat prominence as a limited budget: a primary item can lead only when supporting items are quieter.',
      '강조를 한정된 예산처럼 다루고, 핵심이 앞서도록 보조 요소를 차분하게 만듭니다.',
      '強調を限られた予算として扱い、主要要素が先に立つよう補助要素を静かにします。',
    ),
    t('If everything asks to be noticed, what is the user supposed to notice first?', '모든 요소가 주목을 요구한다면 사용자는 무엇을 먼저 봐야 하나요?', 'すべてが注目を求めるなら、最初に見るべきものは何ですか。'),
    t('Place the primary action or information on the strongest reading path; move context beside or after it.', '핵심 행동이나 정보를 가장 강한 읽기 경로에 두고, 맥락 정보는 옆이나 뒤에 배치하세요.', '主要な行動や情報を最も強い読書経路に置き、文脈は横か後に配置します。'),
    t('Rank every visible region as primary, supporting, or contextual and assign contrast accordingly; once navigation has established location, let it recede behind the work area.', '보이는 모든 영역을 핵심·보조·맥락으로 등급화해 대비를 부여하고, 내비게이션이 현재 위치를 알려준 뒤에는 작업 영역보다 차분하게 물러나게 하세요.', '見える領域を主要・補助・文脈に分類して対比を割り当て、ナビゲーションが現在地を示した後は作業領域より静かに退かせます。'),
    t('A five-second glance and grayscale view produce the same top three reading targets, with the work area leading after orientation and repeated chrome never competing with the current task.', '5초 훑어보기와 회색조 화면에서 상위 세 읽기 대상이 같고, 위치를 파악한 뒤에는 작업 영역이 앞서며 반복되는 크롬이 현재 과업과 경쟁하지 않는지 확인하세요.', '5秒の一瞥とグレースケールで上位三つの対象が一致し、現在地を把握した後は作業領域が先に立ち、反復するクロームが現在のタスクと競合しないか確認します。'),
    t('Do not use low contrast to demote information that remains essential or actionable.', '여전히 필수이거나 조작 가능한 정보를 낮은 대비로 약화하지 마세요.', '必須または操作可能な情報を、低コントラストで弱めてはいけません。'),
    ['focus', 'scanability', 'balance'],
    ['global', 'landing-page'],
    ['structure', 'validation'],
    ['contrast-before-scale', 'explicit-labels-and-semantics'],
    ['selective-attention', 'von-restorff-effect'],
    [sourceReferences.linearRefresh],
  ),
  principle(
    'contrast-before-scale',
    t('Use contrast before size', '크기보다 대비 먼저 쓰기', '大きさより先に対比を使う'),
    ['weight and contrast', 'de-emphasis'],
    'hierarchy-semantics',
    t(
      'Create levels with weight, color, and surrounding quiet before making every important item larger.',
      '중요한 것을 모두 키우기 전에 굵기·색·주변의 여백으로 위계를 만듭니다.',
      '重要なものをすべて大きくする前に、太さ、色、周囲の静けさで階層を作ります。',
    ),
    t('Can the hierarchy become clearer by quieting competitors instead of enlarging the leader?', '주요 요소를 키우기보다 경쟁 요소를 낮춰 위계를 더 분명히 할 수 있나요?', '主役を大きくするより、競合要素を静かにして階層を明確にできますか。'),
    t('Keep related text close in size, then differentiate role through weight, tone, and spacing.', '관련 텍스트의 크기는 가깝게 유지하고 굵기·톤·간격으로 역할을 구분하세요.', '関連テキストの大きさは近く保ち、太さ、色調、余白で役割を分けます。'),
    t('Reduce secondary emphasis one channel at a time and stop before readability or affordance drops.', '보조 강조를 한 채널씩 낮추고, 가독성이나 조작성이 떨어지기 전에 멈추세요.', '補助の強調を一要素ずつ下げ、可読性や操作性が落ちる前に止めます。'),
    t('Headings, values, labels, and actions remain distinguishable at 200% zoom and in grayscale.', '200% 확대와 회색조에서도 제목·값·라벨·행동을 구분할 수 있는지 확인하세요.', '200%拡大とグレースケールでも、見出し、値、ラベル、操作を区別できるか確認します。'),
    t('Muted text still needs accessible contrast; “secondary” must not mean unreadable.', '보조 텍스트도 접근 가능한 대비가 필요하며, “보조”가 “읽을 수 없음”을 뜻해서는 안 됩니다.', '補助テキストにも十分なコントラストが必要で、「補助」は「読めない」ではありません。'),
    ['focus', 'readability', 'accessibility'],
    ['global', 'landing-page'],
    ['structure', 'content', 'validation'],
    ['attention-budget', 'redundant-state-signals'],
    ['selective-attention', 'aesthetic-usability-effect'],
  ),
  principle(
    'explicit-labels-and-semantics',
    t('Make labels and relationships explicit', '라벨과 관계를 명시하기', 'ラベルと関係を明示する'),
    ['explicit labels', 'semantic relationships', 'name role value'],
    'hierarchy-semantics',
    t(
      'Pair clear visible language with programmatic names, roles, values, instructions, and relationships.',
      '명확한 보이는 문구를 프로그램상의 이름·역할·값·설명·관계와 함께 제공합니다.',
      '明確な表示文を、プログラム上の名前、役割、値、説明、関係と組み合わせます。',
    ),
    t('Can people identify what this is, what it controls, and what will happen without inferring meaning from position or styling?', '위치나 스타일에서 의미를 추측하지 않고 이것이 무엇이며 무엇을 제어하고 어떤 결과가 생기는지 식별할 수 있나요?', '位置や見た目から推測せず、これが何で、何を操作し、何が起きるか識別できますか。'),
    t('Place labels next to the value or control they identify; place instructions before the decision and errors beside the affected field.', '라벨은 식별 대상 값이나 컨트롤 옆에, 설명은 결정 전에, 오류는 해당 필드 옆에 배치하세요.', 'ラベルは対象値や操作の隣、説明は判断前、エラーは該当項目の隣に置きます。'),
    t('Use native semantics first, connect label-description-error relationships, and keep visible wording aligned with the accessible name.', '네이티브 의미 구조를 먼저 쓰고 라벨·설명·오류 관계를 연결하며 보이는 문구와 접근 가능한 이름을 맞추세요.', '標準の意味構造を先に使い、ラベル・説明・エラーを関連付け、表示文とアクセシブル名を揃えます。'),
    t('New users and assistive technology identify the same control, state, unit, consequence, and group relationship without guessing.', '새 사용자와 보조 기술이 같은 컨트롤·상태·단위·결과·그룹 관계를 추측 없이 식별하는지 확인하세요.', '新規利用者と支援技術が、同じ操作、状態、単位、結果、グループ関係を推測なく識別できるか確認します。'),
    t('Familiar formatting can reduce repetition, but never remove labels or instructions needed for forms, risk, consent, or unfamiliar data.', '익숙한 형식은 반복을 줄일 수 있지만 폼·위험·동의·낯선 데이터에 필요한 라벨과 설명을 없애서는 안 됩니다.', '慣れた形式で反復は減らせますが、フォーム、リスク、同意、未知データに必要なラベルや説明を消してはいけません。'),
    ['scanability', 'readability', 'accessibility'],
    ['form', 'data-table', 'checkout', 'content', 'settings'],
    ['content', 'validation'],
    ['attention-budget', 'align-for-reading'],
    ['mental-model', 'cognitive-load'],
  ),
  principle(
    'navigation-preserves-context',
    t('Make navigation reveal place and consequence', '내비게이션이 위치와 결과를 드러내게 하기', 'ナビゲーションで現在地と結果を示す'),
    ['navigation contract', 'orientation and destination', 'route versus panel'],
    'hierarchy-semantics',
    t(
      'Navigation should show where people are, where they can go, and whether activation changes location, a local view, or a filter.',
      '내비게이션은 현재 위치·갈 수 있는 곳·실행 시 바뀌는 범위가 새 위치인지 로컬 보기인지 필터인지를 보여줘야 합니다.',
      'ナビゲーションは現在地、行ける場所、操作で変わる範囲が新しい場所かローカル表示かフィルターかを示します。',
    ),
    t('Before activating an item, can a person predict the destination, scope of change, and way back?', '항목을 실행하기 전에 이동할 곳·바뀌는 범위·돌아오는 방법을 예측할 수 있나요?', '項目を実行する前に、移動先、変化の範囲、戻り方を予測できますか。'),
    t('Keep the current location and sibling destinations together, place local view controls beside the content they switch, and keep filters beside the results they constrain.', '현재 위치와 같은 단계의 목적지를 함께 두고, 로컬 보기 전환은 바뀌는 콘텐츠 가까이에, 필터는 제한하는 결과 가까이에 배치하세요.', '現在地と同階層の移動先をまとめ、ローカル表示の切替は変わる内容の近くに、フィルターは絞り込む結果の近くに置きます。'),
    t('Use route-changing controls when URL, history, refresh, or deep-link behavior matters; use local controls for in-place changes, and preserve the same labels, destinations, order, and focus logic when navigation collapses on narrow screens.', 'URL·기록·새로고침·딥링크가 중요하면 경로를 바꾸는 컨트롤을, 제자리 변화에는 로컬 컨트롤을 사용하세요. 좁은 화면에서 내비게이션이 접혀도 라벨·목적지·순서·포커스 논리는 유지하세요.', 'URL、履歴、再読込、深いリンクが重要なら経路を変える操作を、同じ場所での変化にはローカル操作を使います。狭幅で折り畳んでもラベル、移動先、順序、focusの論理を保ちます。'),
    t('Current location is explicit, keyboard order is logical, browser back and refresh preserve truth, deep links restore the same place, and mobile transformations keep every destination reachable without changing its meaning.', '현재 위치가 명시되고 키보드 순서가 논리적이며 뒤로 가기·새로고침·딥링크가 같은 상태를 복원하고, 모바일 변환 뒤에도 모든 목적지의 의미와 접근성이 유지되는지 확인하세요.', '現在地が明示され、キーボード順が論理的で、戻る、再読込、深いリンクが同じ場所を復元し、モバイル変換後も全移動先の意味と到達性が保たれるか確認します。'),
    t('Do not make unrelated mechanisms look identical: a route, an expandable hierarchy, an in-page panel, and a filter can share styling only when their behavior remains unmistakable.', '경로 이동·계층 펼치기·페이지 안 패널·필터처럼 다른 동작을 구분할 수 없게 만들지 마세요. 스타일을 공유해도 행동 차이는 분명해야 합니다.', '経路移動、階層展開、ページ内パネル、フィルターの異なる動作を見分けにくくしてはいけません。見た目を共有しても挙動の差は明確にします。'),
    ['scanability', 'consistency', 'responsiveness', 'accessibility'],
    ['navigation', 'settings', 'content', 'data-table'],
    ['structure', 'interaction', 'validation'],
    ['explicit-labels-and-semantics', 'task-sized-composition', 'multi-input-operability', 'attention-budget'],
    ['mental-model', 'jakobs-law', 'cognitive-load'],
    [sourceReferences.primerNavigation],
  ),
  principle(
    'iconography-has-a-job',
    t('Make every icon earn its place', '모든 아이콘이 역할을 갖게 하기', 'すべてのアイコンに役割を持たせる'),
    ['purposeful iconography', 'icon inventory', 'decorative icon removal'],
    'hierarchy-semantics',
    t(
      'Use icons to accelerate recognition of a repeated action, status, or identity—not to fill empty space or make generic content feel designed.',
      '아이콘은 빈 공간을 채우거나 일반적인 콘텐츠를 꾸미는 대신 반복 행동·상태·대상을 더 빨리 식별하게 할 때 사용합니다.',
      'アイコンは空白を埋めたり一般的な内容を飾ったりせず、反復する操作、状態、対象の認識を速めるために使います。',
    ),
    t('What becomes slower, less clear, or less accessible if this icon is removed?', '이 아이콘을 제거하면 무엇이 더 느려지거나 불분명하거나 접근하기 어려워지나요?', 'このアイコンを外すと、何が遅く、不明確、またはアクセシブルでなくなりますか。'),
    t('Keep useful icons next to the label, action, or state they reinforce; remove decorative icon tiles from headings and explanatory blocks that already name themselves.', '유용한 아이콘은 보강하는 라벨·행동·상태 곁에 두고, 이미 이름이 적힌 제목과 설명 블록에서는 장식용 아이콘 타일을 제거하세요.', '有用なアイコンは補強するラベル、操作、状態の隣に置き、既に名前がある見出しや説明ブロックから装飾用アイコンタイルを外します。'),
    t('Classify the icon inventory as action, status, identity, or decoration; delete decoration, label ambiguous actions, normalize repeated symbols, and reserve colored backplates for real state or selection meaning.', '아이콘 목록을 행동·상태·대상·장식으로 분류해 장식은 지우고, 모호한 행동에는 라벨을 붙이며, 반복 기호를 통일하고, 색 배경은 실제 상태나 선택 의미에만 사용하세요.', 'アイコンを操作、状態、対象、装飾に分類し、装飾を削除し、曖昧な操作にラベルを付け、反復記号を統一し、色付き背景は実際の状態や選択の意味に限定します。'),
    t('Removing decorative icons changes no task meaning; remaining icons have accessible names, familiar or taught meaning, visible focus when interactive, and redundant text or shape for critical status.', '장식 아이콘을 제거해도 과업 의미가 바뀌지 않고, 남은 아이콘에는 접근 가능한 이름·익숙하거나 설명된 의미·인터랙션 시 보이는 포커스가 있으며 중요 상태는 텍스트나 형태로도 전달되는지 확인하세요.', '装飾アイコンを外してもタスクの意味が変わらず、残るアイコンにアクセシブル名、既知または説明された意味、操作時の見えるfocusがあり、重要状態は文字や形でも伝わるか確認します。'),
    t('Text-only is not automatically clearer: keep symbols that measurably improve repeated scanning, spatial orientation, or language-independent recognition.', '텍스트만 쓴다고 항상 더 명확한 것은 아닙니다. 반복 훑기·공간 파악·언어와 무관한 식별을 실제로 개선하는 기호는 유지하세요.', '文字だけが常に明確とは限りません。反復走査、空間把握、言語に依存しない認識を実際に改善する記号は残します。'),
    ['scanability', 'consistency', 'restraint', 'accessibility'],
    ['global', 'navigation', 'settings', 'data-table', 'content'],
    ['structure', 'content', 'validation'],
    ['explicit-labels-and-semantics', 'redundant-state-signals', 'attention-budget', 'depth-explains-structure'],
    ['law-of-similarity', 'mental-model', 'selective-attention'],
    [sourceReferences.vibeCodedAudit, sourceReferences.linearRefresh],
  ),
  principle(
    'task-aware-density',
    t('Tune density to task and input', '과업과 입력 방식에 맞춰 밀도 조율하기', 'タスクと入力に合わせて密度を調整する'),
    ['task density', 'compact mode', 'comfortable mode'],
    'adaptation-density',
    t(
      'Choose density from task frequency, decision complexity, viewport, and input method instead of one fashionable spacing level.',
      '하나의 유행하는 간격이 아니라 과업 빈도·결정 복잡도·화면·입력 방식에 따라 밀도를 정합니다.',
      '一つの流行的な余白ではなく、利用頻度、判断の複雑さ、画面、入力方式から密度を決めます。',
    ),
    t('How much can this user scan and operate without losing grouping, target clarity, or reading comfort?', '이 사용자가 그룹·조작 대상·읽기 편안함을 잃지 않고 어느 정도 밀도를 다룰 수 있나요?', 'この利用者は、まとまり、操作対象、読みやすさを失わず、どの密度まで扱えますか。'),
    t('Keep frequent comparison data compact, occasional decisions calmer, and touch targets roomy without breaking relationship spacing.', '자주 비교하는 데이터는 조밀하게, 가끔 하는 결정은 차분하게, 터치 대상은 관계 간격을 깨지 않으면서 넉넉하게 배치하세요.', '頻繁な比較データは密に、時折の判断は落ち着かせ、関係余白を壊さずタッチ対象を広くします。'),
    t('Define comfortable and compact modes from shared tokens; adjust row height, gaps, and disclosure together while preserving focus and hit areas.', '공통 토큰에서 편안한·조밀한 모드를 만들고 포커스와 조작 영역을 지키며 행 높이·간격·정보 노출을 함께 조정하세요.', '共通トークンから快適・高密度モードを作り、focusと操作領域を保ちながら行高、余白、情報開示を一緒に調整します。'),
    t('Keyboard, pointer, and touch users complete the task at target zoom and viewport sizes without overlap, accidental activation, or lost grouping.', '키보드·포인터·터치 사용자가 목표 확대와 화면에서 겹침·오작동·그룹 손실 없이 과업을 완료하는지 확인하세요.', 'キーボード、ポインター、タッチ利用者が対象拡大と画面で、重なり、誤操作、まとまりの喪失なく完了できるか確認します。'),
    t('Compactness never overrides readable text, visible focus, minimum targets, error comprehension, or required context.', '조밀함이 읽을 수 있는 글자·보이는 포커스·최소 조작 영역·오류 이해·필수 맥락보다 우선해서는 안 됩니다.', '高密度化を、可読文字、見えるfocus、最小操作領域、エラー理解、必須文脈より優先してはいけません。'),
    ['grouping', 'balance', 'responsiveness'],
    ['global'],
    ['structure', 'validation'],
    ['relational-spacing', 'task-sized-composition'],
    ['law-of-proximity', 'law-of-common-region'],
    [sourceReferences.vibeCodedAudit],
  ),
  principle(
    'relational-spacing',
    t('Make spacing express relationships', '간격으로 관계 표현하기', '余白で関係を表す'),
    ['spacing rhythm', 'unambiguous spacing'],
    'adaptation-density',
    t(
      'Choose spacing from a bounded scale and use gap size to encode whether elements belong together.',
      '제한된 간격 척도를 쓰고, 간격 크기로 요소가 같은 그룹인지 표현합니다.',
      '限られた余白尺度を使い、間隔の大きさで要素の所属関係を表します。',
    ),
    t('Does every gap tell one clear grouping story?', '각 간격이 하나의 분명한 그룹 관계를 말하고 있나요?', 'それぞれの余白が一つの明確なグループ関係を示していますか。'),
    t('Place labels nearer their controls than neighboring controls, and validation nearer its field than the next field.', '라벨은 이웃 컨트롤보다 해당 컨트롤에, 검증 메시지는 다음 필드보다 해당 필드에 더 가깝게 두세요.', 'ラベルは隣の操作より対象操作に、検証文は次の項目より対象項目に近づけます。'),
    t('Map recurring relationships to named gaps and use the same relationship-gap pair across breakpoints.', '반복 관계를 이름 붙인 간격에 연결하고, 화면 폭이 바뀌어도 같은 관계-간격 짝을 유지하세요.', '繰り返す関係を名前付き余白に結び、画面幅が変わっても同じ関係と余白の組を保ちます。'),
    t('Cover labels and borders: proximity alone still reveals the intended groups.', '라벨과 경계를 가려도 근접성만으로 의도한 그룹이 드러나는지 확인하세요.', 'ラベルと境界を隠しても、近接だけで意図したグループが分かるか確認します。'),
    t('Do not use equal gaps where two different relationships must be distinguished.', '서로 다른 두 관계를 구분해야 하는 곳에 같은 간격을 쓰지 마세요.', '異なる二つの関係を区別すべき場所で、同じ余白を使わないでください。'),
    ['grouping', 'consistency', 'responsiveness'],
    ['landing-page', 'form', 'data-table', 'checkout', 'settings', 'content'],
    ['structure', 'validation'],
    ['task-aware-density', 'bounded-choice-system'],
    ['law-of-proximity', 'law-of-common-region'],
  ),
  principle(
    'task-sized-composition',
    t('Adapt by content and container', '콘텐츠와 컨테이너에 맞춰 적응하기', '内容とコンテナに合わせて適応する'),
    ['container-aware layout', 'content-sized layout', 'reflow order'],
    'adaptation-density',
    t(
      'Use only the width and columns the content can justify; a viewport is available space, not a fill target.',
      '콘텐츠가 정당화할 수 있는 너비와 열만 쓰고, 화면을 채워야 할 목표로 보지 않습니다.',
      '内容が必要とする幅と列だけを使い、画面全体を埋めることを目標にしません。',
    ),
    t('What must reflow, reorder, or disclose differently when this component—not only the viewport—becomes narrow?', '화면뿐 아니라 이 컴포넌트 자체가 좁아지면 무엇이 재배치·재정렬·별도 노출되어야 하나요?', '画面だけでなく、このコンポーネント自体が狭くなると、何を再配置、並替え、別表示すべきですか。'),
    t('Keep reading and form columns to their useful measure; reserve wide spans for comparisons, canvases, or dense data.', '읽기와 폼 열은 유용한 폭으로 제한하고, 비교·캔버스·고밀도 데이터에만 넓은 폭을 쓰세요.', '読書やフォーム列は適切な幅に保ち、比較、キャンバス、高密度データだけを広くします。'),
    t('Build columns from content relationships and source order; define container-based collapse, text expansion, and focus order before visual rearrangement.', '콘텐츠 관계와 소스 순서에서 열을 만들고 시각 재배치 전에 컨테이너 기반 접힘·텍스트 확장·포커스 순서를 정의하세요.', '内容関係とソース順から列を作り、視覚的再配置前にコンテナ基準の折畳み、文字伸長、focus順を定義します。'),
    t('At 320 CSS pixels and 400% zoom, content reflows without two-dimensional scrolling, clipped controls, broken reading order, or hidden core actions.', '320 CSS 픽셀과 400% 확대에서 양방향 스크롤·잘린 컨트롤·깨진 읽기 순서·숨은 핵심 행동 없이 재배치되는지 확인하세요.', '320 CSSピクセルと400%拡大で、二方向スクロール、操作切れ、読順崩れ、主要操作の隠蔽なく再配置されるか確認します。'),
    t('Do not collapse away essential comparison, status, consent, or recovery controls merely to make a narrow layout look clean.', '좁은 배치를 깔끔하게 보이게 하려고 필수 비교·상태·동의·복구 컨트롤을 접어 숨기지 마세요.', '狭い配置を整えるために、必須の比較、状態、同意、回復操作を折り畳んで隠してはいけません。'),
    ['balance', 'responsiveness', 'readability'],
    ['landing-page', 'form', 'data-table', 'content', 'developer-console'],
    ['structure', 'validation'],
    ['core-task-first', 'task-aware-density'],
    ['cognitive-load', 'law-of-common-region'],
  ),
  principle(
    'deliberate-type-scale',
    t('Use a deliberate type scale', '의도적인 글자 척도 쓰기', '意図した文字尺度を使う'),
    ['type scale', 'typographic hierarchy'],
    'typography-localization',
    t(
      'Use a short, named set of sizes and weights so text roles repeat predictably across screens.',
      '짧고 이름 붙인 크기·굵기 세트로 화면마다 텍스트 역할을 예측 가능하게 반복합니다.',
      '少数の名前付きサイズと太さで、画面をまたいで文字役割を予測可能にします。',
    ),
    t('Can every text size be explained by a role rather than a local visual preference?', '모든 글자 크기를 지역적 취향이 아니라 역할로 설명할 수 있나요?', 'すべての文字サイズを、その場の好みではなく役割で説明できますか。'),
    t('Place display, heading, body, label, and metadata roles in a stable descending sequence.', '디스플레이·제목·본문·라벨·메타데이터 역할을 안정적인 내림차순으로 배치하세요.', '表示見出し、見出し、本文、ラベル、メタ情報を安定した降順で配置します。'),
    t('Start with body text, derive nearby steps, then use weight and spacing before inventing extra sizes.', '본문 크기에서 가까운 단계를 만들고, 새 크기를 추가하기 전에 굵기와 간격을 먼저 쓰세요.', '本文から近い段階を作り、新しいサイズを足す前に太さと余白を使います。'),
    t('A cross-screen inventory shows one role using one size range, including localized text.', '다국어 텍스트를 포함한 화면 간 목록에서 같은 역할이 같은 크기 범위를 쓰는지 확인하세요.', '多言語を含む画面横断の一覧で、同じ役割が同じサイズ範囲を使うか確認します。'),
    t('Do not shrink utility text below readable sizes to preserve an overly ambitious hierarchy.', '과도한 위계를 유지하려고 보조 텍스트를 읽기 어려운 크기로 줄이지 마세요.', '過剰な階層を守るために、補助文字を読めない大きさまで縮めないでください。'),
    ['consistency', 'scanability', 'readability'],
    ['global', 'landing-page'],
    ['structure', 'content', 'validation'],
    ['bounded-choice-system', 'measure-and-leading'],
    ['law-of-similarity', 'selective-attention'],
    [sourceReferences.vibeCodedAudit],
  ),
  principle(
    'measure-and-leading',
    t('Tune measure and leading together', '행 길이와 행간 함께 조율하기', '行長と行間を一緒に調整する'),
    ['line length', 'line height', 'reading measure'],
    'typography-localization',
    t(
      'Line length, font size, and line height form one reading system and should change together.',
      '행 길이·글자 크기·행간을 하나의 읽기 체계로 보고 함께 조정합니다.',
      '行長、文字サイズ、行間を一つの読書システムとして一緒に調整します。',
    ),
    t('Can the eye find the next line without losing place or feeling cramped?', '눈이 위치를 잃거나 답답함 없이 다음 줄을 찾을 수 있나요?', '視線が位置を失わず、窮屈さもなく次の行を見つけられますか。'),
    t('Keep long-form text in a bounded reading column; allow short labels and data to use different measures.', '장문은 제한된 읽기 열에 두고, 짧은 라벨과 데이터에는 다른 폭을 허용하세요.', '長文は制限した読書列に置き、短いラベルやデータには別の幅を許します。'),
    t('Increase leading as measure widens or body text becomes smaller, then test with the longest locale.', '행이 길어지거나 본문이 작아질수록 행간을 늘리고, 가장 긴 언어로 테스트하세요.', '行が長くなる、または本文が小さくなるほど行間を広げ、最長の言語で試します。'),
    t('Readers can scan three paragraphs without horizontal wandering, clipped glyphs, or line collisions at 200% zoom.', '200% 확대에서 가로로 헤매거나 글자가 잘리거나 줄이 겹치지 않고 세 문단을 읽을 수 있는지 확인하세요.', '200%拡大で横に迷わず、字切れや行の衝突なく三段落を読めるか確認します。'),
    t('Do not apply one fixed line-height ratio to every size, script, and font.', '모든 크기·문자 체계·글꼴에 하나의 고정 행간 비율을 적용하지 마세요.', 'すべてのサイズ、文字体系、書体に同じ行間比率を適用しないでください。'),
    ['readability', 'responsiveness', 'accessibility'],
    ['content', 'landing-page', 'developer-console'],
    ['content', 'validation'],
    ['deliberate-type-scale', 'align-for-reading'],
    ['cognitive-load', 'working-memory'],
  ),
  principle(
    'align-for-reading',
    t('Respect locale, script, and direction', '언어·문자·방향 존중하기', '言語・文字・方向を尊重する'),
    ['international typography', 'rtl layout', 'text expansion'],
    'typography-localization',
    t(
      'Let script, direction, line-breaking, fallback fonts, and locale formats shape alignment and available space.',
      '문자 체계·방향·줄바꿈·대체 글꼴·지역 형식이 정렬과 사용 공간을 결정하게 합니다.',
      '文字体系、方向、改行、代替書体、地域形式に合わせて整列と利用空間を決めます。',
    ),
    t('What changes when text expands, runs right-to-left, mixes directions, or uses a different date, number, or currency format?', '텍스트가 늘어나거나 오른쪽에서 왼쪽으로 흐르거나 방향이 섞이거나 날짜·숫자·통화 형식이 달라지면 무엇이 바뀌나요?', '文字が伸びる、右から左へ流れる、方向が混在する、日付・数値・通貨形式が変わると何が変わりますか。'),
    t('Use logical start/end alignment, keep labels near controls, and isolate mixed-direction user content without changing source order.', '논리적 시작/끝 정렬을 쓰고 라벨을 컨트롤 가까이에 두며 소스 순서를 바꾸지 않고 혼합 방향 사용자 콘텐츠를 분리하세요.', '論理的なstart/end整列を使い、ラベルを操作の近くに置き、ソース順を変えず混在方向の内容を分離します。'),
    t('Use script-appropriate fallback and line breaking, locale-aware formats, logical CSS properties, and pseudolocalized text before translation arrives.', '문자 체계에 맞는 대체 글꼴·줄바꿈, 지역 형식, 논리 CSS 속성, 의사 현지화 텍스트를 실제 번역 전에 적용하세요.', '文字体系に合う代替書体と改行、地域形式、論理CSS、疑似翻訳文字を本翻訳前に適用します。'),
    t('LTR, RTL, CJK, mixed-direction names, 30–50% text expansion, zoom, and fallback fonts preserve reading order, alignment, and control access.', 'LTR·RTL·CJK·혼합 방향 이름·30–50% 텍스트 확장·확대·대체 글꼴에서도 읽기 순서·정렬·컨트롤 접근을 지키는지 확인하세요.', 'LTR、RTL、CJK、混在方向名、30–50%文字伸長、拡大、代替書体でも読順、整列、操作アクセスを保つか確認します。'),
    t('Do not mirror semantics, brand marks, media controls, charts, or directional data merely because the interface direction changes.', '인터페이스 방향이 바뀐다는 이유만으로 의미·브랜드 마크·미디어 컨트롤·차트·방향성 데이터를 뒤집지 마세요.', '画面方向が変わるだけで、意味、ブランド印、メディア操作、図表、方向性データを反転してはいけません。'),
    ['readability', 'responsiveness', 'accessibility'],
    ['global'],
    ['structure', 'content', 'validation'],
    ['measure-and-leading', 'explicit-labels-and-semantics'],
    ['law-of-proximity', 'mental-model'],
  ),
  principle(
    'role-based-color',
    t('Assign color by role', '역할에 따라 색 지정하기', '役割に応じて色を割り当てる'),
    ['semantic color', 'color roles'],
    'tokens-color-themes',
    t(
      'Name colors by interface purpose—canvas, text, border, action, status—not by isolated swatches.',
      '색을 개별 견본이 아니라 배경·텍스트·경계·행동·상태 같은 인터페이스 역할로 이름 붙입니다.',
      '色を単独の見本ではなく、背景、文字、境界、操作、状態などの役割で名付けます。',
    ),
    t('What stable interface meaning does each color communicate?', '각 색이 전달하는 안정적인 인터페이스 의미는 무엇인가요?', '各色はどの安定したインターフェース上の意味を伝えますか。'),
    t('Keep action and status colors nearest the controls or messages they qualify; keep decorative color outside semantic channels.', '행동·상태 색은 해당 컨트롤이나 메시지 가까이에 두고, 장식 색은 의미 채널과 분리하세요.', '操作・状態色は対象の操作や文の近くに置き、装飾色は意味の経路から分けます。'),
    t('Define role tokens first, map palettes second, and test every role across light, dark, hover, focus, and disabled states.', '역할 토큰을 먼저 정의하고 팔레트를 연결한 뒤 밝음·어두움·호버·포커스·비활성 상태를 모두 확인하세요.', '役割トークンを先に定義し、配色を割り当て、明暗、hover、focus、disabledを確認します。'),
    t('The same color role has the same meaning across screens, and swapped themes preserve that meaning.', '같은 색 역할이 모든 화면에서 같은 의미를 갖고, 테마를 바꿔도 의미가 유지되는지 확인하세요.', '同じ色役割が画面をまたいで同じ意味を持ち、テーマ変更後も保たれるか確認します。'),
    t('Do not reuse one accent for unrelated meanings such as selection, success, warning, and branding.', '선택·성공·경고·브랜드처럼 서로 다른 의미에 하나의 강조색을 재사용하지 마세요.', '選択、成功、警告、ブランドなど異なる意味に同じ強調色を使い回さないでください。'),
    ['consistency', 'accessibility', 'focus'],
    ['global'],
    ['structure', 'validation'],
    ['perceptual-color-ramps', 'redundant-state-signals'],
    ['law-of-similarity', 'mental-model'],
    [sourceReferences.vibeCodedAudit],
  ),
  principle(
    'perceptual-color-ramps',
    t('Build perceptual color ramps', '지각적으로 자연스러운 색 단계 만들기', '知覚的に自然な色段階を作る'),
    ['perceptual color', 'wide gamut fallback', 'color scales'],
    'tokens-color-themes',
    t(
      'Create role-ready color families in a perceptual space, then preserve intent across gamut, theme, and fallback changes.',
      '지각 색 공간에서 역할에 쓸 색 계열을 만들고 색역·테마·대체 색이 달라도 의도를 유지합니다.',
      '知覚色空間で役割向けの色系列を作り、色域、テーマ、代替色が変わっても意図を保ちます。',
    ),
    t('Do adjacent shades remain distinct while still feeling like one family?', '인접한 색 단계가 구분되면서도 한 계열로 느껴지나요?', '隣り合う色段階は区別でき、同じ系列にも見えますか。'),
    t('Place light steps on surfaces, middle steps on borders or secondary states, and dark steps on text or strong actions only after contrast tests.', '밝은 단계는 면, 중간 단계는 경계·보조 상태, 어두운 단계는 대비 검증 뒤 텍스트·강한 행동에 배치하세요.', '明るい段階は面、中間は境界や補助状態、暗い段階は対比確認後に文字や強い操作へ使います。'),
    t('Tune endpoints in context, interpolate in a perceptual space, correct clipped or muddy steps, and define safe fallbacks for unsupported gamuts.', '맥락에서 양 끝을 조정하고 지각 공간에서 중간을 만든 뒤 잘리거나 탁한 단계를 보정하고 지원되지 않는 색역의 안전한 대체 색을 정의하세요.', '文脈で両端を調整し、知覚空間で中間を作り、切れや濁りを補正し、未対応色域の安全な代替色を定義します。'),
    t('Neighboring steps remain distinct on real surfaces, semantic roles keep contrast in every theme, and wide-gamut colors degrade without changing meaning.', '실제 면에서 인접 단계가 구분되고 모든 테마에서 의미 역할의 대비를 지키며 광색역 색이 의미 변화 없이 대체되는지 확인하세요.', '実面で隣接段階が区別でき、全テーマで意味役割の対比を保ち、広色域色が意味を変えず代替されるか確認します。'),
    t('Perceptual uniformity, wide gamut, or a mathematically neat scale does not automatically make a pairing accessible.', '지각적 균일성·광색역·수학적으로 깔끔한 척도가 조합의 접근성을 자동으로 보장하지는 않습니다.', '知覚的均一性、広色域、数値的に整った尺度だけで組合せのアクセシビリティは保証されません。'),
    ['consistency', 'readability', 'accessibility'],
    ['global'],
    ['structure', 'validation'],
    ['role-based-color', 'contrast-before-scale'],
    ['law-of-similarity', 'aesthetic-usability-effect'],
  ),
  principle(
    'redundant-state-signals',
    t('Expose state visually and programmatically', '상태를 시각적·프로그램적으로 드러내기', '状態を視覚的・プログラム的に示す'),
    ['redundant encoding', 'accessible status', 'forced colors'],
    'interaction-accessibility',
    t(
      'Represent current, selected, expanded, busy, invalid, and completed states with visible cues and machine-readable state.',
      '현재·선택·펼침·처리 중·오류·완료 상태를 보이는 단서와 기계가 읽을 수 있는 상태로 함께 표현합니다.',
      '現在、選択、展開、処理中、無効、完了を、見える手掛かりと機械可読状態の両方で表します。',
    ),
    t('If color, animation, or iconography disappears, do users and assistive technology still receive the same state and next action?', '색·애니메이션·아이콘이 사라져도 사용자와 보조 기술이 같은 상태와 다음 행동을 받나요?', '色、動き、アイコンが消えても、利用者と支援技術は同じ状態と次の操作を受け取れますか。'),
    t('Place the non-color cue inside or immediately beside the stateful element, not in a distant legend.', '비색상 단서는 먼 범례가 아니라 상태 요소 안이나 바로 옆에 배치하세요.', '色以外の手掛かりは遠い凡例ではなく、状態要素の中か直近に置きます。'),
    t('Pair at least two visible cues with the correct semantic state, status announcement, focus behavior, and update timing.', '최소 두 개의 보이는 단서를 올바른 의미 상태·상태 알림·포커스 동작·업데이트 시점과 연결하세요.', '二つ以上の見える手掛かりを、正しい意味状態、状態通知、focus挙動、更新時点と結びます。'),
    t('Grayscale, forced-colors, high contrast, reduced motion, keyboard focus, and screen-reader checks preserve every critical distinction.', '회색조·강제 색상·고대비·동작 축소·키보드 포커스·스크린 리더에서도 중요한 구분이 유지되는지 확인하세요.', 'グレースケール、強制色、高対比、動き削減、キーボードfocus、スクリーンリーダーでも重要な区別を保つか確認します。'),
    t('An icon without a visible or accessible label may simply replace one ambiguous signal with another.', '보이거나 접근 가능한 라벨이 없는 아이콘은 모호한 신호를 다른 모호한 신호로 바꿀 뿐일 수 있습니다.', '見える、またはアクセシブルなラベルのないアイコンは、曖昧さを別の曖昧さに置き換えるだけかもしれません。'),
    ['accessibility', 'resilience', 'consistency'],
    ['form', 'data-table', 'checkout', 'chat', 'developer-console', 'settings'],
    ['interaction', 'validation'],
    ['role-based-color', 'contrast-before-scale'],
    ['law-of-similarity', 'doherty-threshold'],
  ),
  principle(
    'multi-input-operability',
    t('Support every input mode', '모든 입력 방식 지원하기', 'すべての入力方式を支える'),
    ['concurrent input', 'keyboard touch pointer', 'drag alternative'],
    'interaction-accessibility',
    t(
      'Make the same task operable by keyboard, touch, pointer, stylus, speech, and assistive technology without mode traps.',
      '키보드·터치·포인터·스타일러스·음성·보조 기술로 같은 과업을 모드 함정 없이 조작하게 합니다.',
      'キーボード、タッチ、ポインター、スタイラス、音声、支援技術で同じタスクをモードの罠なく操作可能にします。',
    ),
    t('Can users reach, identify, activate, cancel, and recover from every control without relying on hover, dragging, or fine pointer precision?', '호버·드래그·정밀 포인터에 기대지 않고 모든 컨트롤에 도달·식별·실행·취소·복구할 수 있나요?', 'hover、ドラッグ、精密ポインターに頼らず、全操作へ到達、識別、実行、取消、回復できますか。'),
    t('Keep alternatives beside gesture-only controls, preserve logical focus order, and place visible focus where it cannot be obscured.', '제스처 전용 컨트롤 옆에 대안을 두고 논리적 포커스 순서를 지키며 가려지지 않는 곳에 보이는 포커스를 배치하세요.', 'ジェスチャー専用操作の隣に代替を置き、論理的focus順を保ち、隠れない位置にfocusを表示します。'),
    t('Give hover and focus equivalent information, provide drag and motion alternatives, use forgiving targets, and support input switching without reset.', '호버와 포커스에 같은 정보를 주고 드래그·동작 대안을 제공하며 여유 있는 조작 영역과 상태 초기화 없는 입력 전환을 지원하세요.', 'hoverとfocusに同じ情報を与え、ドラッグと動作の代替、余裕ある操作領域、状態を失わない入力切替を支えます。'),
    t('Complete the task with keyboard only, touch only, pointer only, zoom, screen reader, and mid-task input switching without lost focus or accidental activation.', '키보드만·터치만·포인터만·확대·스크린 리더·과업 중 입력 전환으로 포커스 손실이나 오작동 없이 완료하는지 확인하세요.', 'キーボードのみ、タッチのみ、ポインターのみ、拡大、スクリーンリーダー、途中入力切替でfocus喪失や誤操作なく完了できるか確認します。'),
    t('Do not infer a user’s ability from the device or remove keyboard behavior because a pointer is present.', '기기만 보고 사용자의 능력을 추정하거나 포인터가 있다는 이유로 키보드 동작을 제거하지 마세요.', '端末から利用者の能力を推測したり、ポインターがあるためキーボード操作を削除したりしないでください。'),
    ['accessibility', 'resilience', 'responsiveness'],
    ['navigation', 'form', 'data-table', 'checkout', 'onboarding', 'chat', 'developer-console', 'settings'],
    ['interaction', 'validation'],
    ['redundant-state-signals', 'complete-state-model'],
    ['fitts-law', 'mental-model'],
  ),
  principle(
    'depth-explains-structure',
    t('Use depth to explain structure', '깊이로 구조 설명하기', '奥行きで構造を説明する'),
    ['elevation hierarchy', 'layering'],
    'hierarchy-semantics',
    t(
      'Use overlap, elevation, and inset treatment only when they clarify containment, priority, or temporary layers.',
      '포함 관계·우선순위·임시 레이어를 분명히 할 때만 겹침·높이·들어간 처리를 씁니다.',
      '包含、優先度、一時レイヤーを明確にする場合だけ、重なり、奥行き、窪みを使います。',
    ),
    t('What relationship would become less clear if this shadow or overlap disappeared?', '이 그림자나 겹침이 사라지면 어떤 관계가 덜 분명해지나요?', 'この影や重なりが消えると、どの関係が不明確になりますか。'),
    t('Place temporary or movable layers above their origin and keep persistent content on the base plane.', '임시·이동 레이어는 출발 요소 위에 두고, 지속 콘텐츠는 기본 평면에 유지하세요.', '一時的・移動可能なレイヤーは起点の上に置き、永続内容は基底面に保ちます。'),
    t('Choose space, background, border, overlap, or elevation by the relationship it explains; inventory separators and icon backplates, then remove every one that repeats information already carried by spacing or type.', '간격·배경·경계·겹침·높이를 설명할 관계에 따라 고르세요. 구분선과 아이콘 배경을 목록으로 만든 뒤, 간격이나 글자가 이미 전달하는 정보를 반복하는 것은 제거하세요.', '余白、背景、境界、重なり、奥行きを説明する関係で選びます。区切り線とアイコン背景を棚卸しし、余白や文字が既に伝える情報を反復するものは外します。'),
    t('Removing each separator or surface one at a time either preserves clarity or reveals the exact relationship it owns; dialogs, popovers, sticky regions, portals, and overlapping media still keep containment, reading order, focus, clipping, and stacking.', '구분선과 표면을 하나씩 지웠을 때 명료함이 유지되거나, 그 요소가 담당한 정확한 관계가 드러나는지 확인하세요. 대화상자·팝오버·고정 영역·포털·겹치는 미디어도 포함 관계·읽기 순서·포커스·잘림·쌓임을 지켜야 합니다.', '区切りや面を一つずつ外したとき、明瞭さが保たれるか、その要素が担う正確な関係が明らかになるか確認します。ダイアログ、popover、固定領域、portal、重なるmediaも包含、読順、focus、切抜き、重なりを保つ必要があります。'),
    t('Too many elevated surfaces flatten the hierarchy and make every region look interactive.', '높은 면이 너무 많으면 위계가 평평해지고 모든 영역이 조작 가능해 보입니다.', '浮いた面が多すぎると階層が平坦になり、すべてが操作可能に見えます。'),
    ['grouping', 'focus', 'restraint'],
    ['navigation', 'form', 'data-table', 'checkout', 'chat', 'settings'],
    ['structure', 'interaction', 'validation'],
    ['relational-spacing', 'attention-budget'],
    ['law-of-common-region', 'law-of-uniform-connectedness'],
    [sourceReferences.linearRefresh, sourceReferences.vibeCodedAudit],
  ),
  principle(
    'resilient-imagery',
    t('Design imagery for hostile content', '예측 불가능한 콘텐츠에도 견디는 이미지', '予測不能な内容に耐える画像設計'),
    ['resilient images', 'content-safe media'],
    'adaptation-density',
    t(
      'Treat crops, aspect ratios, overlays, and user uploads as variable input rather than ideal art direction.',
      '자르기·비율·오버레이·사용자 업로드를 이상적인 연출이 아니라 변동 입력으로 다룹니다.',
      '切り抜き、比率、オーバーレイ、ユーザー画像を理想的演出ではなく変動入力として扱います。',
    ),
    t('What happens when the image is bright, dark, busy, tiny, missing, or the wrong aspect ratio?', '이미지가 밝거나 어둡거나 복잡하거나 작거나 없거나 비율이 다르면 어떻게 되나요?', '画像が明るい、暗い、複雑、小さい、欠落、異なる比率の場合どうなりますか。'),
    t('Place essential text outside unpredictable imagery, or give it a content-independent contrast surface.', '필수 텍스트는 예측 불가능한 이미지 밖에 두거나, 콘텐츠와 무관하게 대비가 보장되는 면 위에 배치하세요.', '重要な文字は予測不能な画像の外に置くか、内容に依存せず対比を保つ面に載せます。'),
    t('Define crop focal points, min/max ratios, placeholders, error fallbacks, and moderation-safe overflow behavior.', '초점 자르기·최소/최대 비율·자리표시자·오류 대체·안전한 넘침 동작을 정의하세요.', '焦点切抜き、最小最大比率、代替表示、エラー時代替、安全なはみ出し処理を定義します。'),
    t('A stress set of extreme images preserves legibility, identity, layout stability, and meaningful alt text.', '극단적인 이미지 묶음에서도 가독성·식별·레이아웃 안정성·의미 있는 대체 텍스트가 유지되는지 확인하세요.', '極端な画像セットでも可読性、識別、レイアウト安定性、意味のある代替文が保たれるか確認します。'),
    t('A dark overlay cannot guarantee contrast over every image and may erase important image detail.', '어두운 오버레이만으로 모든 이미지의 대비를 보장할 수 없고 중요한 디테일을 지울 수 있습니다.', '暗いオーバーレイだけでは全画像の対比を保証できず、重要な細部を消す場合があります。'),
    ['resilience', 'responsiveness', 'accessibility'],
    ['landing-page', 'content', 'onboarding', 'chat'],
    ['content', 'validation'],
    ['task-sized-composition', 'redundant-state-signals'],
    ['postels-law', 'cognitive-load'],
  ),
  principle(
    'complete-state-model',
    t('Design the complete state model', '전체 상태 모델 설계하기', '状態モデル全体を設計する'),
    ['ui state matrix', 'non-happy paths', 'offline and stale'],
    'states-feedback-recovery',
    t(
      'Treat loading, empty, partial, stale, offline, permission, error, success, conflict, and timeout as one explicit interface contract.',
      '로딩·빈 상태·부분 데이터·오래된 데이터·오프라인·권한·오류·성공·충돌·시간 초과를 하나의 명시적 인터페이스 계약으로 다룹니다.',
      '読込、空、一部、古い情報、offline、権限、エラー、成功、競合、timeoutを一つの明示的な画面契約として扱います。',
    ),
    t('What does the user see, hear, retain, and do next for every data, network, permission, and interaction state?', '모든 데이터·네트워크·권한·상호작용 상태에서 사용자가 무엇을 보고 듣고 유지하며 다음에 무엇을 하나요?', '各データ、network、権限、操作状態で、利用者は何を見聞きし、何を保持し、次に何をしますか。'),
    t('Keep state feedback in the affected region, preserve stable context around it, and place the safest relevant action beside the explanation.', '상태 피드백을 영향받는 영역에 두고 주변 맥락을 안정적으로 유지하며 가장 안전하고 관련 있는 행동을 설명 옆에 배치하세요.', '状態feedbackを影響領域に置き、周囲の文脈を安定させ、安全で関連する操作を説明の隣に置きます。'),
    t('Define triggers, must-show data, forbidden implications, focus targets, announcements, retained input, retry rules, and transition order for each state.', '각 상태의 발생 조건·필수 정보·금지 암시·포커스 대상·알림·입력 보존·재시도 규칙·전환 순서를 정의하세요.', '各状態の発生条件、必須情報、禁止表現、focus先、通知、入力保持、再試行規則、遷移順を定義します。'),
    t('State-matrix tests cover loading, skeleton, empty causes, partial, stale, offline, permission, disabled, error, timeout, success, and conflict without losing input, focus, or scroll.', '상태 행렬 테스트가 입력·포커스·스크롤을 잃지 않고 로딩·스켈레톤·빈 상태 원인·부분·오래됨·오프라인·권한·비활성·오류·시간 초과·성공·충돌을 다루는지 확인하세요.', '状態表テストが入力、focus、scrollを失わず、読込、skeleton、空の原因、一部、古い情報、offline、権限、disabled、error、timeout、成功、競合を扱うか確認します。'),
    t('Never show a generic empty or success state when the system cannot distinguish missing data, filters, permissions, delay, failure, or completion.', '시스템이 데이터 없음·필터·권한·지연·실패·완료를 구분하지 못하는데 일반적인 빈 상태나 성공 상태를 보여주지 마세요.', 'データなし、filter、権限、遅延、失敗、完了を区別できないのに、汎用の空状態や成功を表示してはいけません。'),
    ['resilience', 'focus', 'accessibility'],
    ['search', 'form', 'data-table', 'checkout', 'onboarding', 'content', 'chat', 'developer-console', 'settings'],
    ['interaction', 'content', 'validation'],
    ['core-task-first', 'explicit-labels-and-semantics', 'recoverable-actions'],
    ['doherty-threshold', 'zeigarnik-effect'],
    [sourceReferences.vibeCodedAudit],
  ),
  principle(
    'recoverable-actions',
    t('Make actions recoverable', '행동을 복구 가능하게 만들기', '操作を回復可能にする'),
    ['undo cancel retry', 'optimistic rollback', 'conflict recovery'],
    'states-feedback-recovery',
    t(
      'Provide a proportional way to cancel, undo, retry, restore, or resolve actions before their consequences become irreversible.',
      '행동의 결과가 되돌릴 수 없게 되기 전에 취소·실행 취소·재시도·복원·충돌 해결 경로를 비례하게 제공합니다.',
      '結果が不可逆になる前に、取消、undo、再試行、復元、競合解決の経路を影響に応じて用意します。',
    ),
    t('How can the user safely stop, reverse, or resume this action if the network, automation, or their intent changes?', '네트워크·자동화·사용자 의도가 바뀌면 이 행동을 어떻게 안전하게 멈추고 되돌리고 이어갈 수 있나요?', 'network、自動化、利用者の意図が変わったとき、この操作をどう安全に止め、戻し、再開できますか。'),
    t('Place cancel during progress, undo beside confirmed results, retry beside failure, and conflict resolution beside the affected object.', '진행 중에는 취소를, 확정 결과 옆에는 실행 취소를, 실패 옆에는 재시도를, 영향받은 객체 옆에는 충돌 해결을 배치하세요.', '進行中は取消、確定結果の隣はundo、失敗の隣は再試行、影響対象の隣は競合解決を置きます。'),
    t('Define idempotent retry, autosave status, optimistic rollback, conflict copies, destructive confirmation, and an explicit irreversible boundary.', '멱등 재시도·자동 저장 상태·낙관적 롤백·충돌 사본·파괴적 확인·명시적인 비가역 경계를 정의하세요.', '冪等再試行、自動保存状態、楽観的rollback、競合copy、破壊確認、明示的な不可逆境界を定義します。'),
    t('Cancel, undo, retry, offline recovery, duplicate submission, conflict, and expired-session tests preserve data and communicate the final truth.', '취소·실행 취소·재시도·오프라인 복구·중복 제출·충돌·세션 만료 테스트가 데이터를 보존하고 최종 사실을 정확히 알리는지 확인하세요.', '取消、undo、再試行、offline回復、重複送信、競合、session期限切れでデータを保ち、最終事実を正確に伝えるか確認します。'),
    t('Confirmation is not recovery: do not replace undo or rollback with repeated warning dialogs when a safer reversible design is possible.', '확인 대화상자는 복구가 아니므로 더 안전하게 되돌릴 수 있는데 반복 경고로 실행 취소나 롤백을 대신하지 마세요.', '確認dialogは回復ではありません。安全に戻せるなら、undoやrollbackを繰り返す警告で代替しないでください。'),
    ['resilience', 'accessibility', 'consistency'],
    ['form', 'data-table', 'checkout', 'content', 'chat', 'developer-console', 'settings'],
    ['interaction', 'validation'],
    ['complete-state-model', 'redundant-state-signals'],
    ['mental-model', 'teslers-law'],
  ),
  principle(
    'motion-and-preference',
    t('Use motion to explain what changed', '움직임으로 무엇이 바뀌었는지 설명하기', '動きで何が変わったかを説明する'),
    ['reduced motion', 'transition continuity', 'motion preference'],
    'states-feedback-recovery',
    t(
      'Connect the action a person took to the result that changed on screen.',
      '사용자가 누른 행동과 화면에서 바뀐 결과를 자연스럽게 연결합니다.',
      '利用者が行った操作と、画面で変わった結果を自然につなぎます。',
    ),
    t('After something is pressed, what changed, where did it change, and can that be understood without motion?', '무엇을 눌러 무엇이 바뀌었는지, 움직임이 없어도 알 수 있나요?', '何を押して何が変わったのか、動きがなくても理解できますか。'),
    t('Keep the control and the affected result in the same visual context so the eye can follow action to outcome.', '누른 컨트롤과 영향을 받은 결과를 같은 시각 맥락에 두어 행동에서 결과까지 시선이 이어지게 하세요.', '押したコントロールと影響を受けた結果を同じ視覚文脈に置き、操作から結果まで視線が続くようにします。'),
    t('Acknowledge the action immediately, reveal the changed object where it now belongs, keep transitions brief and interruptible, and show the same text or state cue when reduced motion is preferred.', '행동을 즉시 확인해 주고 바뀐 대상을 실제 위치에 보여주세요. 전환은 짧고 중단 가능하게 하며, 동작 축소 설정에서는 같은 텍스트나 상태 표시와 함께 즉시 갱신하세요.', '操作をすぐに受け付け、変わった対象を実際の位置に示します。遷移は短く中断可能にし、動きを減らす設定では同じ文字や状態表示とともに即時更新します。'),
    t('With animation disabled, the control label, changed object, status text, focus, and reading position still communicate the same cause and result.', '애니메이션을 꺼도 컨트롤 라벨·바뀐 대상·상태 문구·포커스·읽기 위치만으로 같은 원인과 결과를 이해할 수 있는지 확인하세요.', 'アニメーションを無効にしても、コントロールのラベル、変化した対象、状態文、フォーカス、読書位置だけで同じ原因と結果が伝わるか確認します。'),
    t('Do not use decorative motion to delay action, replace status text, pull attention away from the result, or disguise a broken transition.', '장식 움직임으로 행동을 늦추거나 상태 문구를 대신하거나 결과에서 주의를 빼앗거나 깨진 전환을 그럴듯하게 가리지 마세요.', '装飾的な動きで操作を遅らせ、状態文を置き換え、結果から注意をそらし、壊れた遷移をごまかしてはいけません。'),
    ['focus', 'resilience', 'accessibility', 'restraint'],
    ['global', 'landing-page'],
    ['interaction', 'validation'],
    ['complete-state-model', 'attention-budget'],
    ['doherty-threshold', 'mental-model'],
  ),
];
