// Public product archetypes (04 §4, ADR-010).
// AUTHORED public design knowledge — NOT extracted from ProKit.tsx / products/.
// Each archetype id equals a productType enum value (ontology.ts), excluding 'other'.
// Style ids referenced below are verified against src/data/styles.ts.

import { t } from './localization';
import type { ProductArchetype } from './types';

export const productArchetypes: ProductArchetype[] = [
  {
    id: 'operational-saas',
    name: t('Operational SaaS', '운영형 SaaS', '運用系SaaS'),
    description: t(
      'A working surface for operators who watch systems, respond to issues, and adjust settings all day.',
      '시스템을 지켜보고 문제에 대응하며 설정을 조정하는 운영자가 하루 종일 쓰는 작업 화면.',
      'システムを見張り、問題に対応し、設定を調整する運用担当者が一日中使う作業画面。',
    ),
    signals: ['ops dashboard', 'admin console', 'monitoring', 'control panel', 'internal tooling', 'team operations'],
    primaryTasks: ['monitor', 'triage', 'configure', 'manage', 'review'],
    commonScreens: ['dashboard', 'data-table', 'detail', 'form', 'settings'],
    recommendedPrimaryStyleIds: ['quiet-utility', 'platform-core', 'runtime-signal'],
    recommendedSecondaryStyleIds: ['notion-style', 'macos-liquid-glass'],
    avoidStyleIds: ['kinetic-pop', 'aurora-gradient', 'y2k-retro'],
    defaultDensity: 'high',
    defaultUsageFrequency: 'daily',
    defaultTrust: 'medium',
    stateSurfaceIds: ['data-table', 'form'],
  },
  {
    id: 'developer-tool',
    name: t('Developer tool', '개발자 도구', '開発者ツール'),
    description: t(
      'A precise, keyboard-friendly surface for engineers running commands, reading logs, and wiring up integrations.',
      '명령을 실행하고 로그를 읽으며 연동을 구성하는 엔지니어를 위한 정밀하고 키보드 친화적인 화면.',
      'コマンドを実行し、ログを読み、連携を組み立てるエンジニア向けの精密でキーボード重視の画面。',
    ),
    signals: ['cli', 'sdk', 'api client', 'developer console', 'integration setup', 'log viewer'],
    primaryTasks: ['configure', 'monitor', 'manage', 'analyze', 'read'],
    commonScreens: ['developer-console', 'data-table', 'documentation', 'settings', 'detail'],
    recommendedPrimaryStyleIds: ['terminal-core', 'runtime-signal', 'platform-core'],
    recommendedSecondaryStyleIds: ['console-launch', 'quiet-utility'],
    avoidStyleIds: ['soft-pastel', 'claymorphism', 'earth-atelier'],
    defaultDensity: 'high',
    defaultUsageFrequency: 'daily',
    defaultTrust: 'medium',
    stateSurfaceIds: ['developer-console', 'data-table'],
  },
  {
    id: 'documentation',
    name: t('Documentation', '문서/레퍼런스', 'ドキュメント'),
    description: t(
      'A reference surface built for reading and searching: clear hierarchy, comfortable measure, and findable structure.',
      '읽기와 검색에 맞춘 레퍼런스 화면. 또렷한 위계와 편안한 문장 폭, 찾기 쉬운 구조가 핵심.',
      '読むことと探すことに合わせたリファレンス画面。明快な階層、読みやすい行幅、見つけやすい構造が要。',
    ),
    signals: ['docs', 'api docs', 'reference', 'guide', 'manual', 'developer education'],
    primaryTasks: ['read', 'search', 'navigate', 'browse'],
    commonScreens: ['documentation', 'detail', 'landing', 'settings'],
    recommendedPrimaryStyleIds: ['mono-type', 'editorial-silence', 'fusion-editorial-terminal'],
    recommendedSecondaryStyleIds: ['notion-style', 'platform-core'],
    avoidStyleIds: ['cyberpunk-glitch', 'neon-drift'],
    defaultDensity: 'low',
    defaultUsageFrequency: 'occasional',
    defaultTrust: 'low',
    stateSurfaceIds: [],
  },
  {
    id: 'data-analytics',
    name: t('Data analytics', '데이터 분석', 'データ分析'),
    description: t(
      'A dense, scannable surface for reading metrics, comparing slices, and drilling into charts and tables.',
      '지표를 읽고 구간을 비교하며 차트와 표를 깊이 파고드는, 빽빽하고 훑어보기 쉬운 화면.',
      '指標を読み、断面を比較し、グラフと表を掘り下げる、密度が高く一覧しやすい画面。',
    ),
    signals: ['analytics', 'bi', 'reporting', 'metrics', 'charts', 'data viz'],
    primaryTasks: ['analyze', 'monitor', 'compare', 'review'],
    commonScreens: ['dashboard', 'data-table', 'detail', 'settings'],
    recommendedPrimaryStyleIds: ['runtime-signal', 'quiet-utility', 'platform-core'],
    recommendedSecondaryStyleIds: ['notion-style', 'macos-liquid-glass'],
    avoidStyleIds: ['kinetic-pop', 'holographic-fluid', 'soft-pastel'],
    defaultDensity: 'high',
    defaultUsageFrequency: 'daily',
    defaultTrust: 'medium',
    stateSurfaceIds: ['data-table'],
  },
  {
    id: 'security-console',
    name: t('Security console', '보안 콘솔', 'セキュリティコンソール'),
    description: t(
      'A high-stakes surface for watching threats, triaging alerts, and auditing access with clear evidence trails.',
      '위협을 감시하고 경보를 분류하며 접근 기록을 명확한 근거와 함께 감사하는, 책임이 무거운 화면.',
      '脅威を監視し、アラートを振り分け、明確な証跡とともにアクセスを監査する責任の重い画面。',
    ),
    signals: ['security', 'siem', 'threat', 'audit log', 'access control', 'incident response'],
    primaryTasks: ['monitor', 'triage', 'audit', 'analyze', 'review'],
    commonScreens: ['dashboard', 'data-table', 'detail', 'developer-console', 'settings'],
    recommendedPrimaryStyleIds: ['runtime-signal', 'quiet-utility', 'platform-core'],
    recommendedSecondaryStyleIds: ['terminal-core', 'fusion-pure-noir'],
    avoidStyleIds: ['soft-pastel', 'claymorphism', 'bento-bloom'],
    defaultDensity: 'high',
    defaultUsageFrequency: 'daily',
    defaultTrust: 'high',
    stateSurfaceIds: ['data-table', 'developer-console'],
  },
  {
    id: 'finance-admin',
    name: t('Finance admin', '금융/정산 관리', '金融管理'),
    description: t(
      'A trustworthy surface for ledgers, payments, and reconciliation where numbers must be exact and auditable.',
      '원장과 결제, 정산을 다루는 신뢰 중심 화면. 숫자는 정확하고 추적 가능해야 합니다.',
      '元帳・決済・照合を扱う信頼重視の画面。数字は正確で監査可能でなければなりません。',
    ),
    signals: ['finance', 'billing', 'ledger', 'payments admin', 'reconciliation', 'trading'],
    primaryTasks: ['review', 'audit', 'analyze', 'manage', 'monitor'],
    commonScreens: ['dashboard', 'data-table', 'detail', 'form', 'settings'],
    recommendedPrimaryStyleIds: ['quiet-utility', 'platform-core', 'fusion-pure-noir'],
    recommendedSecondaryStyleIds: ['runtime-signal', 'fusion-bento-noir'],
    avoidStyleIds: ['kinetic-pop', 'y2k-retro', 'soft-pastel'],
    defaultDensity: 'high',
    defaultUsageFrequency: 'daily',
    defaultTrust: 'high',
    stateSurfaceIds: ['data-table', 'form'],
  },
  {
    id: 'healthcare-portal',
    name: t('Healthcare portal', '헬스케어 포털', 'ヘルスケアポータル'),
    description: t(
      'A calm, careful surface for patients and clinicians to view records, schedule visits, and complete sensitive forms.',
      '환자와 의료진이 기록을 보고 진료를 예약하며 민감한 양식을 작성하는, 차분하고 신중한 화면.',
      '患者と医療者が記録を見て、受診を予約し、機微なフォームを記入する、落ち着いた慎重な画面。',
    ),
    signals: ['healthcare', 'medical', 'patient', 'clinical', 'ehr', 'appointment booking'],
    primaryTasks: ['read', 'schedule', 'review', 'communicate', 'manage'],
    commonScreens: ['dashboard', 'detail', 'form', 'settings', 'data-table'],
    recommendedPrimaryStyleIds: ['platform-core', 'quiet-utility', 'soft-pastel'],
    recommendedSecondaryStyleIds: ['notion-style', 'macos-liquid-glass'],
    avoidStyleIds: ['cyberpunk-glitch', 'neon-drift', 'y2k-retro'],
    defaultDensity: 'medium',
    defaultUsageFrequency: 'occasional',
    defaultTrust: 'high',
    stateSurfaceIds: ['form', 'data-table'],
  },
  {
    id: 'commerce',
    name: t('Commerce', '커머스/쇼핑', 'コマース'),
    description: t(
      'A shopping surface that helps people browse, compare, and check out with confidence and minimal friction.',
      '사람들이 자신 있게, 막힘 없이 둘러보고 비교하고 결제하도록 돕는 쇼핑 화면.',
      '人々が安心して滞りなく、見て、比べて、決済できるよう助けるショッピング画面。',
    ),
    signals: ['ecommerce', 'shop', 'store', 'cart', 'checkout', 'retail'],
    primaryTasks: ['browse', 'compare', 'purchase', 'checkout', 'search'],
    commonScreens: ['landing', 'detail', 'checkout', 'data-table', 'form'],
    recommendedPrimaryStyleIds: ['mesh-gradient', 'bento-bloom', 'macos-liquid-glass'],
    recommendedSecondaryStyleIds: ['midnight-noir', 'earth-atelier'],
    avoidStyleIds: ['terminal-core', 'runtime-signal'],
    defaultDensity: 'medium',
    defaultUsageFrequency: 'occasional',
    defaultTrust: 'high',
    stateSurfaceIds: ['checkout', 'form'],
  },
  {
    id: 'ai-chat',
    name: t('AI chat', 'AI 챗', 'AIチャット'),
    description: t(
      'A conversational surface where people send messages, read streamed replies, and steer an assistant in real time.',
      '사람들이 메시지를 보내고 흘러나오는 답변을 읽으며 어시스턴트를 실시간으로 이끄는 대화형 화면.',
      '人がメッセージを送り、流れてくる返答を読み、アシスタントをリアルタイムで導く対話画面。',
    ),
    signals: ['chat', 'assistant', 'conversational', 'llm', 'copilot', 'message thread'],
    primaryTasks: ['communicate', 'author', 'read', 'upload', 'search'],
    commonScreens: ['chat', 'detail', 'settings', 'landing'],
    recommendedPrimaryStyleIds: ['platform-core', 'mesh-gradient', 'framer-motion'],
    recommendedSecondaryStyleIds: ['holographic-fluid', 'quiet-utility'],
    avoidStyleIds: ['retro-pixel', 'y2k-retro', 'risograph-print'],
    defaultDensity: 'medium',
    defaultUsageFrequency: 'daily',
    defaultTrust: 'medium',
    stateSurfaceIds: ['chat'],
  },
  {
    id: 'content-editorial',
    name: t('Content / editorial', '콘텐츠/에디토리얼', 'コンテンツ/編集'),
    description: t(
      'A reading-first surface where typography, pacing, and imagery carry stories, articles, and long-form pieces.',
      '타이포그래피와 호흡, 이미지가 이야기와 기사, 긴 글을 이끄는 읽기 중심 화면.',
      'タイポグラフィ、間合い、画像が物語・記事・長文を運ぶ、読むことを軸にした画面。',
    ),
    signals: ['editorial', 'magazine', 'blog', 'news', 'publication', 'long-form'],
    primaryTasks: ['read', 'browse', 'author', 'navigate'],
    commonScreens: ['landing', 'detail', 'documentation'],
    recommendedPrimaryStyleIds: ['editorial-silence', 'zen-minimalism', 'fusion-grain-mono'],
    recommendedSecondaryStyleIds: ['mono-type', 'risograph-print'],
    avoidStyleIds: ['runtime-signal', 'terminal-core'],
    defaultDensity: 'low',
    defaultUsageFrequency: 'occasional',
    defaultTrust: 'low',
    stateSurfaceIds: [],
  },
  {
    id: 'knowledge-base',
    name: t('Knowledge base', '지식베이스', 'ナレッジベース'),
    description: t(
      'A help-and-reference surface where people search, read articles, and self-serve answers to their questions.',
      '사람들이 검색하고 글을 읽으며 스스로 답을 찾는 도움말·레퍼런스 화면.',
      '人が検索し、記事を読み、自分で答えにたどり着くヘルプ／リファレンス画面。',
    ),
    signals: ['kb', 'wiki', 'help center', 'faq', 'support docs', 'self-service'],
    primaryTasks: ['search', 'read', 'navigate', 'browse'],
    commonScreens: ['documentation', 'detail', 'landing', 'settings'],
    recommendedPrimaryStyleIds: ['notion-style', 'editorial-silence', 'mono-type'],
    recommendedSecondaryStyleIds: ['platform-core', 'quiet-utility'],
    avoidStyleIds: ['cyberpunk-glitch', 'neon-drift'],
    defaultDensity: 'medium',
    defaultUsageFrequency: 'occasional',
    defaultTrust: 'low',
    stateSurfaceIds: [],
  },
  {
    id: 'portfolio',
    name: t('Portfolio', '포트폴리오', 'ポートフォリオ'),
    description: t(
      'A showcase surface where a person or studio presents work with a strong point of view and memorable craft.',
      '개인이나 스튜디오가 분명한 관점과 기억에 남는 완성도로 작업을 선보이는 쇼케이스 화면.',
      '個人やスタジオが明確な視点と記憶に残る作り込みで作品を見せるショーケース画面。',
    ),
    signals: ['portfolio', 'showcase', 'personal site', 'studio site', 'agency', 'case study'],
    primaryTasks: ['browse', 'read', 'navigate'],
    commonScreens: ['landing', 'detail'],
    recommendedPrimaryStyleIds: ['zen-minimalism', 'fusion-studio-pixel', 'editorial-silence'],
    recommendedSecondaryStyleIds: ['fusion-quiet-manifesto', 'earth-atelier'],
    avoidStyleIds: ['quiet-utility', 'runtime-signal'],
    defaultDensity: 'low',
    defaultUsageFrequency: 'one-off',
    defaultTrust: 'low',
    stateSurfaceIds: [],
  },
  {
    id: 'campaign',
    name: t('Campaign / launch', '캠페인/런치', 'キャンペーン'),
    description: t(
      'A single-visit surface built to land a message fast: a launch, promo, or event page that converts on first impression.',
      '메시지를 빠르게 각인시키는 일회성 화면. 첫인상에서 전환을 끌어내는 런치·프로모·이벤트 페이지.',
      'メッセージを素早く届ける一回性の画面。第一印象で行動につなげるローンチ・プロモ・イベントページ。',
    ),
    signals: ['landing', 'launch', 'promo', 'event', 'marketing', 'product launch'],
    primaryTasks: ['browse', 'read', 'onboard', 'navigate'],
    commonScreens: ['landing', 'detail', 'form'],
    recommendedPrimaryStyleIds: ['kinetic-pop', 'framer-motion', 'fusion-strict-console'],
    recommendedSecondaryStyleIds: ['aurora-gradient', 'fusion-kinetic-brutal'],
    avoidStyleIds: ['quiet-utility', 'mono-type'],
    defaultDensity: 'low',
    defaultUsageFrequency: 'one-off',
    defaultTrust: 'low',
    stateSurfaceIds: ['form'],
  },
  {
    id: 'consumer-app',
    name: t('Consumer app', '소비자 앱', 'コンシューマーアプリ'),
    description: t(
      'A friendly everyday surface for a broad audience to do lightweight tasks, navigate, and come back often.',
      '폭넓은 사용자가 가벼운 작업을 하고 이동하며 자주 다시 찾는, 친근한 일상 화면.',
      '幅広い利用者が軽い操作をして移動し、何度も戻ってくる親しみやすい日常の画面。',
    ),
    signals: ['consumer', 'mobile app', 'social', 'lifestyle', 'b2c', 'everyday use'],
    primaryTasks: ['browse', 'navigate', 'communicate', 'onboard', 'manage'],
    commonScreens: ['dashboard', 'detail', 'form', 'settings', 'landing'],
    recommendedPrimaryStyleIds: ['bento-bloom', 'soft-pastel', 'mesh-gradient'],
    recommendedSecondaryStyleIds: ['claymorphism', 'macos-liquid-glass'],
    avoidStyleIds: ['terminal-core', 'runtime-signal', 'fusion-pure-noir'],
    defaultDensity: 'medium',
    defaultUsageFrequency: 'daily',
    defaultTrust: 'medium',
    stateSurfaceIds: ['form'],
  },
];
