import { t } from '../../localization';
import type { StateRecipe } from '../types';

export const dataTableRecipes: StateRecipe[] = [
  {
    id: 'initial-loading',
    surfaceIds: ['data-table'],
    category: 'data',
    criticality: 'required',
    name: t('Initial loading', '최초 로딩', '初回ロード'),
    summary: t(
      'The first fetch is in flight; the table has no rows yet and the outcome is unknown.',
      '첫 요청이 진행 중이고, 아직 행이 없으며 결과를 알 수 없는 상태.',
      '最初のリクエストが進行中で、まだ行が無く結果も不明な状態。'),
    aliases: ['loading', 'first load', 'fetching', 'skeleton', '로딩 중', '불러오는 중', '読み込み中', '取得中'],
    domainSignals: ['fetch', 'loading', 'table', 'list'],
    triggers: [
      t('The first request for table rows is in flight', '테이블 행에 대한 첫 요청이 진행 중', 'テーブル行の最初のリクエストが進行中'),
      t('No cached rows are available to show yet', '먼저 보여줄 캐시된 행이 아직 없음', 'まず表示できるキャッシュ行がまだ無い'),
    ],
    userQuestions: [
      t('Is this loading, or is it just empty and broken?',
        '로딩 중인 건가, 아니면 그냥 비어 있고 고장 난 건가?',
        '読み込み中なのか、それとも空で壊れているのか?'),
    ],
    mustShow: [
      t('A loading indicator that maps to the table layout (skeleton rows)',
        '테이블 레이아웃에 맞는 로딩 표시(스켈레톤 행)',
        'テーブルのレイアウトに沿ったローディング表示(スケルトン行)'),
      t('The column headers if they are already known',
        '이미 알고 있는 열 헤더',
        '既に分かっている列ヘッダー'),
    ],
    mustPreserve: [
      t('The current query and filters that triggered the load', '로딩을 부른 현재 검색어·필터', 'ロードを引き起こした現在の検索語・フィルター'),
      t('The reserved table area so layout does not jump', '레이아웃이 튀지 않도록 확보된 테이블 영역', 'レイアウトがずれないよう確保したテーブル領域'),
    ],
    primaryActions: [t('Wait for the result (no action required)', '결과를 기다림(별도 동작 불필요)', '結果を待つ(操作不要)')],
    secondaryActions: [t('Cancel the load', '로딩 취소', 'ロードをキャンセル')],
    mustNot: [
      t('Show an empty-state or error before the request resolves',
        '요청이 끝나기 전에 빈 상태·오류를 보여주기',
        'リクエスト完了前に空状態やエラーを表示する'),
      t('Block the whole page with a full-screen spinner for a single table',
        '테이블 하나 때문에 전체 화면 스피너로 페이지를 막기',
        'テーブル一つのために全画面スピナーでページ全体を塞ぐ'),
      t('Use a spinner with no layout while the row shape is already known',
        '행 모양을 아는데도 레이아웃 없는 스피너만 쓰기',
        '行の形が分かっているのにレイアウト無しのスピナーだけを使う'),
    ],
    accessibility: {
      announcement: t('Announce "loading" politely via aria-busy / aria-live=polite',
        'aria-busy / aria-live=polite로 "로딩 중"을 방해되지 않게 안내',
        'aria-busy / aria-live=politeで「読み込み中」を控えめに通知'),
      focus: t('Keep focus on the control that triggered the load', '로딩을 시작한 컨트롤에 포커스 유지', 'ロードを開始したコントロールにフォーカスを維持'),
    },
    motion: {
      guidance: [t('Calm skeleton shimmer in the row region only', '행 영역에만 차분한 스켈레톤 셔머', '行領域だけに落ち着いたスケルトンのシマー')],
      reducedMotion: [t('Show static placeholder rows with no shimmer', '셔머 없이 정적 플레이스홀더 행 표시', 'シマー無しで静的なプレースホルダー行を表示')],
    },
  },
  {
    id: 'populated',
    surfaceIds: ['data-table'],
    category: 'data',
    criticality: 'required',
    name: t('Populated', '데이터 있음', 'データあり'),
    summary: t(
      'The fetch succeeded and the table is showing one or more rows of real data.',
      '요청이 성공해 테이블에 실제 데이터가 한 행 이상 표시되는 상태.',
      'リクエストが成功し、テーブルに実データが1行以上表示されている状態。'),
    aliases: ['loaded', 'has data', 'results', 'rows', '데이터 표시', '결과 있음', '表示済み', '結果あり'],
    domainSignals: ['table', 'list', 'rows', 'results'],
    triggers: [
      t('A fetch returned one or more rows', '요청이 한 행 이상을 반환', 'リクエストが1行以上を返した'),
    ],
    userQuestions: [
      t('What is here, and how do I sort, filter, or act on these rows?',
        '여기 뭐가 있고, 어떻게 정렬·필터·작업하나?',
        'ここに何があり、どう並べ替え・絞り込み・操作するのか?'),
    ],
    mustShow: [
      t('The rows with readable column headers', '읽기 쉬운 열 헤더와 함께 행', '読みやすい列ヘッダーと共に行を'),
      t('Sort, filter, and pagination controls that reflect the current view',
        '현재 보기를 반영하는 정렬·필터·페이지네이션 컨트롤',
        '現在の表示を反映する並べ替え・絞り込み・ページネーションのコントロール'),
    ],
    mustPreserve: [
      t('The active sort, filters, and query', '적용 중인 정렬·필터·검색어', '適用中の並べ替え・フィルター・検索語'),
      t('The current scroll position and any row selection', '현재 스크롤 위치와 선택된 행', '現在のスクロール位置と選択中の行'),
    ],
    primaryActions: [t('Open or act on a row', '행 열기 또는 행에 대한 작업', '行を開く・行に対して操作')],
    secondaryActions: [
      t('Change sort or filters', '정렬·필터 변경', '並べ替え・フィルターを変更'),
      t('Go to the next page', '다음 페이지로 이동', '次のページへ'),
    ],
    mustNot: [
      t('Reset the scroll or selection when a background refresh arrives',
        '백그라운드 새로고침이 와도 스크롤·선택을 초기화하기',
        'バックグラウンド更新が来てもスクロール・選択をリセットする'),
      t('Shift rows under the pointer with late-loading content',
        '뒤늦게 로딩된 콘텐츠로 포인터 아래 행을 밀어내기',
        '遅れて読み込まれた内容でポインタ下の行をずらす'),
    ],
    accessibility: {
      announcement: t('Announce the row count after load politely',
        '로딩 후 행 수를 방해되지 않게 안내',
        'ロード後の行数を控えめに通知'),
      keyboard: [
        t('Allow arrow-key navigation across cells and rows', '셀·행 간 방향키 이동 허용', 'セル・行間を矢印キーで移動できるようにする'),
        t('Make sortable headers operable by keyboard', '정렬 가능한 헤더를 키보드로 조작 가능하게', 'ソート可能なヘッダーをキーボードで操作可能に'),
      ],
      contrast: [
        t('Keep row text and zebra striping above the contrast minimum', '행 텍스트와 줄무늬를 최소 대비 이상으로 유지', '行テキストとゼブラ縞を最小コントラスト以上に保つ'),
      ],
    },
    motion: {
      guidance: [t('Animate only newly inserted or reordered rows, briefly', '새로 삽입·재정렬된 행만 짧게 애니메이션', '新規挿入・並べ替えされた行だけを短くアニメーション')],
      reducedMotion: [t('Update rows in place with no transition', '전환 없이 행을 제자리에서 갱신', 'トランジション無しで行をその場で更新')],
    },
  },
  {
    id: 'initial-empty',
    surfaceIds: ['data-table'],
    category: 'content',
    criticality: 'required',
    name: t('Initial empty', '데이터 없음(최초)', 'データなし(初回)'),
    summary: t(
      'The fetch succeeded but there is genuinely no source data yet — nothing has been created.',
      '요청은 성공했지만 아직 원본 데이터가 진짜로 없는 상태 — 아무것도 생성된 적이 없음.',
      'リクエストは成功したが、元データがまだ本当に無い状態 — 何も作成されていない。'),
    aliases: ['empty', 'no data', 'first run', 'nothing yet', 'blank slate', '비어 있음', '아직 없음', '空', 'まだ無い'],
    domainSignals: ['empty', 'first-run', 'table', 'onboarding'],
    triggers: [
      t('A successful fetch returned zero rows with no active filters', '필터 없이 성공한 요청이 0건을 반환', 'フィルター無しで成功したリクエストが0件を返した'),
      t('No record has ever been created for this view', '이 보기에 대해 생성된 레코드가 한 번도 없음', 'この表示に対するレコードが一度も作成されていない'),
    ],
    userQuestions: [
      t('Did something fail, or is this just new and waiting for my first entry?',
        '뭔가 실패한 건가, 아니면 그냥 새 거라 내 첫 입력을 기다리는 건가?',
        '何か失敗したのか、それとも新しくて最初の入力を待っているだけなのか?'),
    ],
    mustShow: [
      t('A friendly explanation that this view is empty because nothing exists yet',
        '아직 아무것도 없어서 비었다는 친절한 설명',
        'まだ何も無いため空である、という分かりやすい説明'),
      t('A clear way to create the first record', '첫 레코드를 만드는 분명한 경로', '最初のレコードを作る明確な導線'),
    ],
    mustPreserve: [
      t('The surrounding navigation and any column configuration', '주변 내비게이션과 열 구성', '周辺のナビゲーションと列の構成'),
    ],
    primaryActions: [t('Create the first record', '첫 레코드 만들기', '最初のレコードを作成')],
    secondaryActions: [
      t('Import existing data', '기존 데이터 가져오기', '既存データを取り込む'),
      t('Learn how this view works', '이 보기 사용법 보기', 'この表示の使い方を見る'),
    ],
    mustNot: [
      t('Present the empty state as an error or failure',
        '빈 상태를 오류·실패처럼 표현하기',
        '空状態をエラーや失敗のように見せる'),
      t('Show a clear-filters action when no filters are active',
        '필터가 없는데 필터 지우기 동작을 보여주기',
        'フィルターが無いのにフィルター解除の操作を出す'),
      t('Leave a bare blank area with no guidance on what to do next',
        '다음에 무엇을 할지 안내 없이 빈 영역만 남기기',
        '次に何をすべきか案内せず空白だけを残す'),
    ],
    accessibility: {
      announcement: t('Announce the empty result politely, not as an alert',
        '빈 결과를 경보가 아니라 방해되지 않게 안내',
        '空の結果をアラートではなく控えめに通知'),
      focus: t('Move focus to the create-first-record action', '첫 레코드 만들기 동작으로 포커스 이동', '最初のレコード作成のアクションへフォーカスを移す'),
    },
    motion: {
      guidance: [t('Gently fade in the empty-state illustration and copy', '빈 상태 일러스트와 문구를 부드럽게 페이드 인', '空状態のイラストと文言を穏やかにフェードイン')],
      reducedMotion: [t('Show the empty-state content immediately, no fade', '페이드 없이 빈 상태 콘텐츠를 즉시 표시', 'フェード無しで空状態の内容を即時表示')],
    },
  },
  {
    id: 'filtered-empty',
    surfaceIds: ['data-table'],
    category: 'content',
    criticality: 'required',
    name: t('Filtered empty', '필터 결과 없음', 'フィルター結果なし'),
    summary: t(
      'Source data exists, but the active query or filters match nothing.',
      '원본 데이터는 있지만 현재 검색어·필터에 일치하는 항목이 없는 상태.',
      '元データはあるが、現在の検索条件・フィルターに一致する項目がない状態。'),
    aliases: ['no matches', 'zero results', 'empty after filter', '검색 결과 없음', '필터 비었음', '該当なし', '0件'],
    domainSignals: ['filter', 'search', 'query'],
    triggers: [
      t('Source data may exist', '원본 데이터는 존재할 수 있음', '元データは存在しうる'),
      t('Active query or filters produce zero matches', '현재 검색어·필터가 0건을 만듦', '現在の検索・フィルターが0件を返す'),
    ],
    userQuestions: [
      t('Is there no data at all, or are my filters too narrow?',
        '데이터가 아예 없는 건가, 아니면 필터가 너무 좁은 건가?',
        'データが全く無いのか、フィルターが狭すぎるのか?'),
    ],
    mustShow: [
      t('A clear "no matching results" explanation', '“일치하는 결과 없음”을 분명히 설명', '「該当する結果なし」と明確に説明'),
      t('The active query and filters', '현재 적용된 검색어·필터', '適用中の検索語・フィルター'),
      t('A clear-filters action', '필터 지우기 동작', 'フィルター解除の操作'),
    ],
    mustPreserve: [
      t('The current query', '현재 검색어', '現在の検索語'),
      t('The current filters', '현재 필터', '現在のフィルター'),
      t('Surrounding navigation', '주변 내비게이션', '周辺のナビゲーション'),
    ],
    primaryActions: [t('Clear filters', '필터 지우기', 'フィルターを解除')],
    secondaryActions: [t('Edit the query', '검색어 수정', '検索語を編集')],
    mustNot: [
      t('Show first-use onboarding copy', '최초 사용 온보딩 문구를 보여주기', '初回オンボーディング文言を表示'),
      t('Make "create new" the default action', '“새로 만들기”를 기본 동작으로', '「新規作成」を既定操作にする'),
      t('Hide the cause of zero results', '0건의 원인을 숨기기', '0件の原因を隠す'),
    ],
    accessibility: {
      announcement: t('Announce the updated result count politely',
        '갱신된 결과 수를 방해되지 않게 안내', '更新後の件数を控えめに通知'),
      focus: t('Keep focus on the query controls', '포커스를 검색 컨트롤에 유지', 'フォーカスを検索コントロールに維持'),
    },
    motion: {
      guidance: [t('Briefly replace the result region only', '결과 영역만 짧게 교체', '結果領域だけ短く差し替え')],
      reducedMotion: [t('Swap content with no transition', '전환 없이 콘텐츠만 교체', 'トランジション無しで差し替え')],
    },
  },
  {
    id: 'fetch-failed',
    surfaceIds: ['data-table'],
    category: 'network',
    criticality: 'required',
    name: t('Fetch failed', '불러오기 실패', '取得失敗'),
    summary: t(
      'The request to load rows failed (network, timeout, or server error) so the table could not render.',
      '행을 불러오는 요청이 네트워크·타임아웃·서버 오류로 실패해 테이블을 표시하지 못한 상태.',
      '行を読み込むリクエストがネットワーク・タイムアウト・サーバーエラーで失敗し、テーブルを表示できなかった状態。'),
    aliases: ['load error', 'request failed', 'network error', 'timeout', '로딩 실패', '요청 실패', '読み込みエラー', '通信失敗'],
    domainSignals: ['error', 'network', 'timeout', 'fetch'],
    triggers: [
      t('The fetch returned a network error, timeout, or 5xx response', '요청이 네트워크 오류·타임아웃·5xx 응답을 반환', 'リクエストがネットワークエラー・タイムアウト・5xx応答を返した'),
    ],
    userQuestions: [
      t('Is this my connection or the server, and can I just try again?',
        '내 연결 문제인가 서버 문제인가, 그냥 다시 시도하면 되나?',
        '自分の接続の問題かサーバーの問題か、もう一度試せば良いのか?'),
    ],
    mustShow: [
      t('A plain-language explanation that loading failed', '불러오기에 실패했다는 쉬운 설명', '読み込みに失敗したことを平易に説明'),
      t('A manual retry action', '수동 재시도 동작', '手動の再試行操作'),
    ],
    mustPreserve: [
      t('The current query and filters so retry repeats the same request', '재시도가 같은 요청을 반복하도록 현재 검색어·필터', '再試行が同じ要求を繰り返せるよう現在の検索語・フィルター'),
      t('Any rows already shown from a previous successful load', '이전에 성공적으로 표시된 기존 행', '以前に成功して表示済みの既存行'),
    ],
    primaryActions: [t('Retry the request', '다시 시도', '再試行')],
    secondaryActions: [
      t('View error details', '오류 상세 보기', 'エラー詳細を表示'),
      t('Report the problem', '문제 신고', '問題を報告'),
    ],
    mustNot: [
      t('Silently auto-retry in a loop without telling the user',
        '사용자에게 알리지 않고 조용히 반복 자동 재시도하기',
        'ユーザーに知らせず黙ってループ自動再試行する'),
      t('Replace already-loaded rows with a blank error screen',
        '이미 불러온 행을 빈 오류 화면으로 덮어쓰기',
        '既に読み込んだ行を空のエラー画面で上書きする'),
      t('Show raw stack traces or status codes as the primary message',
        '원시 스택트레이스·상태 코드를 주된 메시지로 보여주기',
        '生のスタックトレースやステータスコードを主メッセージにする'),
    ],
    accessibility: {
      announcement: t('Announce the failure assertively via role=alert',
        '실패를 role=alert로 즉시·강조해서 안내',
        '失敗をrole=alertで即時・強調して通知'),
      focus: t('Move focus to the error message and its retry action', '포커스를 오류 메시지와 재시도 동작으로 이동', 'フォーカスをエラーメッセージと再試行操作へ'),
    },
    motion: {
      guidance: [t('Reveal the error calmly; no shaking or flashing', '오류를 차분히 표시, 흔들림·깜빡임 금지', 'エラーを落ち着いて表示、揺れ・点滅は禁止')],
      reducedMotion: [t('Show the error immediately with no animation', '애니메이션 없이 오류 즉시 표시', 'アニメーション無しでエラーを即時表示')],
    },
  },
  {
    id: 'partial-data',
    surfaceIds: ['data-table'],
    category: 'data',
    criticality: 'recommended',
    name: t('Partial data', '일부 데이터', '一部データ'),
    summary: t(
      'Some rows or fields loaded, but part of the dataset is missing or failed to resolve.',
      '일부 행·필드는 로딩됐지만 데이터의 일부가 누락되거나 가져오지 못한 상태.',
      '一部の行・項目は読み込めたが、データの一部が欠落または取得できなかった状態。'),
    aliases: ['partial load', 'incomplete', 'some rows missing', 'degraded', '부분 로딩', '일부 누락', '部分的', '一部欠落'],
    domainSignals: ['partial', 'incomplete', 'degraded', 'table'],
    triggers: [
      t('One source or page succeeded while another failed or timed out', '한 소스·페이지는 성공하고 다른 쪽은 실패·타임아웃', '一方のソース・ページは成功し、他方が失敗・タイムアウトした'),
      t('Some cells could not be resolved (e.g. a joined field)', '일부 셀(예: 조인 필드)을 가져오지 못함', '一部のセル(例: 結合項目)を取得できなかった'),
    ],
    userQuestions: [
      t('Can I trust what I see, or is part of this table missing?',
        '지금 보이는 걸 믿어도 되나, 아니면 일부가 빠진 건가?',
        '今見えているものを信じてよいのか、一部が欠けているのか?'),
    ],
    mustShow: [
      t('The rows that did load', '불러온 행', '読み込めた行'),
      t('A clear indicator that the data is incomplete and which part is missing',
        '데이터가 불완전하다는 것과 어느 부분이 빠졌는지 분명한 표시',
        'データが不完全であることと、どの部分が欠けているかの明確な表示'),
    ],
    mustPreserve: [
      t('The successfully loaded rows and the current sort, filters, and scroll', '성공적으로 불러온 행과 현재 정렬·필터·스크롤', '読み込み済みの行と現在の並べ替え・フィルター・スクロール'),
    ],
    primaryActions: [t('Retry the failed portion only', '실패한 부분만 다시 시도', '失敗した部分のみ再試行')],
    secondaryActions: [t('See what is missing', '누락된 항목 보기', '欠落している項目を表示')],
    mustNot: [
      t('Present partial results as if the dataset were complete',
        '부분 결과를 완전한 데이터인 것처럼 보여주기',
        '部分的な結果を完全なデータのように見せる'),
      t('Discard the rows that did load just because the rest failed',
        '나머지가 실패했다고 이미 불러온 행을 버리기',
        '残りが失敗したからと読み込み済みの行を破棄する'),
      t('Compute totals or summaries silently from incomplete data',
        '불완전한 데이터로 합계·요약을 조용히 계산하기',
        '不完全なデータで合計・集計を黙って算出する'),
    ],
    accessibility: {
      announcement: t('Announce that results are partial politely, not as an error',
        '결과가 일부임을 오류가 아니라 방해되지 않게 안내',
        '結果が一部であることをエラーではなく控えめに通知'),
    },
    motion: {
      guidance: [t('Mark incomplete regions statically; no looping warning pulse', '불완전한 영역을 정적으로 표시, 반복 경고 펄스 금지', '不完全な領域を静的に表示、繰り返す警告パルス禁止')],
      reducedMotion: [t('Use a static badge or note instead of any pulse', '펄스 대신 정적 배지·메모 사용', 'パルスの代わりに静的なバッジ・注記を使う')],
    },
  },
  {
    id: 'stale-data',
    surfaceIds: ['data-table'],
    category: 'time',
    criticality: 'recommended',
    name: t('Stale data', '오래된 데이터', '古いデータ'),
    summary: t(
      'The displayed rows are known to be out of date; newer data exists upstream but has not been pulled in.',
      '표시 중인 행이 최신이 아님이 확인된 상태 — 더 새로운 데이터가 있지만 아직 반영되지 않음.',
      '表示中の行が最新でないと分かっている状態 — より新しいデータがあるが、まだ反映されていない。'),
    aliases: ['outdated', 'cached', 'refresh available', 'out of sync', '구버전', '갱신 필요', '古い', '更新あり'],
    domainSignals: ['stale', 'cache', 'refresh', 'updated-at'],
    triggers: [
      t('The data age exceeds its freshness window', '데이터 나이가 신선도 기준을 초과', 'データの経過時間が鮮度の基準を超えた'),
      t('An update event or version signal arrived for the current view', '현재 보기에 대한 갱신 이벤트·버전 신호가 도착', '現在の表示に対する更新イベント・バージョン信号が届いた'),
    ],
    userQuestions: [
      t('How old is this, and do I need to refresh before I act on it?',
        '이건 얼마나 오래된 거고, 작업 전에 새로고침해야 하나?',
        'これはどのくらい古く、操作する前に更新が必要か?'),
    ],
    mustShow: [
      t('When the data was last updated', '데이터가 마지막으로 갱신된 시점', 'データが最後に更新された時点'),
      t('A non-intrusive notice that newer data is available', '더 새로운 데이터가 있다는 방해되지 않는 알림', 'より新しいデータがある旨の邪魔にならない通知'),
    ],
    mustPreserve: [
      t('The current scroll position, sort, filters, and row selection', '현재 스크롤 위치·정렬·필터·행 선택', '現在のスクロール位置・並べ替え・フィルター・行選択'),
    ],
    primaryActions: [t('Refresh on demand', '사용자가 직접 새로고침', 'ユーザー操作で更新')],
    secondaryActions: [t('Keep the current view', '현재 보기 유지', '現在の表示を維持')],
    mustNot: [
      t('Auto-refresh and reset the scroll position out from under the user',
        '자동 새로고침으로 사용자의 스크롤 위치를 초기화하기',
        '自動更新でユーザーのスクロール位置をリセットする'),
      t('Discard unsaved row selection when refreshing', '새로고침 시 저장 안 된 행 선택을 버리기', '更新時に未保存の行選択を破棄する'),
      t('Show stale rows with no indication that they are out of date',
        '오래됐다는 표시 없이 낡은 행을 그대로 보여주기',
        '古いという表示無しに古い行をそのまま見せる'),
    ],
    accessibility: {
      announcement: t('Announce that an update is available politely; do not steal focus',
        '갱신 가능 알림을 방해되지 않게 안내하되 포커스를 빼앗지 않기',
        '更新があることを控えめに通知し、フォーカスを奪わない'),
    },
    motion: {
      guidance: [t('Show a quiet, persistent refresh affordance; no auto-swap animation', '조용하고 지속적인 새로고침 어포던스, 자동 교체 애니메이션 금지', '静かで持続的な更新アフォーダンス、自動差し替えアニメ禁止')],
      reducedMotion: [t('Use a static "updated data available" label', '정적 "갱신 가능" 라벨 사용', '静的な「更新あり」ラベルを使う')],
    },
  },
  {
    id: 'loading-next-page',
    surfaceIds: ['data-table'],
    category: 'data',
    criticality: 'recommended',
    name: t('Loading next page', '다음 페이지 로딩', '次ページ読み込み'),
    summary: t(
      'Existing rows are already shown and the next page or scroll batch is being fetched and appended.',
      '기존 행은 이미 보이는 상태에서 다음 페이지·스크롤 배치를 가져와 이어 붙이는 중인 상태.',
      '既存の行が表示された状態で、次ページ・スクロールのバッチを取得して追加している状態。'),
    aliases: ['pagination', 'load more', 'infinite scroll', 'next page', 'append', '더 보기', '페이지 추가', '追加読み込み', 'もっと見る'],
    domainSignals: ['pagination', 'infinite-scroll', 'load-more', 'table'],
    triggers: [
      t('The user scrolled near the end or pressed "load more"', '사용자가 끝 근처로 스크롤하거나 "더 보기"를 누름', 'ユーザーが末尾付近までスクロール、または「もっと見る」を押した'),
      t('The next page request is in flight while current rows stay visible', '현재 행은 유지된 채 다음 페이지 요청이 진행 중', '現在の行を保ったまま次ページのリクエストが進行中'),
    ],
    userQuestions: [
      t('Is more loading, or have I reached the bottom?',
        '더 불러오는 중인가, 아니면 끝까지 온 건가?',
        'もっと読み込み中か、それとも一番下まで来たのか?'),
    ],
    mustShow: [
      t('The already-loaded rows, kept in place', '이미 불러온 행을 그대로 유지', '既に読み込んだ行をそのまま維持'),
      t('A loading indicator at the point where new rows will append', '새 행이 추가될 위치에 로딩 표시', '新しい行が追加される位置にローディング表示'),
    ],
    mustPreserve: [
      t('The current scroll position so appended rows do not jump the viewport', '추가된 행이 화면을 튀게 하지 않도록 현재 스크롤 위치', '追加行が画面をずらさないよう現在のスクロール位置'),
      t('The active sort, filters, and row selection', '적용 중인 정렬·필터·행 선택', '適用中の並べ替え・フィルター・行選択'),
    ],
    primaryActions: [t('Wait for the next page to append', '다음 페이지가 추가되길 기다림', '次ページの追加を待つ')],
    secondaryActions: [t('Cancel loading more', '추가 로딩 취소', '追加読み込みをキャンセル')],
    mustNot: [
      t('Re-render the whole table and lose the scroll position',
        '테이블 전체를 다시 그려 스크롤 위치를 잃기',
        'テーブル全体を再描画してスクロール位置を失う'),
      t('Replace existing rows with a full-page loading state',
        '기존 행을 전체 페이지 로딩 상태로 덮어쓰기',
        '既存の行を全画面ローディング状態で上書きする'),
      t('Fire duplicate page requests on every scroll tick',
        '스크롤마다 중복된 페이지 요청을 쏘기',
        'スクロールのたびに重複したページ要求を投げる'),
    ],
    accessibility: {
      announcement: t('Announce that more rows are loading politely', '추가 행 로딩을 방해되지 않게 안내', '行を追加読み込み中であることを控えめに通知'),
      focus: t('Keep focus where it was; do not jump to the new rows', '포커스를 원위치에 유지, 새 행으로 이동하지 않기', 'フォーカスを元の位置に保ち、新しい行へ移さない'),
    },
    motion: {
      guidance: [t('Show a small spinner at the append point only', '추가 지점에만 작은 스피너 표시', '追加位置だけに小さなスピナーを表示')],
      reducedMotion: [t('Use a static "loading more" label instead of a spinner', '스피너 대신 정적 "더 불러오는 중" 라벨 사용', 'スピナーの代わりに静的な「読み込み中」ラベルを使う')],
    },
  },
  {
    id: 'end-of-results',
    surfaceIds: ['data-table'],
    category: 'content',
    criticality: 'recommended',
    name: t('End of results', '결과 끝', '結果の末尾'),
    summary: t(
      'All available rows have been loaded; there is no further page to fetch.',
      '사용 가능한 모든 행을 불러왔고 더 가져올 페이지가 없는 상태.',
      '利用可能な全ての行を読み込み、これ以上取得するページが無い状態。'),
    aliases: ['no more results', 'last page', 'all loaded', 'bottom', '마지막 페이지', '더 없음', '最後', '以上'],
    domainSignals: ['end', 'last-page', 'pagination', 'table'],
    triggers: [
      t('The last page returned and no next-page cursor remains', '마지막 페이지가 반환되고 다음 커서가 없음', '最後のページが返り、次のカーソルが無い'),
      t('The user scrolled or paged to the end of the dataset', '사용자가 데이터 끝까지 스크롤·페이지 이동', 'ユーザーがデータの末尾までスクロール・移動した'),
    ],
    userQuestions: [
      t('Is this really everything, or did loading stop early?',
        '이게 정말 전부인가, 아니면 로딩이 일찍 멈춘 건가?',
        'これが本当に全部か、それとも読み込みが途中で止まったのか?'),
    ],
    mustShow: [
      t('A clear "you have reached the end" marker', '“끝까지 봤습니다”라는 분명한 표시', '「末尾に到達しました」という明確な表示'),
      t('The total count loaded, when it is known', '알 수 있으면 불러온 전체 개수', '分かる場合は読み込んだ総数'),
    ],
    mustPreserve: [
      t('The current scroll position, sort, and filters', '현재 스크롤 위치·정렬·필터', '現在のスクロール位置・並べ替え・フィルター'),
    ],
    primaryActions: [t('Stop (no further loading)', '멈춤(추가 로딩 없음)', '停止(これ以上読み込まない)')],
    secondaryActions: [
      t('Scroll back to top', '맨 위로 이동', '一番上へ戻る'),
      t('Refine filters to find more', '필터를 조정해 더 찾기', 'フィルターを調整して探す'),
    ],
    mustNot: [
      t('Keep showing a loading spinner as if more rows are coming',
        '더 올 것처럼 로딩 스피너를 계속 보여주기',
        'まだ来るかのようにローディングスピナーを出し続ける'),
      t('Keep firing fetch requests against an exhausted cursor',
        '소진된 커서로 계속 요청을 보내기',
        '尽きたカーソルに対してリクエストを送り続ける'),
    ],
    accessibility: {
      announcement: t('Announce that the end of the list was reached politely', '목록 끝에 도달했음을 방해되지 않게 안내', 'リストの末尾に達したことを控えめに通知'),
    },
    motion: {
      guidance: [t('Show the end marker statically; no spinner', '끝 표시를 정적으로 노출, 스피너 없음', '末尾表示を静的に出す、スピナー無し')],
      reducedMotion: [t('Display the end marker immediately with no fade', '페이드 없이 끝 표시를 즉시 노출', 'フェード無しで末尾表示を即時に出す')],
    },
  },
  {
    id: 'permission-denied',
    surfaceIds: ['data-table'],
    category: 'permission',
    criticality: 'domain-specific',
    name: t('Permission denied', '권한 없음', '権限なし'),
    summary: t(
      'The user is authenticated but lacks permission to view this table or some of its rows.',
      '사용자는 인증됐지만 이 테이블 또는 일부 행을 볼 권한이 없는 상태.',
      'ユーザーは認証済みだが、このテーブルまたは一部の行を閲覧する権限が無い状態。'),
    aliases: ['no access', 'restricted', 'not authorized', '403', '권한 거부', '접근 제한', 'アクセス不可', '権限不足'],
    domainSignals: ['permission', 'role', 'scope', 'access'],
    triggers: [
      t('The authenticated user lacks the role or scope to read this view', '인증된 사용자가 이 보기를 읽을 role·scope 미보유', '認証済みユーザーがこの表示を読むrole・scopeを持たない'),
      t('Row-level access rules hide part of the dataset', '행 단위 접근 규칙이 데이터 일부를 가림', '行レベルのアクセス規則がデータの一部を隠す'),
    ],
    userQuestions: [
      t('Is my login wrong, or do I just not have access to this?',
        '로그인이 잘못된 건가, 아니면 그냥 접근 권한이 없는 건가?',
        'ログインが間違っているのか、単にアクセス権が無いのか?'),
    ],
    mustShow: [
      t('That authentication succeeded but permission is missing', '인증은 됐지만 권한이 없음을', '認証は成功したが権限が無いことを'),
      t('Which access or role is required and how to request it', '필요한 접근·role과 요청 방법', '必要なアクセス・roleと申請方法'),
    ],
    mustPreserve: [
      t('The surrounding navigation and the view the user attempted to open', '주변 내비게이션과 사용자가 열려던 보기', '周辺のナビゲーションとユーザーが開こうとした表示'),
    ],
    primaryActions: [t('Request access', '권한 요청', 'アクセスを申請')],
    secondaryActions: [t('Switch account or role', '계정·역할 전환', 'アカウント・ロールを切替')],
    mustNot: [
      t('Show a login screen when the user is already authenticated',
        '이미 인증된 사용자에게 로그인 화면을 띄우기',
        '既に認証済みのユーザーにログイン画面を出す'),
      t('Reveal the existence or contents of restricted rows in the error',
        '오류로 제한된 행의 존재·내용을 노출하기',
        'エラーで制限された行の存在・内容を露出する'),
      t('Present a recoverable retry as if it were a transient failure',
        '복구 불가능한 상태를 일시적 실패처럼 재시도시키기',
        '回復不能な状態を一時的失敗のように再試行させる'),
    ],
    accessibility: {
      announcement: t('Announce the restriction assertively without trapping focus', '제한을 포커스를 가두지 않고 단호하게 안내', '制限をフォーカスを閉じ込めずはっきりと通知'),
      focus: t('Move focus to the access-request explanation', '포커스를 권한 요청 안내로 이동', 'フォーカスをアクセス申請の説明へ移す'),
    },
    motion: {
      guidance: [t('Static, informational presentation; no alarm animation', '정적·정보 전달 표시, 경보 애니메이션 금지', '静的・情報提示の表示、警報アニメ禁止')],
      reducedMotion: [t('No motion needed', '모션 불필요', 'モーション不要')],
    },
  },
  {
    id: 'rate-limited',
    surfaceIds: ['data-table'],
    category: 'network',
    criticality: 'domain-specific',
    name: t('Rate limited', '요청 제한', 'レート制限'),
    summary: t(
      'The backend rejected the request because too many were sent in a short window (429); the table is throttled.',
      '짧은 시간에 너무 많은 요청이 몰려 백엔드가 거절한 상태(429) — 테이블이 일시적으로 제한됨.',
      '短時間に要求が多すぎてバックエンドが拒否した状態(429) — テーブルが一時的に制限されている。'),
    aliases: ['429', 'too many requests', 'throttled', 'quota exceeded', 'slow down', '요청 과다', '제한 초과', 'リクエスト過多', '制限超過'],
    domainSignals: ['rate-limit', '429', 'throttle', 'quota'],
    triggers: [
      t('The server returned 429 / Retry-After for the table request', '서버가 테이블 요청에 429 / Retry-After를 반환', 'サーバーがテーブル要求に429 / Retry-Afterを返した'),
      t('The request quota for this view was exceeded', '이 보기의 요청 쿼터를 초과', 'この表示のリクエストクォータを超過した'),
    ],
    userQuestions: [
      t('Did I break something, or do I just need to wait a moment?',
        '내가 뭘 잘못한 건가, 아니면 잠깐 기다리면 되나?',
        '何か壊したのか、それとも少し待てば良いのか?'),
    ],
    mustShow: [
      t('That the request was throttled, not failed by error', '오류로 실패한 게 아니라 요청이 제한됐음을', 'エラーで失敗ではなく要求が制限されたことを'),
      t('How long to wait before retrying, from Retry-After', 'Retry-After 기준으로 재시도까지 대기 시간', 'Retry-Afterに基づく再試行までの待ち時間'),
    ],
    mustPreserve: [
      t('The current query, filters, and any already-loaded rows', '현재 검색어·필터와 이미 불러온 행', '現在の検索語・フィルターと読み込み済みの行'),
    ],
    primaryActions: [t('Wait, then retry when the cooldown ends', '대기 후 쿨다운이 끝나면 재시도', '待機し、クールダウン終了後に再試行')],
    secondaryActions: [t('Slow down auto-refresh or polling', '자동 새로고침·폴링 간격을 늘리기', '自動更新・ポーリングの間隔を広げる')],
    mustNot: [
      t('Immediately auto-retry and make the rate limit worse',
        '즉시 자동 재시도해 제한을 더 악화시키기',
        '即座に自動再試行して制限を悪化させる'),
      t('Hide the wait time and let the user retry blindly',
        '대기 시간을 숨기고 사용자가 무작정 재시도하게 두기',
        '待ち時間を隠してユーザーに当てずっぽうで再試行させる'),
      t('Treat 429 as a hard error and discard loaded rows',
        '429를 치명적 오류로 취급해 불러온 행을 버리기',
        '429を致命的エラー扱いして読み込み済みの行を破棄する'),
    ],
    accessibility: {
      announcement: t('Announce the throttling politely with the wait time, not as an alarm',
        '제한 상태를 대기 시간과 함께 경보가 아닌 방해되지 않게 안내',
        '制限状態を待ち時間と共にアラームではなく控えめに通知'),
    },
    motion: {
      guidance: [t('Show a quiet countdown to the next allowed retry; no flashing', '다음 재시도까지 조용한 카운트다운, 깜빡임 금지', '次の再試行までの静かなカウントダウン、点滅禁止')],
      reducedMotion: [t('Show the remaining wait time as static text', '남은 대기 시간을 정적 텍스트로 표시', '残りの待ち時間を静的テキストで表示')],
    },
  },
];
