// v0.1 State Atlas recipes for the `developer-console` surface (06 §2.5).
// required → recommended → domain-specific (06 §6). `forbidden` is the worked
// recipe from 06 §4.3 and is used verbatim. unauthorized(401) vs forbidden(403):
// unauthorized's primary action is sign-in/auth; forbidden's is request-access and
// must NOT show a login screen (06 §5).

import { t } from '../../localization';
import type { StateRecipe } from '../types';

export const developerConsoleRecipes: StateRecipe[] = [
  {
    id: 'no-project',
    surfaceIds: ['developer-console'],
    category: 'content',
    criticality: 'required',
    name: t('No project selected', '선택된 프로젝트 없음', 'プロジェクト未選択'),
    summary: t(
      'The console loaded but no project, app, or workspace is selected to scope requests against.',
      '콘솔은 열렸지만 요청 대상이 될 프로젝트·앱·워크스페이스가 아직 선택되지 않은 상태.',
      'コンソールは開いたが、リクエストの対象となるプロジェクト・アプリ・ワークスペースが未選択の状態。'),
    aliases: ['no project', 'empty workspace', 'select a project', 'no app selected', '프로젝트 없음', '워크스페이스 비었음', 'プロジェクトなし', 'ワークスペース未選択'],
    domainSignals: ['project', 'workspace', 'app', 'scope'],
    triggers: [
      t('The account has no project yet, or none is selected',
        '계정에 프로젝트가 아직 없거나 선택되지 않음',
        'アカウントにプロジェクトが無いか、未選択である'),
      t('A previously selected project was deleted or revoked',
        '이전에 선택한 프로젝트가 삭제·회수됨',
        '以前選択したプロジェクトが削除・取消された'),
    ],
    userQuestions: [
      t('Which project am I working in, and how do I pick or create one?',
        '나는 지금 어떤 프로젝트에서 작업하나? 어떻게 고르거나 만드나?',
        '今どのプロジェクトで作業している?どう選ぶか作るのか?'),
    ],
    mustShow: [
      t('That a project must be selected before any request runs',
        '요청을 보내려면 먼저 프로젝트를 선택해야 함',
        'リクエストの前にプロジェクト選択が必要なこと'),
      t('A way to pick an existing project or create a first one',
        '기존 프로젝트 선택 또는 첫 프로젝트 생성 경로',
        '既存プロジェクトの選択、または最初の作成導線'),
    ],
    mustPreserve: [
      t('Any draft request, parameters, and body the user already typed',
        '사용자가 이미 입력한 요청 초안·파라미터·본문',
        'すでに入力したリクエスト下書き・パラメータ・本文'),
      t('The console layout, panels, and theme',
        '콘솔 레이아웃·패널·테마',
        'コンソールのレイアウト・パネル・テーマ'),
    ],
    primaryActions: [ t('Select a project', '프로젝트 선택', 'プロジェクトを選択') ],
    secondaryActions: [ t('Create a new project', '새 프로젝트 만들기', '新規プロジェクトを作成') ],
    mustNot: [
      t('Run requests against a guessed or default project silently',
        '추정하거나 기본값인 프로젝트로 조용히 요청을 보내기',
        '推測や既定のプロジェクトで黙ってリクエストを実行する'),
      t('Treat the empty state as an error or failure',
        '빈 상태를 오류·실패처럼 표시하기',
        '空の状態をエラー・失敗として表示する'),
    ],
    accessibility: {
      announcement: t('Announce that a project is required, politely',
        '프로젝트 선택이 필요함을 방해되지 않게 안내',
        'プロジェクト選択が必要なことを控えめに通知'),
      focus: t('Move focus to the project picker', '포커스를 프로젝트 선택기로 이동', 'フォーカスをプロジェクト選択へ移動'),
    },
    motion: {
      guidance: [ t('Static empty state; no spinner or alarm', '정적 빈 상태, 스피너·경보 없음', '静的な空状態、スピナー・警報なし') ],
      reducedMotion: [ t('Show the picker immediately, no transition', '전환 없이 선택기를 즉시 표시', 'トランジション無しで選択UIを即時表示') ],
    },
  },
  {
    id: 'request-running',
    surfaceIds: ['developer-console'],
    category: 'network',
    criticality: 'required',
    name: t('Request running', '요청 실행 중', 'リクエスト実行中'),
    summary: t(
      'A request has been sent and the console is waiting for the response.',
      '요청을 보냈고 콘솔이 응답을 기다리는 중인 상태.',
      'リクエストを送信し、コンソールが応答を待っている状態。'),
    aliases: ['running', 'in flight', 'pending request', 'awaiting response', '실행 중', '요청 중', '応答待ち', 'リクエスト中'],
    domainSignals: ['request', 'pending', 'loading', 'endpoint'],
    triggers: [
      t('The user sends a request and the response has not arrived',
        '사용자가 요청을 보냈고 응답이 아직 도착하지 않음',
        'リクエストを送信し、応答がまだ届いていない'),
    ],
    userQuestions: [
      t('Did my request go through, and can I cancel it if it hangs?',
        '내 요청이 정말 나갔나? 멈추면 취소할 수 있나?',
        'リクエストは送れたのか?固まったら取り消せるのか?'),
    ],
    mustShow: [
      t('A clear in-progress indicator scoped to the running request',
        '실행 중인 요청에 한정된 명확한 진행 표시',
        '実行中のリクエストに限定した進行表示'),
      t('The method and endpoint being called',
        '호출 중인 메서드와 엔드포인트',
        '呼び出し中のメソッドとエンドポイント'),
    ],
    mustPreserve: [
      t('The request being run — method, URL, params, headers, and body',
        '실행 중인 요청 — 메서드·URL·파라미터·헤더·본문',
        '実行中のリクエスト — メソッド・URL・パラメータ・ヘッダー・本文'),
      t('The console request history',
        '콘솔 요청 히스토리',
        'コンソールのリクエスト履歴'),
    ],
    primaryActions: [ t('Cancel request', '요청 취소', 'リクエストを取消') ],
    secondaryActions: [ t('Edit the request while waiting', '대기 중 요청 편집', '待機中にリクエストを編集') ],
    mustNot: [
      t('Disable the whole console while one request is in flight',
        '한 요청이 진행 중이라고 콘솔 전체를 잠그기',
        'リクエスト1件の実行中にコンソール全体を操作不能にする'),
      t('Let the spinner run forever with no timeout or cancel',
        '타임아웃·취소 없이 스피너를 무한정 돌리기',
        'タイムアウト・取消なしでスピナーを無限に回す'),
    ],
    accessibility: {
      announcement: t('Announce "request running" politely via a busy status',
        '"요청 실행 중"을 busy 상태로 방해되지 않게 안내',
        '「リクエスト実行中」をbusy状態で控えめに通知'),
      focus: t('Keep focus on the send/cancel control', '포커스를 보내기·취소 컨트롤에 유지', 'フォーカスを送信・取消コントロールに維持'),
    },
    motion: {
      guidance: [ t('A calm, looping progress indicator; no jumpy layout', '차분한 반복 진행 표시, 들썩이는 레이아웃 금지', '落ち着いたループ進行表示、レイアウトの跳ねを禁止') ],
      reducedMotion: [ t('Use a static "Running…" label instead of an animated spinner', '애니메이션 스피너 대신 정적 "실행 중…" 라벨', 'アニメスピナーの代わりに静的な「実行中…」ラベル') ],
    },
  },
  {
    id: 'console-success',
    surfaceIds: ['developer-console'],
    category: 'data',
    criticality: 'required',
    name: t('Request succeeded', '요청 성공', 'リクエスト成功'),
    summary: t(
      'The request returned a successful response and the console renders the result.',
      '요청이 성공 응답을 반환했고 콘솔이 결과를 표시한 상태.',
      'リクエストが成功応答を返し、コンソールが結果を表示した状態。'),
    aliases: ['success', '2xx', 'ok response', 'completed request', '성공', '응답 성공', '成功', '応答成功'],
    domainSignals: ['response', 'result', 'status', '200'],
    triggers: [
      t('The endpoint returns a success status with a body',
        '엔드포인트가 본문과 함께 성공 상태를 반환',
        'エンドポイントが本文付きの成功ステータスを返す'),
    ],
    userQuestions: [
      t('What exactly did the API return, and how do I reuse this call?',
        'API가 정확히 무엇을 돌려줬나? 이 호출을 어떻게 재사용하나?',
        'APIは正確に何を返したか?この呼び出しをどう再利用するか?'),
    ],
    mustShow: [
      t('The status code, latency, and response body',
        '상태 코드·응답 시간·응답 본문',
        'ステータスコード・レイテンシ・応答本文'),
      t('Response headers, available on demand',
        '필요 시 볼 수 있는 응답 헤더',
        '必要に応じて確認できる応答ヘッダー'),
    ],
    mustPreserve: [
      t('The exact request that produced this response',
        '이 응답을 만든 요청 그대로',
        'この応答を生んだリクエストそのもの'),
      t('The console request history',
        '콘솔 요청 히스토리',
        'コンソールのリクエスト履歴'),
    ],
    primaryActions: [ t('Copy response', '응답 복사', '応答をコピー') ],
    secondaryActions: [
      t('Copy as code snippet (curl/SDK)', '코드 스니펫으로 복사(curl/SDK)', 'コードスニペットでコピー(curl/SDK)'),
      t('Save the request', '요청 저장', 'リクエストを保存'),
    ],
    mustNot: [
      t('Truncate the body without a clear way to see the full payload',
        '전체 페이로드를 볼 길 없이 본문을 잘라내기',
        '全文を確認する手段なく本文を切り詰める'),
      t('Pretty-print so aggressively that the raw response is unrecoverable',
        '원본 응답을 되찾을 수 없을 만큼 과하게 가공해 표시하기',
        '生の応答に戻せないほど過剰に整形して表示する'),
    ],
    accessibility: {
      announcement: t('Announce success and the status code politely',
        '성공과 상태 코드를 방해되지 않게 안내',
        '成功とステータスコードを控えめに通知'),
      focus: t('Move focus to the response panel', '포커스를 응답 패널로 이동', 'フォーカスを応答パネルへ移動'),
    },
    motion: {
      guidance: [ t('Reveal the response region only; no confetti', '응답 영역만 표시, 컨페티 금지', '応答領域だけ表示、紙吹雪は禁止') ],
      reducedMotion: [ t('Swap in the response with no transition', '전환 없이 응답으로 교체', 'トランジション無しで応答に差し替え') ],
    },
  },
  {
    id: 'invalid-request',
    surfaceIds: ['developer-console'],
    category: 'data',
    criticality: 'required',
    name: t('Invalid request', '잘못된 요청', '不正なリクエスト'),
    summary: t(
      'The server reached the request but rejected it as malformed or invalid (400/422).',
      '서버에 요청은 닿았으나 형식·내용이 잘못돼 거절된 상태(400/422).',
      'サーバーには届いたが、形式・内容が不正として拒否された状態(400/422)。'),
    aliases: ['400', '422', 'validation error', 'bad request', 'malformed', '잘못된 요청', '검증 오류', 'バリデーションエラー', '不正リクエスト'],
    domainSignals: ['validation', 'parameter', 'schema', '400'],
    triggers: [
      t('The server returns a validation error for the parameters or body',
        '서버가 파라미터·본문에 대한 검증 오류를 반환',
        'サーバーがパラメータ・本文の検証エラーを返す'),
    ],
    userQuestions: [
      t('Which field is wrong, and what value does the API expect?',
        '어느 필드가 틀렸고, API가 기대하는 값은 무엇인가?',
        'どのフィールドが誤りで、APIは何の値を期待しているのか?'),
    ],
    mustShow: [
      t('Which field or parameter failed and why',
        '어느 필드·파라미터가 왜 실패했는지',
        'どのフィールド・パラメータがなぜ失敗したか'),
      t('The status code and the server-provided error message',
        '상태 코드와 서버가 준 오류 메시지',
        'ステータスコードとサーバー提供のエラーメッセージ'),
    ],
    mustPreserve: [
      t('The request the user entered — params, headers, and body',
        '사용자가 입력한 요청 — 파라미터·헤더·본문',
        'ユーザーが入力したリクエスト — パラメータ・ヘッダー・本文'),
      t('The console request history',
        '콘솔 요청 히스토리',
        'コンソールのリクエスト履歴'),
    ],
    primaryActions: [ t('Fix the flagged field', '지적된 필드 수정', '指摘されたフィールドを修正') ],
    secondaryActions: [ t('Open the endpoint reference', '엔드포인트 레퍼런스 열기', 'エンドポイントのリファレンスを開く') ],
    mustNot: [
      t('Resubmit the same invalid request automatically',
        '같은 잘못된 요청을 자동으로 다시 보내기',
        '同じ不正リクエストを自動で再送する'),
      t('Show a generic "something went wrong" and discard the field detail',
        '필드별 상세를 버리고 막연한 "문제가 발생했습니다"만 보여주기',
        'フィールド別の詳細を捨てて漠然と「問題が発生しました」だけ表示する'),
    ],
    accessibility: {
      announcement: t('Announce the validation failure assertively (role=alert)',
        '검증 실패를 단호하게(alert) 안내',
        '検証失敗をはっきりと(alert)通知'),
      focus: t('Move focus to the first invalid field', '포커스를 첫 번째 잘못된 필드로 이동', 'フォーカスを最初の不正フィールドへ移動'),
    },
    motion: {
      guidance: [ t('Steady error reveal at the field; no shake or flash', '필드에 차분히 오류 표시, 흔들림·번쩍임 금지', 'フィールドに落ち着いてエラー表示、揺れ・点滅禁止') ],
      reducedMotion: [ t('Show field errors immediately, no motion', '필드 오류를 즉시 표시, 모션 없음', 'フィールドエラーを即時表示、モーションなし') ],
    },
  },
  {
    id: 'unauthorized',
    surfaceIds: ['developer-console'],
    category: 'permission',
    criticality: 'required',
    name: t('Unauthorized', '인증 안 됨', '認証されていません'),
    summary: t(
      'The request had no valid credentials — missing, expired, or invalid key/session (401).',
      '유효한 자격 증명이 없는 상태 — 키·세션이 없거나 만료·무효(401).',
      '有効な資格情報が無い状態 — キー・セッションが未提供か期限切れ・無効(401)。'),
    aliases: ['401', 'not authenticated', 'invalid key', 'expired token', 'missing credentials', '인증 실패', '키 만료', '認証失敗', 'トークン期限切れ'],
    domainSignals: ['auth', 'api-key', 'token', 'session', '401'],
    triggers: [
      t('No credentials are sent, or the API key/session is invalid or expired',
        '자격 증명이 없거나 API 키·세션이 무효·만료됨',
        '資格情報が無いか、APIキー・セッションが無効・期限切れ'),
    ],
    userQuestions: [
      t('Is my key wrong or expired, and how do I sign in or set a valid key?',
        '내 키가 틀렸나 만료됐나? 어떻게 로그인하거나 유효한 키를 넣나?',
        '私のキーは誤りか期限切れか?どうログインするか有効なキーを設定するのか?'),
    ],
    mustShow: [
      t('That authentication itself failed (not a permission problem)',
        '권한 문제가 아니라 인증 자체가 실패했음',
        '権限の問題ではなく認証そのものが失敗したこと'),
      t('How to sign in or supply a valid API key',
        '로그인하거나 유효한 API 키를 넣는 방법',
        'サインインまたは有効なAPIキーを設定する方法'),
    ],
    mustPreserve: [
      t('The attempted request and its parameters, so it can be retried once authenticated',
        '인증 후 다시 보낼 수 있도록 시도한 요청과 파라미터',
        '認証後に再送できるよう、試みたリクエストとパラメータ'),
      t('The console request history',
        '콘솔 요청 히스토리',
        'コンソールのリクエスト履歴'),
    ],
    primaryActions: [ t('Sign in / set API key', '로그인 / API 키 설정', 'サインイン / APIキー設定') ],
    secondaryActions: [ t('Open key management', '키 관리 열기', 'キー管理を開く') ],
    mustNot: [
      t('Confuse 401 with 403 — do not say the user lacks permission',
        '401을 403과 혼동해 권한 부족이라고 말하기',
        '401を403と混同して権限不足と告げる'),
      t('Echo the rejected key or token back in the error',
        '거절된 키·토큰을 오류에 그대로 노출하기',
        '拒否されたキー・トークンをエラーにそのまま表示する'),
    ],
    accessibility: {
      announcement: t('Announce the auth failure assertively (role=alert)',
        '인증 실패를 단호하게(alert) 안내',
        '認証失敗をはっきりと(alert)通知'),
      focus: t('Move focus to the sign-in or key field', '포커스를 로그인·키 입력으로 이동', 'フォーカスをサインイン・キー入力へ移動'),
    },
    motion: {
      guidance: [ t('Static, informational reveal; no alarm animation', '정적·정보 전달 표시, 경보 애니메이션 금지', '静的・情報提示の表示、警報アニメ禁止') ],
      reducedMotion: [ t('Show the prompt immediately, no motion', '안내를 즉시 표시, 모션 없음', '案内を即時表示、モーションなし') ],
    },
  },
  {
    id: 'forbidden',
    surfaceIds: ['developer-console'],
    category: 'permission',
    criticality: 'required',
    name: t('Forbidden', '권한 없음', '権限がありません'),
    summary: t(
      'The request was authenticated but the principal lacks permission (403).',
      '인증은 됐지만 해당 주체에 권한이 없는 상태(403).',
      '認証済みだが、その主体に権限がない状態(403)。'),
    aliases: ['403', 'access denied', 'not allowed', 'insufficient scope', '권한 거부', '접근 거부', 'アクセス拒否', '権限不足'],
    domainSignals: ['permission', 'scope', 'role', 'api-key'],
    triggers: [
      t('Authenticated principal lacks the required scope/role', '인증된 주체가 필요한 scope/role 미보유', '認証主体が必要なscope/roleを持たない'),
    ],
    userQuestions: [
      t('Am I logged in wrong, or just not allowed?', '로그인이 잘못된 건가, 그냥 권한이 없는 건가?', 'ログインが違うのか、単に許可が無いのか?'),
    ],
    mustShow: [
      t('That auth succeeded but permission is missing', '인증은 됐고 권한이 없음을', '認証は成功し権限が無いことを'),
      t('Which scope/role is required', '필요한 scope/role', '必要なscope/role'),
      t('How to request access', '권한 요청 방법', 'アクセス申請の方法'),
    ],
    mustPreserve: [
      t('The attempted request and its context', '시도한 요청과 맥락', '試みた要求とその文脈'),
    ],
    primaryActions: [ t('Request access / switch key', '권한 요청 / 키 전환', 'アクセス申請 / キー切替') ],
    secondaryActions: [ t('View required scopes', '필요 scope 보기', '必要scopeを表示') ],
    mustNot: [
      t('Show a login screen (it is not an auth failure)', '로그인 화면을 띄우기(인증 실패 아님)', 'ログイン画面を出す(認証失敗ではない)'),
      t('Suggest retrying the identical request', '동일 요청 재시도를 권하기', '同一要求の再試行を勧める'),
      t('Leak which resources exist via error detail', '오류 상세로 리소스 존재를 노출', 'エラー詳細で資源の存在を漏らす'),
    ],
    accessibility: {
      announcement: t('Announce assertively; do not trap focus', '단호하게 안내, 포커스 가두지 않기', 'はっきりと通知、フォーカスを閉じ込めない'),
    },
    motion: {
      guidance: [ t('Static, informational; no alarm animation', '정적·정보 전달, 경보 애니메이션 금지', '静的・情報提示、警報アニメ禁止') ],
      reducedMotion: [ t('No motion needed', '모션 불필요', 'モーション不要') ],
    },
  },
  {
    id: 'console-rate-limited',
    surfaceIds: ['developer-console'],
    category: 'network',
    criticality: 'recommended',
    name: t('Rate limited', '요청 한도 초과', 'レート制限'),
    summary: t(
      'The API rejected the request because the rate limit was exceeded (429).',
      'API가 요청 한도를 초과해 요청을 거절한 상태(429).',
      'APIがレート制限を超えたためリクエストを拒否した状態(429)。'),
    aliases: ['429', 'too many requests', 'rate limit', 'throttled', 'quota exceeded', '한도 초과', '쓰로틀', 'レート超過', 'スロットル'],
    domainSignals: ['rate-limit', 'throttle', 'quota', '429'],
    triggers: [
      t('The API returns 429 with a retry-after window',
        'API가 retry-after와 함께 429를 반환',
        'APIがretry-afterを伴って429を返す'),
    ],
    userQuestions: [
      t('How long until I can retry, and what is my limit?',
        '언제 다시 시도할 수 있나? 내 한도는 얼마인가?',
        'いつ再試行できるのか?私の上限はどれくらいか?'),
    ],
    mustShow: [
      t('The retry-after time, as an explicit countdown or timestamp',
        'retry-after 시간을 명시적 카운트다운·시각으로',
        'retry-afterの時間を明示的なカウントダウン・時刻で'),
      t('The limit that was hit and the current usage if known',
        '걸린 한도와, 알 수 있으면 현재 사용량',
        '到達した上限と、分かれば現在の使用量'),
    ],
    mustPreserve: [
      t('The request that was throttled — params, headers, and body',
        '한도에 걸린 요청 — 파라미터·헤더·본문',
        '制限に掛かったリクエスト — パラメータ・ヘッダー・本文'),
      t('The console request history',
        '콘솔 요청 히스토리',
        'コンソールのリクエスト履歴'),
    ],
    primaryActions: [ t('Retry after the wait window', '대기 시간 후 재시도', '待機時間後に再試行') ],
    secondaryActions: [ t('View rate-limit and quota docs', '한도·쿼터 문서 보기', 'レート制限・クォータ文書を表示') ],
    mustNot: [
      t('Silently auto-retry before retry-after elapses',
        'retry-after가 지나기 전에 조용히 자동 재시도하기',
        'retry-after経過前に黙って自動再試行する'),
      t('Hide the wait time or present it as a generic failure',
        '대기 시간을 숨기거나 일반 실패처럼 표시하기',
        '待機時間を隠す、または一般的な失敗として表示する'),
    ],
    accessibility: {
      announcement: t('Announce the rate limit and wait time assertively (role=alert)',
        '한도 초과와 대기 시간을 단호하게(alert) 안내',
        'レート制限と待機時間をはっきりと(alert)通知'),
      focus: t('Move focus to the retry control', '포커스를 재시도 컨트롤로 이동', 'フォーカスを再試行コントロールへ移動'),
    },
    motion: {
      guidance: [ t('A calm countdown only; no flashing or alarm motion', '차분한 카운트다운만, 번쩍임·경보 모션 금지', '落ち着いたカウントダウンのみ、点滅・警報モーション禁止') ],
      reducedMotion: [ t('Show a static "retry at HH:MM" timestamp instead of a ticking timer', '째깍이는 타이머 대신 정적 "HH:MM에 재시도" 표시', 'カチカチ動くタイマーの代わりに静的な「HH:MMに再試行」表示') ],
    },
  },
  {
    id: 'console-service-unavailable',
    surfaceIds: ['developer-console'],
    category: 'network',
    criticality: 'recommended',
    name: t('Service unavailable', '서비스 이용 불가', 'サービス利用不可'),
    summary: t(
      'The API or an upstream dependency is temporarily down or unreachable (5xx / timeout).',
      'API나 상위 의존 서비스가 일시적으로 다운·도달 불가인 상태(5xx·타임아웃).',
      'APIまたは上流の依存サービスが一時的にダウン・到達不能な状態(5xx・タイムアウト)。'),
    aliases: ['503', '500', 'server error', 'upstream down', 'timeout', 'outage', '서버 오류', '장애', 'サーバーエラー', '障害'],
    domainSignals: ['outage', 'upstream', 'server-error', '503'],
    triggers: [
      t('The API returns a 5xx, or the request times out with no response',
        'API가 5xx를 반환하거나 응답 없이 타임아웃됨',
        'APIが5xxを返すか、応答なしでタイムアウトする'),
    ],
    userQuestions: [
      t('Is this my code or the service, and when should I try again?',
        '이게 내 코드 문제인가 서비스 문제인가? 언제 다시 시도하나?',
        'これは私のコードの問題かサービスの問題か?いつ再試行すべきか?'),
    ],
    mustShow: [
      t('That the failure is server-side, not the user request',
        '실패가 사용자 요청이 아니라 서버 쪽임',
        '失敗がユーザーのリクエストではなくサーバー側であること'),
      t('A status-page link or known-incident notice if available',
        '상태 페이지 링크나, 알려진 장애 안내가 있으면 함께',
        'ステータスページのリンクや、既知の障害情報があれば併せて'),
    ],
    mustPreserve: [
      t('The request that failed — params, headers, and body',
        '실패한 요청 — 파라미터·헤더·본문',
        '失敗したリクエスト — パラメータ・ヘッダー・本文'),
      t('The console request history',
        '콘솔 요청 히스토리',
        'コンソールのリクエスト履歴'),
    ],
    primaryActions: [ t('Retry with backoff', '백오프 후 재시도', 'バックオフして再試行') ],
    secondaryActions: [ t('Open the status page', '상태 페이지 열기', 'ステータスページを開く') ],
    mustNot: [
      t('Blame the user or imply their request was malformed',
        '사용자를 탓하거나 요청이 잘못됐다고 암시하기',
        'ユーザーを責める、またはリクエストが不正だと示唆する'),
      t('Hammer the endpoint with immediate, unbounded auto-retries',
        '간격 없이 무제한 자동 재시도로 엔드포인트를 두드리기',
        '間隔なしの無制限な自動再試行でエンドポイントを叩く'),
    ],
    accessibility: {
      announcement: t('Announce the outage assertively (role=alert)',
        '장애를 단호하게(alert) 안내',
        '障害をはっきりと(alert)通知'),
      focus: t('Move focus to the retry control', '포커스를 재시도 컨트롤로 이동', 'フォーカスを再試行コントロールへ移動'),
    },
    motion: {
      guidance: [ t('Steady error reveal; no alarm or shake', '차분한 오류 표시, 경보·흔들림 금지', '落ち着いたエラー表示、警報・揺れ禁止') ],
      reducedMotion: [ t('Show the error and retry option immediately, no motion', '오류와 재시도 옵션을 즉시 표시, 모션 없음', 'エラーと再試行オプションを即時表示、モーションなし') ],
    },
  },
  {
    id: 'response-too-large',
    surfaceIds: ['developer-console'],
    category: 'content',
    criticality: 'domain-specific',
    name: t('Response too large', '응답이 너무 큼', '応答が大きすぎます'),
    summary: t(
      'The response is too large to render fully in the console without freezing the view.',
      '응답이 너무 커서 화면을 멈추지 않고는 콘솔에 전부 렌더링할 수 없는 상태.',
      '応答が大きすぎて、画面を固めずにコンソールへ全文を描画できない状態。'),
    aliases: ['large response', 'huge payload', 'too big to render', 'oversized body', '큰 응답', '거대 페이로드', '大きい応答', '巨大ペイロード'],
    domainSignals: ['payload-size', 'large', 'pagination', 'streaming'],
    triggers: [
      t('The response body exceeds the safe render threshold for the console',
        '응답 본문이 콘솔의 안전 렌더링 한계를 초과',
        '応答本文がコンソールの安全描画しきい値を超える'),
    ],
    userQuestions: [
      t('Can I still get the full data without crashing the console?',
        '콘솔을 멈추지 않고도 전체 데이터를 받을 수 있나?',
        'コンソールを止めずに全データを取得できるのか?'),
    ],
    mustShow: [
      t('That the response is too large to render in full and why',
        '응답이 전부 렌더링하기엔 너무 크다는 점과 그 이유',
        '応答が全文描画には大きすぎることとその理由'),
      t('The total size and how much is currently shown',
        '전체 크기와 현재 보이는 분량',
        '全体サイズと現在表示している分量'),
    ],
    mustPreserve: [
      t('The request that produced the response, and the full body in memory or storage',
        '응답을 만든 요청과, 메모리·저장소에 있는 전체 본문',
        '応答を生んだリクエストと、メモリ・ストレージ上の全文'),
      t('The console request history',
        '콘솔 요청 히스토리',
        'コンソールのリクエスト履歴'),
    ],
    primaryActions: [ t('Download the full response', '전체 응답 다운로드', '応答全文をダウンロード') ],
    secondaryActions: [
      t('Paginate or stream the response', '응답을 페이지네이션·스트리밍으로 보기', '応答をページング・ストリーミングで見る'),
      t('View a previewed first chunk', '앞부분만 미리보기', '先頭チャンクをプレビュー'),
    ],
    mustNot: [
      t('Silently truncate the body with no access to the rest',
        '나머지에 접근할 길 없이 본문을 조용히 잘라내기',
        '残りへの導線なく本文を黙って切り詰める'),
      t('Try to render the entire payload and freeze the console',
        '전체 페이로드를 통째로 렌더링하려다 콘솔을 멈추기',
        '全ペイロードを丸ごと描画しようとしてコンソールを固める'),
    ],
    accessibility: {
      announcement: t('Announce that the response was truncated for display, politely',
        '표시를 위해 응답이 잘렸음을 방해되지 않게 안내',
        '表示のため応答が省略されたことを控えめに通知'),
      focus: t('Move focus to the download or pagination control', '포커스를 다운로드·페이지네이션 컨트롤로 이동', 'フォーカスをダウンロード・ページングコントロールへ移動'),
    },
    motion: {
      guidance: [ t('Reveal the truncation notice calmly; stream additional chunks smoothly', '잘림 안내를 차분히 표시, 추가 청크는 매끄럽게 스트리밍', '省略の案内を落ち着いて表示、追加チャンクは滑らかにストリーミング') ],
      reducedMotion: [ t('Load chunks on explicit action with no progressive animation', '점진적 애니메이션 없이 명시적 동작으로 청크 로드', '段階的アニメなしで明示操作によりチャンクを読み込む') ],
    },
  },
  {
    id: 'console-partial-response',
    surfaceIds: ['developer-console'],
    category: 'data',
    criticality: 'domain-specific',
    name: t('Partial response', '부분 응답', '部分応答'),
    summary: t(
      'The connection dropped or the stream ended early, so only part of the response arrived.',
      '연결이 끊기거나 스트림이 일찍 종료돼 응답의 일부만 도착한 상태.',
      '接続が切れたか、ストリームが早期終了し、応答の一部だけ届いた状態。'),
    aliases: ['partial', 'incomplete response', 'truncated stream', 'connection dropped', '부분 응답', '불완전 응답', '部分応答', '途中切断'],
    domainSignals: ['partial', 'stream', 'incomplete', 'interrupted'],
    triggers: [
      t('The stream or connection ends before the full body is received',
        '전체 본문을 받기 전에 스트림·연결이 종료됨',
        '全文を受け取る前にストリーム・接続が終了する'),
    ],
    userQuestions: [
      t('Is this all the data, or did the response get cut off?',
        '이게 데이터 전부인가, 아니면 응답이 중간에 잘린 건가?',
        'これが全データか、それとも応答が途中で切れたのか?'),
    ],
    mustShow: [
      t('That the response is incomplete, not a full successful result',
        '응답이 성공 완료가 아니라 불완전함',
        '応答が完了した成功ではなく不完全であること'),
      t('Which part arrived and where it was cut off',
        '도착한 부분과 잘린 지점',
        '届いた部分と切れた位置'),
    ],
    mustPreserve: [
      t('The partial data already received and the request that produced it',
        '이미 받은 부분 데이터와 그 요청',
        'すでに受け取った部分データとそのリクエスト'),
      t('The console request history',
        '콘솔 요청 히스토리',
        'コンソールのリクエスト履歴'),
    ],
    primaryActions: [ t('Resume or re-run the request', '요청 이어받기·다시 실행', 'リクエストを再開・再実行') ],
    secondaryActions: [ t('Copy the partial response', '받은 부분 응답 복사', '受け取った部分応答をコピー') ],
    mustNot: [
      t('Present the partial body as a complete, successful response',
        '부분 본문을 완전한 성공 응답인 것처럼 보여주기',
        '部分的な本文を完全な成功応答のように見せる'),
      t('Discard the bytes already received on the failure',
        '실패 시 이미 받은 바이트를 버리기',
        '失敗時にすでに受信したバイトを捨てる'),
    ],
    accessibility: {
      announcement: t('Announce that the response is incomplete assertively (role=alert)',
        '응답이 불완전함을 단호하게(alert) 안내',
        '応答が不完全であることをはっきりと(alert)通知'),
      focus: t('Move focus to the resume/re-run control', '포커스를 이어받기·재실행 컨트롤로 이동', 'フォーカスを再開・再実行コントロールへ移動'),
    },
    motion: {
      guidance: [ t('Mark the cut-off point calmly; no alarm motion', '잘린 지점을 차분히 표시, 경보 모션 금지', '切れた位置を落ち着いて表示、警報モーション禁止') ],
      reducedMotion: [ t('Show the incomplete marker immediately, no motion', '불완전 표시를 즉시 보여주기, 모션 없음', '不完全マーカーを即時表示、モーションなし') ],
    },
  },
];
