import { t } from '../../localization';
import type { StateRecipe } from '../types';

export const formRecipes: StateRecipe[] = [
  {
    id: 'pristine',
    surfaceIds: ['form'],
    category: 'interaction',
    criticality: 'required',
    name: t('Pristine', '미입력 상태', '未入力状態'),
    summary: t(
      'The form is freshly loaded; no field has been touched or changed yet.',
      '폼이 막 열린 상태로, 아직 어떤 필드도 만지거나 바꾸지 않은 상태.',
      'フォームを開いた直後で、まだどの項目も触れていない・変更していない状態。'),
    aliases: ['untouched', 'initial form', 'clean form', 'default state', '초기 폼', '입력 전', '未編集', '初期状態'],
    domainSignals: ['form', 'input', 'field', 'create', 'edit'],
    triggers: [
      t('The form first renders with default or empty values',
        '폼이 기본값 또는 빈 값으로 처음 렌더링됨',
        'フォームが既定値または空値で初めて描画される'),
      t('The user has not edited any field yet',
        '사용자가 아직 어떤 필드도 편집하지 않음',
        'ユーザーがまだどの項目も編集していない'),
    ],
    userQuestions: [
      t('What do I need to fill in, and which fields are required?',
        '무엇을 입력해야 하고, 어떤 항목이 필수지?',
        '何を入力すればよく、どの項目が必須なんだろう?'),
      t('Where do I start?',
        '어디서부터 시작하지?',
        'どこから始めればいい?'),
    ],
    mustShow: [
      t('Clear field labels and which fields are required',
        '명확한 필드 레이블과 필수 항목 표시',
        '明確な項目ラベルと必須項目の表示'),
      t('Helpful placeholder or format hints where needed',
        '필요한 곳에 도움이 되는 자리표시자나 형식 안내',
        '必要な箇所に役立つプレースホルダーや形式の案内'),
      t('A clearly available primary submit action',
        '명확히 사용 가능한 기본 제출 동작',
        '明確に利用できる主送信アクション'),
    ],
    mustPreserve: [
      t('Any default values prefilled for the user',
        '사용자를 위해 미리 채워진 기본값',
        'ユーザー向けにあらかじめ入った既定値'),
      t('Logical tab order across fields',
        '필드 간 논리적인 탭 순서',
        '項目間の論理的なタブ順序'),
    ],
    primaryActions: [
      t('Begin filling the first field',
        '첫 번째 필드 입력 시작',
        '最初の項目の入力を開始'),
    ],
    secondaryActions: [
      t('View an example or guidance',
        '예시나 안내 보기',
        '例や案内を表示'),
    ],
    mustNot: [
      t('Show validation errors before the user has typed anything',
        '사용자가 아무것도 입력하기 전에 검증 오류를 표시',
        'ユーザーが何も入力する前に検証エラーを表示'),
      t('Disable submit with no explanation of what is missing',
        '무엇이 빠졌는지 설명 없이 제출을 비활성화',
        '何が足りないか説明せず送信を無効化'),
      t('Mark every field with an error or warning style upfront',
        '처음부터 모든 필드를 오류·경고 스타일로 표시',
        '最初から全項目をエラー・警告スタイルにする'),
    ],
    accessibility: {
      announcement: t('No live announcement needed on initial render',
        '초기 렌더링 시 라이브 안내 불필요',
        '初期描画時はライブ通知は不要'),
      focus: t('Place focus on the first interactive field or heading',
        '포커스를 첫 인터랙티브 필드 또는 제목에 배치',
        'フォーカスを最初の操作可能な項目または見出しに置く'),
      keyboard: [
        t('Tab moves through fields in visual order',
          'Tab으로 시각적 순서대로 필드 이동',
          'Tabで視覚的順序どおりに項目を移動'),
      ],
      contrast: [
        t('Required markers must not rely on color alone',
          '필수 표시는 색상에만 의존하지 않기',
          '必須表示は色だけに頼らない'),
      ],
    },
    motion: {
      guidance: [
        t('Render fields statically; no entrance animation that delays input',
          '필드를 정적으로 표시, 입력을 지연시키는 등장 애니메이션 금지',
          '項目を静的に表示し、入力を遅らせる登場アニメは避ける'),
      ],
      reducedMotion: [
        t('Show the form immediately with no transition',
          '전환 없이 폼을 즉시 표시',
          'トランジション無しでフォームを即時表示'),
      ],
    },
  },
  {
    id: 'invalid',
    surfaceIds: ['form'],
    category: 'data',
    criticality: 'required',
    name: t('Invalid input', '입력값 오류', '入力値エラー'),
    summary: t(
      'One or more fields fail client-side validation and the form cannot be submitted as is.',
      '하나 이상의 필드가 클라이언트 검증에 실패해 현재 상태로는 제출할 수 없는 상태.',
      '1つ以上の項目がクライアント検証に失敗し、このままでは送信できない状態。'),
    aliases: ['validation error', 'field error', 'invalid form', 'bad input', '검증 실패', '필드 오류', 'バリデーションエラー', '項目エラー'],
    domainSignals: ['validation', 'error', 'required', 'format', 'form'],
    triggers: [
      t('A field value violates a validation rule (format, range, required)',
        '필드 값이 검증 규칙(형식·범위·필수)을 위반',
        '項目の値が検証ルール(形式・範囲・必須)に違反'),
      t('The user attempts to submit with invalid fields',
        '유효하지 않은 필드가 있는 채로 제출을 시도',
        '無効な項目があるまま送信を試みる'),
    ],
    userQuestions: [
      t('Which field is wrong, and exactly how do I fix it?',
        '어떤 필드가 잘못됐고, 정확히 어떻게 고치지?',
        'どの項目が間違っていて、どう直せばいい?'),
      t('Did I lose what I already typed?',
        '이미 입력한 내용이 사라진 건가?',
        'すでに入力した内容は消えていない?'),
    ],
    mustShow: [
      t('A specific message on each invalid field, near that field',
        '각 오류 필드 옆에 구체적인 메시지 표시',
        '各エラー項目のそばに具体的なメッセージを表示'),
      t('How to correct it, not just that it is wrong',
        '잘못됐다는 사실뿐 아니라 고치는 방법 안내',
        '間違いの指摘だけでなく直し方を案内'),
      t('A summary or count when several fields are invalid',
        '여러 필드가 오류일 때 요약이나 개수 표시',
        '複数項目がエラーのとき要約や件数を表示'),
    ],
    mustPreserve: [
      t('Every value the user already entered, including valid fields',
        '유효한 필드를 포함해 사용자가 이미 입력한 모든 값',
        '有効な項目を含め、ユーザーが入力済みの全ての値'),
      t('Cursor position and the field the user was editing',
        '커서 위치와 사용자가 편집 중이던 필드',
        'カーソル位置と編集中だった項目'),
    ],
    primaryActions: [
      t('Jump to the first invalid field to correct it',
        '첫 번째 오류 필드로 이동해 수정',
        '最初のエラー項目へ移動して修正'),
    ],
    secondaryActions: [
      t('Re-check the requirements for a field',
        '필드의 요구 조건 다시 확인',
        '項目の要件を再確認'),
    ],
    mustNot: [
      t('Clear or reset the values the user already entered',
        '사용자가 이미 입력한 값을 지우거나 초기화',
        'ユーザーが入力済みの値を消去・リセットする'),
      t('Show only a generic "form has errors" with no field detail',
        '필드별 상세 없이 “폼에 오류가 있음”만 표시',
        '項目別の詳細なく「フォームにエラーがあります」とだけ表示'),
      t('Mark valid fields as errored or hide the error cause',
        '유효한 필드를 오류로 표시하거나 오류 원인을 숨기기',
        '有効な項目をエラー扱いしたり原因を隠す'),
    ],
    accessibility: {
      announcement: t('Announce the error assertively (role=alert) on submit attempt',
        '제출 시도 시 오류를 단호하게(role=alert) 안내',
        '送信試行時にエラーをはっきりと(role=alert)通知'),
      focus: t('Move focus to the first invalid field or the error summary',
        '포커스를 첫 오류 필드 또는 오류 요약으로 이동',
        'フォーカスを最初のエラー項目またはエラー要約へ移動'),
      keyboard: [
        t('Each error message is reachable and linked to its field',
          '각 오류 메시지에 도달 가능하고 해당 필드와 연결',
          '各エラーメッセージへ到達でき、対象項目と紐づく'),
      ],
      contrast: [
        t('Error styling uses an icon or text, not color alone',
          '오류 표시는 색상만이 아니라 아이콘·텍스트 사용',
          'エラー表示は色だけでなくアイコン・テキストを併用'),
      ],
    },
    motion: {
      guidance: [
        t('Reveal each error message calmly in place; no aggressive shake',
          '각 오류 메시지를 제자리에서 차분히 표시, 과한 흔들림 금지',
          '各エラーメッセージをその場で落ち着いて表示し、強い揺れは避ける'),
      ],
      reducedMotion: [
        t('Show errors immediately with no shake or bounce',
          '흔들림·바운스 없이 오류를 즉시 표시',
          '揺れ・バウンス無しでエラーを即時表示'),
      ],
    },
  },
  {
    id: 'submitting',
    surfaceIds: ['form'],
    category: 'network',
    criticality: 'required',
    name: t('Submitting', '제출 중', '送信中'),
    summary: t(
      'The form passed validation and is being sent to the server; the result is not yet known.',
      '폼이 검증을 통과해 서버로 전송 중이며, 아직 결과를 알 수 없는 상태.',
      'フォームが検証を通過しサーバーへ送信中で、まだ結果が分からない状態。'),
    aliases: ['saving', 'in flight', 'processing', 'sending', '저장 중', '전송 중', '保存中', '処理中'],
    domainSignals: ['submit', 'save', 'request', 'pending', 'form'],
    triggers: [
      t('The user submits a valid form and the request is in flight',
        '사용자가 유효한 폼을 제출해 요청이 전송 중',
        'ユーザーが有効なフォームを送信し、要求が処理中'),
      t('The server has not yet responded with success or failure',
        '서버가 아직 성공·실패 응답을 주지 않음',
        'サーバーがまだ成功・失敗を応答していない'),
    ],
    userQuestions: [
      t('Did it go through, or should I click again?',
        '전송된 건가, 아니면 다시 눌러야 하나?',
        '送信できたのか、もう一度押すべきか?'),
      t('How long will this take?',
        '얼마나 걸리지?',
        'どのくらいかかる?'),
    ],
    mustShow: [
      t('A clear in-progress indicator on the submit control',
        '제출 버튼에 명확한 진행 중 표시',
        '送信ボタンに明確な進行中表示'),
      t('That the request has been accepted and is processing',
        '요청이 접수되어 처리 중임을 표시',
        '要求が受け付けられ処理中であることを表示'),
    ],
    mustPreserve: [
      t('All entered field values in case the request fails',
        '요청 실패에 대비해 입력한 모든 필드 값',
        '要求失敗に備えて入力済みの全項目値'),
      t('The scroll position within the form',
        '폼 내 스크롤 위치',
        'フォーム内のスクロール位置'),
    ],
    primaryActions: [
      t('Wait for the result while the control stays busy',
        '버튼이 처리 중인 상태로 결과를 대기',
        'ボタンが処理中のまま結果を待つ'),
    ],
    secondaryActions: [
      t('Cancel the submission if it is safely cancelable',
        '안전하게 취소 가능하면 제출 취소',
        '安全に取り消せる場合は送信をキャンセル'),
    ],
    mustNot: [
      t('Allow the submit button to be pressed again (double-submit)',
        '제출 버튼을 다시 누를 수 있게 두기(중복 제출)',
        '送信ボタンを再度押せるままにする(二重送信)'),
      t('Wipe or lock the entered values so they are lost if it fails',
        '입력값을 지우거나 잠가서 실패 시 잃게 만들기',
        '入力値を消去・ロックして失敗時に失わせる'),
      t('Leave the user with no feedback that anything is happening',
        '아무 일도 일어나지 않는 것처럼 피드백을 주지 않기',
        '何も起きていないかのように一切のフィードバックを与えない'),
    ],
    accessibility: {
      announcement: t('Announce "submitting" politely via aria-live; mark the control aria-busy',
        '“제출 중”을 aria-live로 방해되지 않게 안내하고 버튼을 aria-busy로 표시',
        '「送信中」をaria-liveで控えめに通知し、ボタンをaria-busyにする'),
      focus: t('Keep focus on the submit control; do not steal focus mid-request',
        '포커스를 제출 버튼에 유지, 요청 중 포커스를 빼앗지 않기',
        'フォーカスを送信ボタンに維持し、要求中にフォーカスを奪わない'),
      keyboard: [
        t('Disabled submit still announces a busy state to assistive tech',
          '비활성화된 제출 버튼도 보조 기술에 busy 상태를 알림',
          '無効化した送信ボタンも支援技術にbusy状態を伝える'),
      ],
      contrast: [
        t('The busy indicator is visible against the button background',
          '진행 표시가 버튼 배경과 대비되어 보임',
          '進行表示がボタン背景に対して見える'),
      ],
    },
    motion: {
      guidance: [
        t('Use a steady, looping progress indicator; no jumpy motion',
          '일정하게 반복되는 진행 표시 사용, 튀는 모션 금지',
          '一定に繰り返す進行表示を使い、跳ねる動きは避ける'),
      ],
      reducedMotion: [
        t('Replace the spinner with a static "Submitting…" label',
          '스피너를 정적인 “제출 중…” 레이블로 대체',
          'スピナーを静的な「送信中…」ラベルに置き換える'),
      ],
    },
  },
  {
    id: 'submission-failed',
    surfaceIds: ['form'],
    category: 'network',
    criticality: 'required',
    name: t('Submission failed', '제출 실패', '送信失敗'),
    summary: t(
      'The submit request did not complete due to a network or server error, unrelated to field validity.',
      '필드 유효성과 무관하게 네트워크나 서버 오류로 제출 요청이 완료되지 못한 상태.',
      '項目の妥当性とは無関係に、ネットワークやサーバーのエラーで送信が完了しなかった状態。'),
    aliases: ['save failed', 'network error', 'server error', 'request failed', '저장 실패', '전송 실패', '通信エラー', 'サーバーエラー'],
    domainSignals: ['error', 'network', 'timeout', 'submit', 'form'],
    triggers: [
      t('The request times out or the network drops mid-submit',
        '제출 중 요청이 타임아웃되거나 네트워크가 끊김',
        '送信中に要求がタイムアウトするかネットワークが切断'),
      t('The server returns a 5xx or unexpected error',
        '서버가 5xx나 예상치 못한 오류를 반환',
        'サーバーが5xxや想定外のエラーを返す'),
    ],
    userQuestions: [
      t('Did my data save or not? Will I lose what I typed?',
        '내 데이터가 저장된 건가 아닌가? 입력한 게 사라지나?',
        'データは保存された?入力した内容は失われる?'),
      t('Is it safe to try again?',
        '다시 시도해도 안전한가?',
        'もう一度試しても大丈夫?'),
    ],
    mustShow: [
      t('That the submission did not complete and why, in plain language',
        '제출이 완료되지 않았음과 그 이유를 쉬운 말로 표시',
        '送信が完了しなかったことと理由を平易な言葉で表示'),
      t('A reassurance that the entered data is still here',
        '입력한 데이터가 그대로 남아 있다는 안심 표시',
        '入力済みデータがそのまま残っているという安心の表示'),
      t('A clear way to retry the submission',
        '제출을 재시도하는 명확한 방법',
        '送信を再試行する明確な方法'),
    ],
    mustPreserve: [
      t('All entered field values so nothing the user typed is lost',
        '사용자가 입력한 내용이 하나도 사라지지 않도록 모든 필드 값',
        'ユーザーが入力した内容が失われないよう全項目値'),
      t('Scroll and focus position within the form',
        '폼 내 스크롤과 포커스 위치',
        'フォーム内のスクロールとフォーカス位置'),
    ],
    primaryActions: [
      t('Retry the submission manually',
        '수동으로 제출 재시도',
        '手動で送信を再試行'),
    ],
    secondaryActions: [
      t('Save a draft locally so progress is not lost',
        '진행 내용을 잃지 않도록 로컬에 임시 저장',
        '進捗を失わないようローカルに下書き保存'),
    ],
    mustNot: [
      t('Discard or clear the user input on failure',
        '실패 시 사용자 입력을 버리거나 지우기',
        '失敗時にユーザー入力を破棄・消去する'),
      t('Silently auto-retry, risking a duplicate or partial save',
        '조용히 자동 재시도해 중복·부분 저장 위험을 만들기',
        '黙って自動再試行し、重複・部分保存の危険を生む'),
      t('Claim success or imply the data was saved when it was not',
        '저장되지 않았는데 성공이라고 하거나 저장된 듯 오해시키기',
        '保存されていないのに成功と称したり保存済みと誤解させる'),
    ],
    accessibility: {
      announcement: t('Announce the failure assertively (role=alert)',
        '실패를 단호하게(role=alert) 안내',
        '失敗をはっきりと(role=alert)通知'),
      focus: t('Move focus to the error message and the retry action',
        '포커스를 오류 메시지와 재시도 동작으로 이동',
        'フォーカスをエラーメッセージと再試行アクションへ移動'),
      keyboard: [
        t('The retry control is keyboard reachable from the error',
          '재시도 버튼이 오류에서 키보드로 도달 가능',
          '再試行ボタンがエラーからキーボードで到達可能'),
      ],
      contrast: [
        t('Error text meets contrast and is not conveyed by color alone',
          '오류 텍스트가 대비 기준을 충족하고 색상만으로 전달하지 않음',
          'エラーテキストがコントラストを満たし、色だけで伝えない'),
      ],
    },
    motion: {
      guidance: [
        t('Reveal the error calmly; no celebratory or alarming animation',
          '오류를 차분히 표시, 축하성·경보성 애니메이션 금지',
          'エラーを落ち着いて表示し、祝福系・警報系アニメは避ける'),
      ],
      reducedMotion: [
        t('Show the error immediately with no shake or flash',
          '흔들림·번쩍임 없이 오류를 즉시 표시',
          '揺れ・点滅無しでエラーを即時表示'),
      ],
    },
  },
  {
    id: 'form-success',
    surfaceIds: ['form'],
    category: 'data',
    criticality: 'required',
    name: t('Submission succeeded', '제출 완료', '送信完了'),
    summary: t(
      'The server accepted and saved the submission; the user needs confirmation of what happened next.',
      '서버가 제출을 받아 저장했고, 사용자에게 무엇이 어떻게 됐는지 확인이 필요한 상태.',
      'サーバーが送信を受け取り保存し、ユーザーに何がどうなったかの確認が必要な状態。'),
    aliases: ['saved', 'submitted', 'success', 'done', 'confirmed', '저장됨', '완료', '제출됨', '保存完了', '成功'],
    domainSignals: ['success', 'saved', 'confirmation', 'submit', 'form'],
    triggers: [
      t('The server returns a success response for the submission',
        '서버가 제출에 대해 성공 응답을 반환',
        'サーバーが送信に対して成功を応答'),
      t('The record was created or updated as requested',
        '요청대로 레코드가 생성되거나 갱신됨',
        '要求どおりレコードが作成または更新された'),
    ],
    userQuestions: [
      t('Did it actually save, and what exactly was saved?',
        '정말 저장된 건가, 그리고 정확히 무엇이 저장됐지?',
        '本当に保存された?正確に何が保存された?'),
      t('What should I do next?',
        '이제 무엇을 해야 하지?',
        '次に何をすればいい?'),
    ],
    mustShow: [
      t('A clear confirmation naming what was saved',
        '무엇이 저장됐는지 명시하는 명확한 확인 메시지',
        '何が保存されたかを示す明確な確認メッセージ'),
      t('The obvious next step (view the record, add another, go back)',
        '분명한 다음 단계(레코드 보기, 추가, 돌아가기)',
        '明確な次の手順(レコード表示・追加・戻る)'),
    ],
    mustPreserve: [
      t('A way to reach the saved record or its identifier',
        '저장된 레코드나 식별자에 접근할 수 있는 경로',
        '保存されたレコードや識別子へ到達できる経路'),
    ],
    primaryActions: [
      t('Continue to the saved record or the next step',
        '저장된 레코드 또는 다음 단계로 진행',
        '保存されたレコードまたは次の手順へ進む'),
    ],
    secondaryActions: [
      t('Submit another entry',
        '항목을 하나 더 제출',
        'もう1件入力する'),
    ],
    mustNot: [
      t('Leave the form in a state that invites resubmitting the same data',
        '같은 데이터를 다시 제출하게 유도하는 상태로 폼을 두기',
        '同じデータを再送信させかねない状態でフォームを残す'),
      t('Show a vague "done" with no indication of what was saved or where it went',
        '무엇이 어디에 저장됐는지 없이 막연한 “완료”만 표시',
        '何がどこに保存されたか分からない曖昧な「完了」だけを表示'),
    ],
    accessibility: {
      announcement: t('Announce the success politely via aria-live (status)',
        '성공을 aria-live(status)로 방해되지 않게 안내',
        '成功をaria-live(status)で控えめに通知'),
      focus: t('Move focus to the confirmation or the next-step action',
        '포커스를 확인 메시지나 다음 단계 동작으로 이동',
        'フォーカスを確認メッセージや次の手順アクションへ移動'),
      keyboard: [
        t('The next-step action is keyboard reachable from the confirmation',
          '다음 단계 동작이 확인 메시지에서 키보드로 도달 가능',
          '次の手順アクションが確認メッセージからキーボードで到達可能'),
      ],
      contrast: [
        t('Success styling is not conveyed by green color alone',
          '성공 표시를 초록색만으로 전달하지 않음',
          '成功表示を緑色だけで伝えない'),
      ],
    },
    motion: {
      guidance: [
        t('A brief, single confirmation cue is enough; avoid prolonged celebration',
          '짧은 단발 확인 표시로 충분, 길게 끄는 축하 연출은 지양',
          '短い単発の確認表示で十分で、長い祝福演出は避ける'),
      ],
      reducedMotion: [
        t('Show the confirmation immediately with no animation',
          '애니메이션 없이 확인 메시지를 즉시 표시',
          'アニメーション無しで確認メッセージを即時表示'),
      ],
    },
  },
  {
    id: 'validating',
    surfaceIds: ['form'],
    category: 'data',
    criticality: 'recommended',
    name: t('Validating', '검증 중', '検証中'),
    summary: t(
      'A field value is being checked, often asynchronously (e.g. availability), before it can be confirmed valid.',
      '필드 값을 (예: 사용 가능 여부처럼) 흔히 비동기로 확인 중이라, 아직 유효한지 확정되지 않은 상태.',
      '項目の値を(例: 利用可否のように)多くは非同期で確認中で、まだ妥当か確定していない状態。'),
    aliases: ['checking', 'async validation', 'verifying', 'availability check', '확인 중', '비동기 검증', '検証処理中', '確認中'],
    domainSignals: ['validation', 'async', 'check', 'availability', 'form'],
    triggers: [
      t('A field requires a server check (uniqueness, availability)',
        '필드가 서버 확인(중복·사용 가능 여부)을 필요로 함',
        '項目がサーバー確認(重複・利用可否)を必要とする'),
      t('Validation runs after the user pauses typing or leaves the field',
        '입력을 멈추거나 필드를 벗어난 뒤 검증이 실행됨',
        '入力を止めるか項目を離れた後に検証が実行される'),
    ],
    userQuestions: [
      t('Is this value okay, or should I keep waiting?',
        '이 값이 괜찮은 건가, 아니면 더 기다려야 하나?',
        'この値で大丈夫?それともまだ待つべき?'),
      t('Why can I not submit yet?',
        '왜 아직 제출이 안 되지?',
        'なぜまだ送信できない?'),
    ],
    mustShow: [
      t('An inline "checking…" indicator next to the field being validated',
        '검증 중인 필드 옆에 인라인 “확인 중…” 표시',
        '検証中の項目のそばにインラインの「確認中…」表示'),
      t('That submit is briefly held until the check resolves',
        '확인이 끝날 때까지 제출이 잠시 보류됨을 표시',
        '確認が終わるまで送信が一時的に保留されることを表示'),
    ],
    mustPreserve: [
      t('The value the user typed while it is being checked',
        '확인하는 동안 사용자가 입력한 값',
        '確認中もユーザーが入力した値'),
      t('Focus and editability of other fields',
        '다른 필드의 포커스와 편집 가능 상태',
        '他項目のフォーカスと編集可能状態'),
    ],
    primaryActions: [
      t('Wait for the inline check to resolve',
        '인라인 확인이 끝나기를 대기',
        'インライン確認の完了を待つ'),
    ],
    secondaryActions: [
      t('Continue editing other fields meanwhile',
        '그동안 다른 필드를 계속 편집',
        'その間に他の項目を編集し続ける'),
    ],
    mustNot: [
      t('Block the whole form or freeze unrelated fields during the check',
        '확인 중에 폼 전체를 막거나 무관한 필드를 멈추기',
        '確認中にフォーム全体を塞いだり無関係な項目を止める'),
      t('Flash a premature error before the async check returns',
        '비동기 확인이 끝나기 전에 성급한 오류를 표시',
        '非同期確認が返る前に早まったエラーを表示'),
    ],
    accessibility: {
      announcement: t('Announce "checking" politely; do not interrupt typing',
        '“확인 중”을 은은하게 안내하되 입력을 방해하지 않기',
        '「確認中」を控えめに通知し、入力を妨げない'),
      focus: t('Leave focus where the user placed it; do not pull it to the spinner',
        '포커스를 사용자가 둔 자리에 유지, 스피너로 끌어가지 않기',
        'フォーカスをユーザーが置いた位置に維持し、スピナーへ移さない'),
      keyboard: [
        t('The pending state does not block keyboard navigation',
          '대기 상태가 키보드 내비게이션을 막지 않음',
          '保留状態がキーボード操作を妨げない'),
      ],
      contrast: [
        t('The checking indicator is distinguishable from error and success states',
          '확인 중 표시가 오류·성공 상태와 구별됨',
          '確認中表示がエラー・成功状態と区別できる'),
      ],
    },
    motion: {
      guidance: [
        t('Use a small, steady inline spinner scoped to the field',
          '필드에 한정된 작고 일정한 인라인 스피너 사용',
          '項目に限定した小さく一定のインラインスピナーを使う'),
      ],
      reducedMotion: [
        t('Replace the spinner with a static "Checking…" text',
          '스피너를 정적인 “확인 중…” 텍스트로 대체',
          'スピナーを静的な「確認中…」テキストに置き換える'),
      ],
    },
  },
  {
    id: 'dirty',
    surfaceIds: ['form'],
    category: 'interaction',
    criticality: 'recommended',
    name: t('Dirty', '변경됨', '変更あり'),
    summary: t(
      'The user has edited at least one field, so the form differs from its initial state but is not yet submitted.',
      '사용자가 최소 한 필드를 편집해 폼이 초기 상태와 달라졌지만 아직 제출되지 않은 상태.',
      'ユーザーが少なくとも1項目を編集し、フォームが初期状態と異なるが、まだ送信していない状態。'),
    aliases: ['modified', 'edited', 'touched', 'changed', 'has changes', '수정됨', '편집됨', '編集済み', '変更済み'],
    domainSignals: ['edit', 'change', 'modified', 'form'],
    triggers: [
      t('The user changes any field away from its initial value',
        '사용자가 어떤 필드든 초기값에서 변경',
        'ユーザーがいずれかの項目を初期値から変更'),
      t('The form now holds unsubmitted changes',
        '폼에 아직 제출되지 않은 변경이 있음',
        'フォームに未送信の変更がある'),
    ],
    userQuestions: [
      t('Have my changes been saved, or only typed so far?',
        '내 변경이 저장된 건가, 아직 입력만 한 건가?',
        '変更は保存された?それともまだ入力しただけ?'),
      t('Can I undo back to how it was?',
        '원래대로 되돌릴 수 있나?',
        '元に戻せる?'),
    ],
    mustShow: [
      t('That there are unsaved changes',
        '저장되지 않은 변경이 있음을 표시',
        '未保存の変更があることを表示'),
      t('An enabled save/submit action now that there is something to save',
        '저장할 내용이 생겼으므로 활성화된 저장·제출 동작',
        '保存対象ができたので有効化された保存・送信アクション'),
    ],
    mustPreserve: [
      t('Every edit the user made, exactly as entered',
        '사용자가 입력한 그대로의 모든 편집 내용',
        'ユーザーが入力したとおりの全ての編集'),
    ],
    primaryActions: [
      t('Save the changes',
        '변경 사항 저장',
        '変更を保存'),
    ],
    secondaryActions: [
      t('Revert to the last saved values',
        '마지막으로 저장된 값으로 되돌리기',
        '最後に保存した値に戻す'),
    ],
    mustNot: [
      t('Indicate "saved" while the changes are still only local',
        '변경이 아직 로컬에만 있는데 “저장됨”으로 표시',
        '変更がまだローカルだけなのに「保存済み」と表示'),
      t('Auto-save destructively without telling the user it happened',
        '사용자에게 알리지 않고 파괴적으로 자동 저장',
        'ユーザーに知らせず破壊的に自動保存する'),
    ],
    accessibility: {
      announcement: t('Announce the unsaved-changes status politely, not on every keystroke',
        '저장 안 됨 상태를 키 입력마다가 아니라 방해되지 않게 안내',
        '未保存状態をキー入力ごとではなく控えめに通知'),
      focus: t('Keep focus in the field being edited',
        '편집 중인 필드에 포커스 유지',
        '編集中の項目にフォーカスを維持'),
      keyboard: [
        t('Save and revert actions are keyboard reachable',
          '저장·되돌리기 동작이 키보드로 도달 가능',
          '保存・取り消しアクションがキーボードで到達可能'),
      ],
      contrast: [
        t('The unsaved indicator does not rely on color alone',
          '저장 안 됨 표시가 색상에만 의존하지 않음',
          '未保存表示が色だけに頼らない'),
      ],
    },
    motion: {
      guidance: [
        t('Surface the unsaved indicator subtly; no attention-grabbing motion',
          '저장 안 됨 표시를 은은하게 노출, 주의를 끄는 모션 금지',
          '未保存表示を控えめに出し、注意を引く動きは避ける'),
      ],
      reducedMotion: [
        t('Show the indicator statically with no transition',
          '전환 없이 표시를 정적으로 노출',
          'トランジション無しで表示を静的に出す'),
      ],
    },
  },
  {
    id: 'server-validation-error',
    surfaceIds: ['form'],
    category: 'data',
    criticality: 'recommended',
    name: t('Server validation error', '서버 검증 오류', 'サーバー検証エラー'),
    summary: t(
      'The form passed client checks, but the server rejected specific field values (e.g. duplicate, business rule).',
      '클라이언트 검증은 통과했지만 서버가 특정 필드 값을 거부한 상태(예: 중복, 업무 규칙).',
      'クライアント検証は通過したが、サーバーが特定の項目値を拒否した状態(例: 重複・業務ルール)。'),
    aliases: ['422', 'backend validation', 'rejected by server', 'field rejected', '서버 거부', '백엔드 검증', 'サーバー拒否', 'バックエンド検証'],
    domainSignals: ['validation', 'server', 'conflict', 'duplicate', 'form'],
    triggers: [
      t('The server returns field-level validation errors (e.g. 422)',
        '서버가 필드 단위 검증 오류(예: 422)를 반환',
        'サーバーが項目単位の検証エラー(例: 422)を返す'),
      t('A value violates a rule only the backend can check (duplicate, policy)',
        '백엔드만 검사할 수 있는 규칙(중복·정책)을 값이 위반',
        'バックエンドのみが確認できるルール(重複・ポリシー)に値が違反'),
    ],
    userQuestions: [
      t('It looked fine to me — which field did the server reject and why?',
        '내가 보기엔 괜찮았는데, 서버가 어떤 필드를 왜 거부했지?',
        '自分には問題なく見えた — どの項目をなぜサーバーが拒否した?'),
      t('Do I need to change one thing or start over?',
        '한 가지만 바꾸면 되나, 처음부터 다시 해야 하나?',
        '1つ直せばいい?最初からやり直し?'),
    ],
    mustShow: [
      t('The server message mapped back to the specific offending field',
        '서버 메시지를 문제가 된 해당 필드에 매핑해 표시',
        'サーバーのメッセージを問題の項目に対応づけて表示'),
      t('A clear correction path for that field',
        '해당 필드에 대한 명확한 수정 경로',
        'その項目に対する明確な修正経路'),
    ],
    mustPreserve: [
      t('All entered values, including the rejected field, for editing',
        '거부된 필드를 포함해 수정할 수 있도록 입력한 모든 값',
        '拒否された項目を含め、修正できるよう入力済みの全ての値'),
    ],
    primaryActions: [
      t('Jump to the rejected field and correct it',
        '거부된 필드로 이동해 수정',
        '拒否された項目へ移動して修正'),
    ],
    secondaryActions: [
      t('Review the rule the value violated',
        '값이 위반한 규칙 확인',
        '値が違反したルールを確認'),
    ],
    mustNot: [
      t('Show the raw server error payload or status code to the user',
        '서버 원시 오류 페이로드나 상태 코드를 사용자에게 노출',
        'サーバーの生エラーやステータスコードをユーザーに見せる'),
      t('Reset the form or drop the rejected value the user must edit',
        '폼을 초기화하거나 사용자가 고쳐야 할 거부된 값을 버리기',
        'フォームをリセットしたり、修正すべき拒否された値を捨てる'),
    ],
    accessibility: {
      announcement: t('Announce the server-side error assertively (role=alert)',
        '서버 측 오류를 단호하게(role=alert) 안내',
        'サーバー側エラーをはっきりと(role=alert)通知'),
      focus: t('Move focus to the rejected field or the mapped error',
        '포커스를 거부된 필드 또는 매핑된 오류로 이동',
        'フォーカスを拒否された項目または対応エラーへ移動'),
      keyboard: [
        t('The mapped error links to its field for keyboard users',
          '매핑된 오류가 키보드 사용자를 위해 해당 필드와 연결',
          '対応エラーがキーボード利用者のために項目と紐づく'),
      ],
      contrast: [
        t('Error text meets contrast and is not color-only',
          '오류 텍스트가 대비를 충족하고 색상만으로 전달하지 않음',
          'エラーテキストがコントラストを満たし色だけで伝えない'),
      ],
    },
    motion: {
      guidance: [
        t('Reveal the mapped error calmly in place; no shake',
          '매핑된 오류를 제자리에서 차분히 표시, 흔들림 금지',
          '対応エラーをその場で落ち着いて表示し、揺れは避ける'),
      ],
      reducedMotion: [
        t('Show the error immediately with no animation',
          '애니메이션 없이 오류를 즉시 표시',
          'アニメーション無しでエラーを即時表示'),
      ],
    },
  },
  {
    id: 'unsaved-changes',
    surfaceIds: ['form'],
    category: 'interaction',
    criticality: 'recommended',
    name: t('Unsaved changes', '저장되지 않은 변경', '未保存の変更'),
    summary: t(
      'The user tries to leave or close the form while it still holds edits that have not been saved.',
      '저장되지 않은 편집이 남아 있는 상태에서 사용자가 폼을 떠나거나 닫으려는 상태.',
      '保存されていない編集が残ったまま、ユーザーがフォームを離れる・閉じようとする状態。'),
    aliases: ['leave confirmation', 'discard changes', 'navigation guard', 'beforeunload', '이탈 확인', '변경 폐기', '離脱確認', '変更破棄'],
    domainSignals: ['navigation', 'leave', 'discard', 'dirty', 'form'],
    triggers: [
      t('The user navigates away, closes the tab, or hits back with unsaved edits',
        '저장 안 된 편집이 있는 채로 이동·탭 닫기·뒤로 가기를 시도',
        '未保存の編集があるまま移動・タブ閉じ・戻る操作をする'),
      t('A route change or dialog dismissal is requested while the form is dirty',
        '폼이 변경된 상태에서 라우트 전환이나 다이얼로그 닫힘이 요청됨',
        'フォームが変更状態でルート遷移やダイアログの閉鎖が要求される'),
    ],
    userQuestions: [
      t('Will I lose what I typed if I leave now?',
        '지금 나가면 입력한 게 사라지나?',
        '今離れたら入力した内容は失われる?'),
      t('Can I leave and come back to it later?',
        '나갔다가 나중에 다시 이어서 할 수 있나?',
        '一度離れて後で続けられる?'),
    ],
    mustShow: [
      t('A clear prompt that unsaved changes exist before leaving',
        '떠나기 전에 저장되지 않은 변경이 있다는 명확한 안내',
        '離れる前に未保存の変更があるという明確な確認'),
      t('Distinct choices to stay, save, or discard',
        '머무르기·저장·폐기를 명확히 구분한 선택지',
        '留まる・保存する・破棄するを明確に分けた選択肢'),
    ],
    mustPreserve: [
      t('All entered edits unless the user explicitly chooses to discard',
        '사용자가 명시적으로 폐기하지 않는 한 입력한 모든 편집',
        'ユーザーが明示的に破棄を選ばない限り入力済みの全編集'),
    ],
    primaryActions: [
      t('Stay on the form to keep editing',
        '폼에 머물러 계속 편집',
        'フォームに留まって編集を続ける'),
    ],
    secondaryActions: [
      t('Save and then leave',
        '저장 후 떠나기',
        '保存してから離れる'),
      t('Discard changes and leave',
        '변경을 폐기하고 떠나기',
        '変更を破棄して離れる'),
    ],
    mustNot: [
      t('Navigate away silently and lose the edits with no warning',
        '경고 없이 조용히 이동해 편집 내용을 잃게 하기',
        '警告なく黙って移動し編集内容を失わせる'),
      t('Make discard the default or easiest choice in the prompt',
        '안내에서 폐기를 기본값이나 가장 쉬운 선택으로 만들기',
        '確認で破棄を既定や最も押しやすい選択にする'),
    ],
    accessibility: {
      announcement: t('Present the prompt as a modal alert that takes focus',
        '안내를 포커스를 가져가는 모달 경고로 제시',
        '確認をフォーカスを受け取るモーダルアラートとして提示'),
      focus: t('Move focus into the prompt and back to the form if the user stays',
        '포커스를 안내로 옮기고 머무르면 폼으로 되돌리기',
        'フォーカスを確認へ移し、留まる場合はフォームへ戻す'),
      keyboard: [
        t('Escape maps to the safe choice (stay), not discard',
          'Escape는 안전한 선택(머무르기)에 대응, 폐기가 아님',
          'Escapeは安全な選択(留まる)に対応し、破棄ではない'),
      ],
      contrast: [
        t('The destructive discard action is visually distinguished, not just colored',
          '파괴적인 폐기 동작을 색상만이 아니라 시각적으로 구별',
          '破壊的な破棄アクションを色だけでなく視覚的に区別'),
      ],
    },
    motion: {
      guidance: [
        t('Present the prompt promptly without distracting transitions',
          '주의를 흩뜨리는 전환 없이 안내를 즉시 제시',
          '気を散らす遷移なく確認を速やかに提示'),
      ],
      reducedMotion: [
        t('Show the prompt instantly with no animation',
          '애니메이션 없이 안내를 즉시 표시',
          'アニメーション無しで確認を即時表示'),
      ],
    },
  },
  {
    id: 'read-only',
    surfaceIds: ['form'],
    category: 'permission',
    criticality: 'domain-specific',
    name: t('Read-only', '읽기 전용', '読み取り専用'),
    summary: t(
      'The user can view the form and its values but lacks permission (or context) to edit or submit it.',
      '사용자가 폼과 값을 볼 수는 있지만, 편집하거나 제출할 권한(또는 맥락)이 없는 상태.',
      'ユーザーはフォームと値を閲覧できるが、編集・送信する権限(または文脈)がない状態。'),
    aliases: ['view only', 'locked', 'no edit permission', 'disabled form', 'frozen', '보기 전용', '편집 불가', '閲覧のみ', '編集不可'],
    domainSignals: ['permission', 'role', 'read-only', 'locked', 'form'],
    triggers: [
      t('The user lacks edit permission for this record',
        '사용자가 이 레코드에 대한 편집 권한이 없음',
        'ユーザーがこのレコードの編集権限を持たない'),
      t('The record is locked by status, lifecycle, or another editor',
        '레코드가 상태·생명주기·다른 편집자에 의해 잠김',
        'レコードが状態・ライフサイクル・他の編集者によりロックされている'),
    ],
    userQuestions: [
      t('Why can I not edit this, and can I get access?',
        '왜 편집이 안 되고, 권한을 받을 수 있나?',
        'なぜ編集できない?権限はもらえる?'),
      t('Am I seeing the current, real values?',
        '내가 보는 게 현재의 실제 값이 맞나?',
        '見ているのは現在の実際の値?'),
    ],
    mustShow: [
      t('That the form is read-only and the reason (permission or lock)',
        '폼이 읽기 전용임과 그 이유(권한 또는 잠금)',
        'フォームが読み取り専用であることと理由(権限またはロック)'),
      t('The current field values clearly as non-editable',
        '현재 필드 값을 편집 불가로 명확히 표시',
        '現在の項目値を編集不可として明確に表示'),
    ],
    mustPreserve: [
      t('Full readability of the values and their formatting',
        '값과 그 형식의 완전한 가독성',
        '値とその書式の完全な可読性'),
    ],
    primaryActions: [
      t('Request edit access or the appropriate role',
        '편집 권한이나 적절한 역할을 요청',
        '編集権限や適切な役割を申請'),
    ],
    secondaryActions: [
      t('Copy or export the values for reference',
        '참고용으로 값을 복사하거나 내보내기',
        '参考用に値をコピーまたはエクスポート'),
    ],
    mustNot: [
      t('Make fields look editable when edits will be silently dropped',
        '편집이 조용히 무시되는데 필드를 편집 가능한 것처럼 보이게 하기',
        '編集が黙って無視されるのに項目を編集可能に見せる'),
      t('Render values so dimmed that they become unreadable',
        '값을 너무 흐리게 표시해 읽을 수 없게 만들기',
        '値を薄く表示しすぎて読めなくする'),
    ],
    accessibility: {
      announcement: t('No live alert; state the read-only condition as static text',
        '라이브 경고 없이, 읽기 전용 상태를 정적 텍스트로 안내',
        'ライブ警告なし、読み取り専用であることを静的テキストで案内'),
      focus: t('Allow focus to traverse fields for reading; do not trap it',
        '읽기를 위해 필드 사이로 포커스 이동 허용, 가두지 않기',
        '読むために項目間のフォーカス移動を許可し、閉じ込めない'),
      keyboard: [
        t('Fields are reachable and selectable but not editable',
          '필드에 도달·선택은 되지만 편집은 불가',
          '項目へ到達・選択はできるが編集はできない'),
      ],
      contrast: [
        t('Read-only values still meet text contrast minimums',
          '읽기 전용 값도 텍스트 대비 최소 기준을 충족',
          '読み取り専用の値もテキストコントラストの最低基準を満たす'),
      ],
    },
    motion: {
      guidance: [
        t('Present statically; no motion is needed for a view-only surface',
          '정적으로 표시, 보기 전용 화면에 모션 불필요',
          '静的に表示し、閲覧専用画面にモーションは不要'),
      ],
      reducedMotion: [
        t('No motion to remove; already static',
          '제거할 모션 없음, 이미 정적',
          '除去するモーションなし、すでに静的'),
      ],
    },
  },
  {
    id: 'autosaving',
    surfaceIds: ['form'],
    category: 'network',
    criticality: 'recommended',
    name: t('Autosaving', '자동 저장 중', '自動保存中'),
    summary: t(
      'A draft of the form is being saved in the background while the user keeps working, with no action required from them.',
      '사용자가 계속 작업하는 동안 폼 초안이 백그라운드에서 저장 중이며, 사용자가 따로 할 일은 없는 상태.',
      'ユーザーが作業を続ける間にフォームの下書きがバックグラウンドで保存中で、ユーザーの操作は不要な状態。'),
    aliases: ['saving draft', 'background save', 'auto-save in progress', 'syncing', '초안 저장 중', '백그라운드 저장', '자동 동기화', '下書き保存中', 'バックグラウンド保存', '自動同期'],
    domainSignals: ['autosave', 'draft', 'background', 'form'],
    triggers: [
      t('The user pauses typing and a background draft save begins',
        '사용자가 입력을 멈추자 백그라운드 초안 저장이 시작됨',
        'ユーザーが入力を止め、バックグラウンドの下書き保存が始まる'),
      t('A periodic autosave fires while the form is still being edited',
        '폼을 편집하는 도중 주기적인 자동 저장이 실행됨',
        'フォーム編集中に定期的な自動保存が実行される'),
    ],
    userQuestions: [
      t('Is my work being saved as I go, or do I need to save it myself?',
        '작업하는 대로 저장되고 있나, 아니면 내가 직접 저장해야 하나?',
        '作業しながら保存されている?それとも自分で保存する必要がある?'),
    ],
    mustShow: [
      t('An unobtrusive "saving…" indicator that does not block the work',
        '작업을 막지 않는 은은한 "저장 중…" 표시',
        '作業を妨げない控えめな「保存中…」表示'),
      t('That saving is automatic, so the user need not save manually',
        '자동으로 저장되므로 직접 저장할 필요가 없다는 점',
        '自動で保存されるため手動保存は不要であること'),
    ],
    mustPreserve: [
      t('Every value and edit the user is making right now',
        '사용자가 지금 입력·편집 중인 모든 값',
        'ユーザーが今入力・編集中の全ての値'),
      t('Cursor position and the field being edited',
        '커서 위치와 편집 중인 필드',
        'カーソル位置と編集中の項目'),
    ],
    primaryActions: [
      t('Keep editing; the save happens on its own',
        '계속 편집, 저장은 알아서 진행됨',
        '編集を続ける、保存は自動で進む'),
    ],
    secondaryActions: [
      t('Save now manually',
        '지금 수동으로 저장',
        '今すぐ手動で保存'),
    ],
    mustNot: [
      t('Block typing or freeze fields while the save runs',
        '저장이 도는 동안 입력을 막거나 필드를 멈추기',
        '保存中に入力を塞いだり項目を止める'),
      t('Steal focus or move the cursor to show the indicator',
        '표시를 보여주려고 포커스를 빼앗거나 커서를 옮기기',
        '表示のためにフォーカスを奪う・カーソルを移す'),
      t('Imply the draft is saved before the request actually completes',
        '요청이 실제로 끝나기 전에 저장됐다고 표시하기',
        '要求が実際に完了する前に保存済みと示す'),
    ],
    accessibility: {
      announcement: t('Announce "saving" via a polite live region; do not interrupt typing',
        '"저장 중"을 은은하게 안내하고 입력을 방해하지 않기',
        '「保存中」を控えめに通知し、入力を妨げない'),
      focus: t('Leave focus exactly where the user placed it',
        '포커스를 사용자가 둔 자리에 그대로 유지',
        'フォーカスをユーザーが置いた位置にそのまま維持'),
      keyboard: [
        t('The autosave state does not block keyboard navigation',
          '자동 저장 상태가 키보드 내비게이션을 막지 않음',
          '自動保存の状態がキーボード操作を妨げない'),
      ],
      contrast: [
        t('The saving indicator is distinguishable from the saved state',
          '저장 중 표시가 저장 완료 상태와 구별됨',
          '保存中の表示が保存完了状態と区別できる'),
      ],
    },
    motion: {
      guidance: [
        t('Use a small, quiet inline indicator; no looping spinner that pulls the eye',
          '작고 조용한 인라인 표시 사용, 시선을 끄는 반복 스피너 금지',
          '小さく静かなインライン表示を使い、目を引くループスピナーは避ける'),
      ],
      reducedMotion: [
        t('Show a static "Saving…" label with no animation',
          '애니메이션 없이 정적 "저장 중…" 라벨 표시',
          'アニメーション無しで静的な「保存中…」ラベルを表示'),
      ],
    },
  },
  {
    id: 'saved',
    surfaceIds: ['form'],
    category: 'data',
    criticality: 'recommended',
    name: t('Saved', '저장됨', '保存済み'),
    summary: t(
      'A background autosave finished successfully; the user just needs quiet confirmation that the draft is safe.',
      '백그라운드 자동 저장이 성공적으로 끝나, 초안이 안전하다는 조용한 확인만 있으면 되는 상태.',
      'バックグラウンドの自動保存が成功し、下書きが安全だという静かな確認だけあればよい状態。'),
    aliases: ['draft saved', 'autosaved', 'all changes saved', 'saved just now', '초안 저장됨', '자동 저장 완료', '모든 변경 저장됨', '下書き保存済み', '自動保存完了', '変更を保存しました'],
    domainSignals: ['autosave', 'saved', 'draft', 'form'],
    triggers: [
      t('A background autosave request completes successfully',
        '백그라운드 자동 저장 요청이 성공적으로 완료됨',
        'バックグラウンドの自動保存要求が正常に完了する'),
      t('The draft on the server now matches what the user has typed',
        '서버의 초안이 사용자가 입력한 내용과 일치하게 됨',
        'サーバー上の下書きがユーザーの入力内容と一致する'),
    ],
    userQuestions: [
      t('Is my work actually saved now, and when was that?',
        '내 작업이 지금 정말 저장된 건가, 언제 저장됐지?',
        '私の作業は今本当に保存された?それはいつ?'),
    ],
    mustShow: [
      t('A quiet "saved" confirmation',
        '조용한 "저장됨" 확인',
        '静かな「保存しました」の確認'),
      t('When it was saved (a timestamp or "just now")',
        '저장된 시점(타임스탬프 또는 "방금")',
        '保存された時点(タイムスタンプまたは「たった今」)'),
    ],
    mustPreserve: [
      t('The values and edits the user keeps working on',
        '사용자가 계속 작업하는 값과 편집 내용',
        'ユーザーが作業を続ける値と編集内容'),
      t('Focus and cursor position in the form',
        '폼 안의 포커스와 커서 위치',
        'フォーム内のフォーカスとカーソル位置'),
    ],
    primaryActions: [
      t('Keep editing',
        '계속 편집',
        '編集を続ける'),
    ],
    secondaryActions: [
      t('View version or save history',
        '버전·저장 기록 보기',
        'バージョン・保存履歴を見る'),
    ],
    mustNot: [
      t('Interrupt with a loud modal or dialog to confirm a routine save',
        '일상적인 저장을 알리려고 큰 모달·다이얼로그로 가로막기',
        'ありふれた保存のために大きなモーダル・ダイアログで割り込む'),
      t('Leave a persistent toast that covers the form content',
        '폼 내용을 가리는 토스트를 계속 띄워두기',
        'フォームの内容を覆うトーストを出し続ける'),
      t('Claim "saved" when the latest edits have not been sent yet',
        '최신 편집이 아직 전송되지 않았는데 "저장됨"이라고 하기',
        '最新の編集がまだ送られていないのに「保存済み」と称する'),
    ],
    accessibility: {
      announcement: t('Announce "saved" once via a polite live region, not on every keystroke',
        '"저장됨"을 키 입력마다가 아니라 방해되지 않게 한 번 안내',
        '「保存しました」をキー入力ごとではなく控えめに一度通知'),
      focus: t('Do not move focus; the confirmation is passive',
        '포커스를 옮기지 않기, 확인은 수동적으로 표시',
        'フォーカスを動かさない、確認は受動的に表示'),
      keyboard: [
        t('The save-history action is keyboard reachable',
          '저장 기록 동작이 키보드로 도달 가능',
          '保存履歴の操作がキーボードで到達可能'),
      ],
      contrast: [
        t('The saved confirmation is not conveyed by color alone',
          '저장 완료 표시를 색상만으로 전달하지 않음',
          '保存完了の表示を色だけで伝えない'),
      ],
    },
    motion: {
      guidance: [
        t('A brief, single fade to the "saved" state; no celebration',
          '"저장됨" 상태로 짧게 한 번 페이드, 축하 연출 금지',
          '「保存しました」状態へ短く一度フェード、祝福演出は禁止'),
      ],
      reducedMotion: [
        t('Swap to the saved label immediately with no transition',
          '전환 없이 저장됨 라벨로 즉시 교체',
          'トランジション無しで保存済みラベルに即時切り替え'),
      ],
    },
  },
  {
    id: 'save-conflict',
    surfaceIds: ['form'],
    category: 'data',
    criticality: 'recommended',
    name: t('Save conflict', '저장 충돌', '保存の競合'),
    summary: t(
      'A newer version was saved (by another session, device, or editor) since this draft began, so the local edits now conflict with the stored record.',
      '이 초안을 시작한 뒤 다른 세션·기기·편집자가 더 최신 버전을 저장해, 로컬 편집이 저장된 레코드와 충돌하는 상태.',
      'この下書きを始めた後に別のセッション・端末・編集者がより新しい版を保存したため、ローカルの編集が保存済みレコードと競合している状態。'),
    aliases: ['conflict', 'version conflict', 'concurrent edit', '409', 'stale write', 'optimistic concurrency', '충돌', '버전 충돌', '동시 편집', '競合', 'バージョン競合', '同時編集'],
    domainSignals: ['conflict', 'version', 'concurrent', 'collaboration', '409'],
    triggers: [
      t('A save returns a version conflict (e.g. HTTP 409) because the stored record changed',
        '저장 시 저장된 레코드가 바뀌어 버전 충돌(예: HTTP 409)이 반환됨',
        '保存時に保存済みレコードが変わっておりバージョン競合(例: HTTP 409)が返る'),
      t('Autosave detects the server copy is newer than the version this draft was based on',
        '자동 저장이 이 초안의 기준 버전보다 서버 사본이 더 최신임을 감지',
        '自動保存がこの下書きの基準版よりサーバー側が新しいと検知する'),
    ],
    userQuestions: [
      t('Someone (or another tab) changed this — will I lose my edits or overwrite theirs?',
        '누군가(또는 다른 탭)가 이걸 바꿨는데 — 내 편집이 사라지나, 아니면 그들 것을 덮어쓰나?',
        '誰か(別タブ)がこれを変更した — 自分の編集が消える?それとも相手の変更を上書きする?'),
    ],
    mustShow: [
      t('That a newer version exists and the save did not silently go through',
        '더 최신 버전이 있으며 저장이 조용히 처리되지 않았음',
        'より新しい版が存在し、保存が黙って通っていないこと'),
      t('Which fields differ between the local edits and the newer version',
        '로컬 편집과 최신 버전 사이에 어떤 필드가 다른지',
        'ローカル編集と新しい版でどの項目が異なるか'),
      t('A clear choice: keep mine, take theirs, or merge field by field',
        '명확한 선택지: 내 것 유지, 그들 것 가져오기, 필드별 병합',
        '明確な選択肢: 自分のを残す・相手のを採用・項目ごとにマージ'),
    ],
    mustPreserve: [
      t('The user\'s local edits until they explicitly choose to discard them',
        '사용자가 명시적으로 버리기를 선택하기 전까지 로컬 편집',
        'ユーザーが明示的に破棄を選ぶまでローカルの編集'),
      t('The newer stored version so it can be compared, not blindly overwritten',
        '비교할 수 있도록(무작정 덮어쓰지 않도록) 더 최신 저장본',
        '比較できるよう(やみくもに上書きしないよう)新しい保存版'),
    ],
    primaryActions: [t('Compare the two versions and choose how to resolve', '두 버전을 비교하고 해결 방식 선택', '2つの版を比較して解決方法を選ぶ')],
    secondaryActions: [
      t('Keep my edits (overwrite, with confirmation)', '내 편집 유지(확인 후 덮어쓰기)', '自分の編集を残す(確認のうえ上書き)'),
      t('Discard mine and load the newer version', '내 것 버리고 최신 버전 불러오기', '自分のを破棄して新しい版を読み込む'),
    ],
    mustNot: [
      t('Silently overwrite the newer version with the local edits',
        '로컬 편집으로 최신 버전을 조용히 덮어쓰기',
        'ローカル編集で新しい版を黙って上書きする'),
      t('Silently discard the user\'s local edits to take the newer version',
        '최신 버전을 받으려고 사용자의 로컬 편집을 조용히 버리기',
        '新しい版を採るためユーザーのローカル編集を黙って破棄する'),
      t('Hide that a conflict happened and present it as an ordinary save error',
        '충돌을 숨기고 평범한 저장 오류처럼 보여주기',
        '競合を隠してありふれた保存エラーのように見せる'),
    ],
    accessibility: {
      announcement: t('Announce the conflict assertively (role=alert); it needs a decision',
        '충돌을 단호하게(role=alert) 안내 — 결정이 필요함',
        '競合をはっきりと(role=alert)通知 — 判断が必要'),
      focus: t('Move focus to the resolution choices', '포커스를 해결 선택지로 이동', 'フォーカスを解決の選択肢へ移動'),
    },
    motion: {
      guidance: [t('Reveal the conflict panel calmly; no alarming animation', '충돌 패널을 차분히 표시, 불안한 애니메이션 금지', '競合パネルを落ち着いて表示し、不安を煽るアニメは避ける')],
      reducedMotion: [t('Show the conflict resolution immediately with no transition', '전환 없이 충돌 해결 화면을 즉시 표시', 'トランジション無しで競合解決画面を即時表示')],
    },
  },
];
